/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Advanced Governance Document per the WOS Advanced Governance Specification v1.0 (Layer 3). Targets a WOS Kernel Document and declares verifiable constraint subsets (SMT), equity guardrails, constraint zones (DCR-style), multi-step sessions, tool use governance, agent lifecycle state machines, calibration methods, drift detection methods, shadow mode, and circuit breaker patterns. These capabilities serve any complex workflow -- DCR constraint zones model compliance rules for human case management, equity monitoring applies to human decisions. WOS MUST NOT alter core Formspec processing semantics.
 */
export interface WOSAdvancedGovernanceDocument {
  /**
   * WOS Advanced Governance specification version. MUST be '1.0'.
   */
  $wosAdvancedGovernance: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this document targets.
   */
  targetWorkflow: string;
  /**
   * Version of this Advanced Governance Document.
   */
  version?: string;
  /**
   * Human-readable name for this advanced governance configuration.
   */
  title?: string;
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * Equity guardrails monitoring statistical disparities across demographic groupings (Advanced S3). Applies to human AND AI decisions. Evaluated asynchronously.
   */
  equityGuardrails?: EquityGuardrail[];
  /**
   * DCR-style constraint zones for adaptive case management (Advanced S4). Activities governed by declarative relations, not explicit transitions.
   */
  constraintZones?: ConstraintZone[];
  /**
   * Multi-step session definitions with checkpoints and intervention points (Advanced S5).
   */
  multiStepSessions?: MultiStepSession[];
  toolGovernance?: ToolGovernance;
  agentLifecycle?: AgentLifecycleConfig;
  /**
   * Constraints annotated for SMT verification (Advanced S8).
   */
  verifiableConstraints?: VerifiableConstraint[];
  calibration?: CalibrationConfig;
  driftDetection?: DriftDetectionConfig;
  shadowMode?: ShadowMode;
  circuitBreaker?: CircuitBreaker;
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface EquityGuardrail {
  /**
   * Unique guardrail identifier.
   */
  id: string;
  /**
   * Outcome metric to monitor.
   */
  metric: string;
  /**
   * Case file path defining the grouping dimension.
   */
  groupBy: string;
  /**
   * Maximum acceptable difference between highest and lowest group rates.
   */
  maxDisparity: number;
  /**
   * ISO 8601 duration of the evaluation window.
   */
  evaluationWindow: string;
  /**
   * Minimum observations per group for valid evaluation.
   */
  minimumSampleSize: number;
  /**
   * Action when disparity exceeds threshold. 'flag': record in provenance. 'alert': notify configured roles. 'suspend': alert plus suspend further autonomous processing.
   */
  onViolation: 'flag' | 'alert' | 'suspend';
  /**
   * Transition tags whose outcomes are monitored.
   */
  monitorTags?: string[];
  /**
   * Roles to notify on violation.
   */
  notifyRoles?: string[];
  /**
   * Human-readable explanation of this guardrail.
   */
  reason?: string;
}
export interface ConstraintZone {
  /**
   * Unique constraint zone identifier.
   */
  id: string;
  /**
   * Human-readable description of this constraint zone.
   */
  description?: string;
  /**
   * Activities within this constraint zone with initial markings.
   *
   * @minItems 1
   */
  activities: [ZoneActivity, ...ZoneActivity[]];
  /**
   * DCR relations governing activity dependencies.
   */
  relations: ZoneRelation[];
  /**
   * Event raised when the zone is satisfied.
   */
  completionEvent?: string;
}
export interface ZoneActivity {
  /**
   * Activity identifier within this zone.
   */
  id: string;
  /**
   * Reference to an activity definition.
   */
  activityRef?: string;
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * Whether this activity starts as included (available).
   */
  initialIncluded?: boolean;
  /**
   * Whether this activity starts as pending (must execute before zone completes).
   */
  initialPending?: boolean;
}
export interface ZoneRelation {
  /**
   * DCR relation type (Advanced S4.3).
   */
  type: 'condition' | 'response' | 'include' | 'exclude' | 'milestone';
  /**
   * Source activity identifier.
   */
  source: string;
  /**
   * Target activity identifier.
   */
  target: string;
  /**
   * Human-readable explanation of this relation.
   */
  description?: string;
}
export interface MultiStepSession {
  /**
   * Session identifier.
   */
  id: string;
  description?: string;
  maxSteps?: number;
  /**
   * ISO 8601 duration.
   */
  maxDuration?: string;
  checkpointPolicy?: 'afterEachStep' | 'atInterventionPoints' | 'onDemand';
  /**
   * DAG-ordered steps.
   *
   * @minItems 1
   */
  steps: [SessionStep, ...SessionStep[]];
}
export interface SessionStep {
  id: string;
  description?: string;
  /**
   * Step identifiers that must complete before this step.
   */
  dependsOn?: string[];
  interventionPoint?: boolean;
  interventionPrompt?: string;
}
/**
 * Tool use governance: permitted/prohibited registries, side-effect policy (Advanced S6).
 */
export interface ToolGovernance {
  /**
   * Registry of permitted tools.
   */
  toolRegistry?: ToolDefinition[];
  /**
   * Default policy for tools with side effects at autonomous level.
   */
  defaultSideEffectPolicy?: 'block' | 'allow' | 'requireApproval';
}
export interface ToolDefinition {
  id: string;
  category: string;
  sideEffects: boolean;
  rateLimit?: RateLimit;
  /**
   * Expected output schema.
   */
  outputSchema?: {
    [k: string]: unknown;
  };
  description?: string;
}
export interface RateLimit {
  maxPerMinute?: number;
  maxPerHour?: number;
}
/**
 * Agent lifecycle state machine configuration (Advanced S7).
 */
export interface AgentLifecycleConfig {
  /**
   * Initial lifecycle state for agents in this workflow (Advanced S7.1).
   */
  initialState?: 'active' | 'degraded' | 'suspended';
  /**
   * Lifecycle transition triggers. When omitted, transitions are manual-only.
   */
  transitions?: LifecycleTransition[];
  /**
   * Maximum autonomy level when agent is in degraded state.
   */
  degradedAutonomyCap?: 'autonomous' | 'supervisory' | 'assistive' | 'manual';
  /**
   * Notify administrators on model version changes.
   */
  versionChangeNotification?: boolean;
  /**
   * Roles to notify when an agent is suspended.
   */
  suspensionNotifyRoles?: string[];
}
export interface LifecycleTransition {
  /**
   * Transition name (Advanced S7.2).
   */
  name: 'demote' | 'restore' | 'suspend' | 'resume' | 'retire';
  /**
   * Condition that triggers this transition. FEL expression or human-readable description. When omitted, transition is manual-only.
   */
  trigger?: string;
  /**
   * Human-readable description of this trigger.
   */
  description?: string;
}
export interface VerifiableConstraint {
  /**
   * Reference to a deontic constraint id in the AI Integration Document.
   */
  constraintRef: string;
  /**
   * MUST be true. Annotates this constraint for SMT verification.
   */
  verifiable: true;
  /**
   * Expected verification result, if known from prior runs.
   */
  expectedResult?: 'proven-safe' | 'proven-unsafe' | 'inconclusive';
  /**
   * Notes on verifiability (e.g., which restrictions apply).
   */
  notes?: string;
  /**
   * FEL expression checked by tooling against the AdvGov S8.2 SMT verifiable subset (parse, linear arithmetic, finite-domain equality heuristics, etc.). Optional when the constraint is documented only in notes.
   */
  expression?: string;
  /**
   * Optional map from dotted field paths (as used in FEL, e.g. `output.status`) to explicit finite value domains. Suppresses variable-to-variable equality warnings in SMT subset linting when at least one side of the equality is a listed path.
   */
  finiteDomainDeclarations?: {
    [k: string]: {
      /**
       * Closed set of string values for the path.
       *
       * @minItems 1
       */
      domain: [string, ...string[]];
    };
  };
}
/**
 * Calibration method configuration (Advanced S9).
 */
export interface CalibrationConfig {
  /**
   * Calibration method (Advanced S9.2).
   */
  method?: 'plattScaling' | 'isotonic' | 'binning' | 'custom';
  /**
   * Minimum reviewed outputs for valid calibration.
   */
  minimumSamples?: number;
  /**
   * ISO 8601 duration for recalibration.
   */
  retrainingFrequency?: string;
}
/**
 * Drift detection method configuration (Advanced S10).
 */
export interface DriftDetectionConfig {
  /**
   * Configured drift detection methods.
   */
  methods?: DriftMethod[];
}
export interface DriftMethod {
  /**
   * Statistical method for drift detection.
   */
  method: 'psi' | 'ks' | 'chi2' | 'accuracy';
  threshold?: number;
  /**
   * ISO 8601 duration.
   */
  window?: string;
  dimensions?: DriftDimension[];
}
export interface DriftDimension {
  field: string;
  type: 'continuous' | 'categorical';
}
/**
 * Shadow mode configuration (Advanced S11.1). RECOMMENDED starting point for agents in rights-impacting workflows.
 */
export interface ShadowMode {
  enabled: boolean;
  compareTo?: 'human' | 'productionAgent';
  /**
   * ISO 8601 duration.
   */
  duration?: string;
  minimumSamples?: number;
}
/**
 * Circuit breaker pattern for automatic fallback on high error rates (Advanced S11.2).
 */
export interface CircuitBreaker {
  enabled: boolean;
  /**
   * Error rate that trips the breaker.
   */
  errorRateThreshold: number;
  evaluationWindow: string;
  /**
   * Minimum invocations before the breaker can trip.
   */
  minimumInvocations?: number;
  cooldownDuration: string;
  probeCount?: number;
}
