/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Agent Config sidecar document. Provides detailed operational configuration for an agent declared in a WOS AI Integration Document -- endpoint configuration, credential references, approved model version lists, calibration requirements, autonomy escalation and demotion policies, and per-action overrides. Operational parameters can be updated independently of the governance document.
 */
export interface WOSAgentConfig {
  /**
   * WOS Agent Config specification version. MUST be '1.0'.
   */
  $wosAgentConfig: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * Agent identifier within the AI Integration Document this config targets.
   */
  targetAgent: string;
  /**
   * URI of the AI Integration Document, if not co-located.
   */
  targetIntegration?: string;
  /**
   * Version of this Agent Config document.
   */
  version?: string;
  /**
   * Human-readable name for this agent configuration.
   */
  title?: string;
  endpoint?: EndpointConfig;
  /**
   * Approved model version list for 'approved' model version policy.
   */
  approvedVersions?: string[];
  calibration?: CalibrationConfig;
  autonomyPolicy?: AutonomyPolicy;
  /**
   * Per-action autonomy and constraint overrides.
   */
  actionOverrides?: ActionOverride[];
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Agent service endpoint configuration.
 */
export interface EndpointConfig {
  /**
   * Agent service endpoint URL.
   */
  url: string;
  /**
   * Reference to credential store entry.
   */
  credentialRef?: string;
  /**
   * Maximum invocation time as ISO 8601 duration.
   */
  timeout?: string;
  /**
   * Health check endpoint for availability monitoring.
   */
  healthCheckUrl?: string;
}
/**
 * Calibration requirements and schedule. When calibration has expired, effective autonomy is capped at assistive.
 */
export interface CalibrationConfig {
  /**
   * Whether calibration is required for this agent.
   */
  required: boolean;
  /**
   * Re-calibration frequency as ISO 8601 duration. Required when 'required' is true.
   */
  frequency?: string;
  /**
   * Minimum reviewed outputs for valid calibration.
   */
  minimumSamples?: number;
  /**
   * Calibration method.
   */
  method?: 'plattScaling' | 'isotonic' | 'binning' | 'custom';
}
/**
 * Dynamic autonomy escalation and demotion rules.
 */
export interface AutonomyPolicy {
  /**
   * Conditions under which autonomy may be elevated.
   */
  escalation?: EscalationRule[];
  /**
   * Conditions under which autonomy is automatically reduced.
   */
  demotion?: DemotionRule[];
  /**
   * Maximum autonomy level this agent may reach.
   */
  maxAutonomy?: 'autonomous' | 'supervisory' | 'assistive' | 'manual';
}
export interface EscalationRule {
  /**
   * FEL expression evaluated against agent operational state and case data.
   */
  condition: string;
  /**
   * Autonomy level to escalate to when condition is met.
   */
  targetLevel: 'autonomous' | 'supervisory' | 'assistive';
  /**
   * ISO 8601 duration after which the escalation expires and the agent reverts to its prior autonomy level (AI Integration S5.4).
   */
  escalationExpiry?: string;
  /**
   * Human-readable explanation.
   */
  description?: string;
}
export interface DemotionRule {
  /**
   * FEL expression evaluated against agent operational state and case data.
   */
  condition: string;
  /**
   * Autonomy level to demote to when condition is met.
   */
  targetLevel: 'supervisory' | 'assistive' | 'manual';
  /**
   * When true, agent operates at demoted level until recalibration meets escalation conditions.
   */
  pendingRecalibration?: boolean;
  /**
   * Human-readable explanation.
   */
  description?: string;
}
export interface ActionOverride {
  /**
   * Reference to the action in the kernel lifecycle.
   */
  actionRef: string;
  /**
   * Override autonomy level for this action.
   */
  autonomy?: 'autonomous' | 'supervisory' | 'assistive' | 'manual';
  /**
   * Override review window for supervisory actions (ISO 8601 duration).
   */
  reviewWindow?: string;
  /**
   * Override confidence floor for this action.
   */
  confidenceFloor?: number;
}
