/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Enforcement action for a deontic constraint violation (AI Integration S4.6). Restriction ordering: reject > escalateToHuman > switchToAssistive > flag.
 */
export type ViolationAction = 'reject' | 'escalateToHuman' | 'switchToAssistive' | 'flag';
/**
 * Override for null propagation behavior (AI Integration S4.9). When omitted, determined by the kernel's impactLevel.
 */
export type NullBehavior = 'pass' | 'deny' | 'escalate';

/**
 * A WOS AI Integration Document per the WOS AI Integration Specification v1.0 (Layer 2). Targets a WOS Kernel Document and declares agent registration, deontic constraints (permission/prohibition/obligation/right), autonomy levels with impact-level caps, Formspec-as-validator pattern, confidence framework with decay, fallback chains, decision drift detection, AI-specific oversight extensions, volume constraints, agent-specific review sampling, agent disclosure, and Narrative provenance tier. Every Layer 2 concept extends a Layer 1 (Workflow Governance) concept through the kernel's named seams. The agent is outside the trust boundary -- the WOS Processor enforces all governance. WOS MUST NOT alter core Formspec processing semantics.
 */
export interface WOSAIIntegrationDocument {
  /**
   * WOS AI Integration specification version. MUST be '1.0'. Identifies this document as a WOS AI Integration Document.
   */
  $wosAIIntegration: '1.0';
  /**
   * Optional JSON Schema URI for editor validation and autocompletion.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this AI integration document targets. MUST match the url property of the target Kernel Document.
   */
  targetWorkflow: string;
  /**
   * Version of this AI Integration Document.
   */
  version?: string;
  /**
   * Human-readable name for this AI integration configuration.
   */
  title?: string;
  /**
   * Human-readable description of how AI agents participate in this workflow.
   */
  description?: string;
  /**
   * Default autonomy level for agent actions in this workflow (AI Integration S5). Autonomy is a property of the action site, not the agent. Individual actions MAY override this default. The effective autonomy MUST NOT exceed the impact-level cap.
   */
  defaultAutonomy?: 'autonomous' | 'supervisory' | 'assistive' | 'manual';
  /**
   * Agent declarations registered via the actorExtension seam (AI Integration S3).
   *
   * @minItems 1
   */
  agents: [AgentDeclaration, ...AgentDeclaration[]];
  deonticConstraints?: DeonticConstraints1;
  confidenceFloor?: ConfidenceFloor;
  /**
   * Default fallback chain for agent invocation failures (AI Integration S8). MUST terminate in escalateToHuman or fail. MUST NOT cycle.
   */
  fallbackChain?: FallbackLevel[];
  oversightExtensions?: OversightExtensions;
  volumeConstraints?: VolumeConstraints;
  reviewSampling?: AgentReviewSampling;
  agentDisclosure?: AgentDisclosure;
  narrativeTier?: NarrativeTierConfig;
  driftDetection?: DriftDetectionConfig;
  assistGovernanceProxy?: AssistGovernanceProxy;
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface AgentDeclaration {
  /**
   * Unique agent identifier within the workflow.
   */
  id: string;
  /**
   * Actor type. MUST be 'agent' for agent declarations.
   */
  type: 'agent';
  /**
   * Agent type taxonomy (AI Integration S3.2). 'deterministic': rules engines, output is a pure function of input. 'statistical': classical ML, bounded output space, calibratable. 'generative': LLMs, unbounded output, non-deterministic, injection-vulnerable.
   */
  agentType: 'deterministic' | 'statistical' | 'generative';
  /**
   * Identifier of the model powering this agent.
   */
  modelIdentifier: string;
  /**
   * Version of the model.
   */
  modelVersion: string;
  /**
   * Human-readable description of the agent's role in the workflow.
   */
  description?: string;
  /**
   * Declared capabilities with I/O contracts (AI Integration S3.3).
   */
  capabilities?: Capability[];
  /**
   * Model version policy (AI Integration S3.4). 'pinned': exactly the declared version. 'approved': any version from an approved list. 'latest': latest available, version recorded in provenance.
   */
  modelVersionPolicy?: 'pinned' | 'approved' | 'latest';
  confidenceDecay?: ConfidenceDecay;
  /**
   * Agent-specific fallback chain. Overrides the workflow-level fallback chain for this agent.
   */
  fallbackChain?: FallbackLevel[];
  /**
   * Agent IDs that this agent may invoke at autonomous level (AI Integration S3.7). Required when cascading autonomous agents are used.
   */
  cascadingInvocations?: string[];
  /**
   * Extension data for this agent declaration.
   */
  extensions?: {
    [k: string]: unknown;
  };
  deonticConstraints?: DeonticConstraints;
}
export interface Capability {
  /**
   * Capability identifier.
   */
  id: string;
  /**
   * What this capability does.
   */
  description?: string;
  /**
   * Formspec Definition or JSON Schema URI for input. Uses headless contract pattern (Core S2.3).
   */
  inputContractRef?: string;
  /**
   * Formspec Definition or JSON Schema URI for output. Agent output is validated against this contract (Formspec-as-validator, S6).
   */
  outputContractRef?: string;
}
/**
 * Agent-specific confidence decay configuration (AI Integration S7.5).
 */
export interface ConfidenceDecay {
  /**
   * Whether confidence decay is active.
   */
  enabled: boolean;
  /**
   * ISO 8601 duration after which effective confidence halves.
   */
  halfLife?: string;
  /**
   * Events causing immediate confidence reduction.
   */
  triggers?: DecayTrigger[];
}
export interface DecayTrigger {
  /**
   * Event that triggers confidence decay.
   */
  event: string;
  /**
   * Multiplicative decay factor (0-1). Effective confidence is multiplied by this factor when the event fires.
   */
  decayFactor: number;
}
export interface FallbackLevel {
  /**
   * Fallback action type (AI Integration S8.3).
   */
  action: 'escalateToHuman' | 'retry' | 'alternateAgent' | 'fail';
  /**
   * Task reference for escalateToHuman.
   */
  taskRef?: string;
  /**
   * Maximum retry attempts for retry action.
   */
  maxRetries?: number;
  /**
   * Backoff strategy for retry action.
   */
  backoff?: 'fixed' | 'exponential' | 'linear';
  /**
   * ISO 8601 duration for initial retry interval.
   */
  initialInterval?: string;
  /**
   * Agent identifier for alternateAgent action.
   */
  alternateAgentRef?: string;
  /**
   * Actor to assign the escalated task to. Used with escalateToHuman action.
   */
  assignTo?: string;
}
/**
 * Agent-level deontic constraints (AI Integration S4.7). Apply to all invocations of this agent.
 */
export interface DeonticConstraints {
  /**
   * Permissions bounding what agents are allowed to produce (AI Integration S4.2).
   */
  permissions?: Permission[];
  /**
   * Prohibitions forbidding specified agent outputs or actions (AI Integration S4.3).
   */
  prohibitions?: Prohibition[];
  /**
   * Obligations requiring agents to include specified content (AI Integration S4.4).
   */
  obligations?: Obligation[];
  /**
   * Rights specifying what agents are entitled to receive as input (AI Integration S4.5).
   */
  rights?: Right[];
}
export interface Permission {
  /**
   * Unique permission identifier.
   */
  id: string;
  /**
   * Fields the agent is permitted to produce.
   */
  allowedFields?: string[];
  /**
   * Specific field this permission constrains.
   */
  field?: string;
  /**
   * FEL expression defining value bounds.
   */
  bounds?: string;
  onViolation: ViolationAction;
  nullBehavior?: NullBehavior;
  /**
   * Whether an authorized actor may bypass this constraint with structured rationale (AI Integration S4.7).
   */
  bypassable?: boolean;
}
export interface Prohibition {
  /**
   * Unique prohibition identifier.
   */
  id: string;
  /**
   * FEL expression defining the forbidden condition. When true, the prohibition is triggered.
   */
  condition: string;
  /**
   * Human-readable explanation. Included in provenance when triggered.
   */
  reason?: string;
  onViolation: ViolationAction;
  nullBehavior?: NullBehavior;
  /**
   * Whether an authorized actor may bypass this constraint with structured rationale (AI Integration S4.7).
   */
  bypassable?: boolean;
}
export interface Obligation {
  /**
   * Unique obligation identifier.
   */
  id: string;
  /**
   * FEL expression defining the required condition. When false, the obligation is unmet.
   */
  requirement: string;
  /**
   * Human-readable explanation.
   */
  reason?: string;
  onViolation: ViolationAction;
  nullBehavior?: NullBehavior;
  /**
   * Whether an authorized actor may bypass this constraint with structured rationale (AI Integration S4.7).
   */
  bypassable?: boolean;
}
export interface Right {
  /**
   * Unique right identifier.
   */
  id: string;
  /**
   * Path or reference specifying the data the agent is entitled to receive.
   */
  entitlement: string;
  /**
   * Human-readable description.
   */
  description?: string;
}
/**
 * Deontic constraint framework governing agent behavior (AI Integration S4). Four constraint types from OASIS LegalRuleML: permissions, prohibitions, obligations, rights. Evaluated after contract validation, before output commit. The WOS Processor is the Policy Enforcement Point.
 */
export interface DeonticConstraints1 {
  /**
   * Permissions bounding what agents are allowed to produce (AI Integration S4.2).
   */
  permissions?: Permission[];
  /**
   * Prohibitions forbidding specified agent outputs or actions (AI Integration S4.3).
   */
  prohibitions?: Prohibition[];
  /**
   * Obligations requiring agents to include specified content (AI Integration S4.4).
   */
  obligations?: Obligation[];
  /**
   * Rights specifying what agents are entitled to receive as input (AI Integration S4.5).
   */
  rights?: Right[];
}
/**
 * Workflow-level minimum confidence threshold (AI Integration S7.4). Part of the enforcement ordering (step 4).
 */
export interface ConfidenceFloor {
  /**
   * Minimum acceptable confidence for the declared autonomy level.
   */
  threshold: number;
  /**
   * Enforcement action when confidence falls below threshold.
   */
  onViolation: 'escalateToHuman' | 'reject';
}
/**
 * AI-specific extensions to Layer 1 review protocols (AI Integration S10). Attach via lifecycleHook on review-tagged transitions.
 */
export interface OversightExtensions {
  /**
   * When true and independentFirst protocol is active, hide agent output until the reviewer's independent assessment is recorded (AI Integration S10.2).
   */
  suppressAgentOutput?: boolean;
  presentation?: OversightPresentation;
}
/**
 * Presentation properties for AI-assisted review steps.
 */
export interface OversightPresentation {
  /**
   * Display the agent's confidence score.
   */
  showConfidence?: boolean;
  /**
   * Display alternative recommendations.
   */
  showAlternatives?: boolean;
  /**
   * Visually highlight fields with below-threshold confidence.
   */
  highlightLowConfidenceFields?: boolean;
  /**
   * Highlight differences between reviewer's independent assessment and agent's recommendation. Only meaningful with independentFirst protocol.
   */
  showDiffFromIndependent?: boolean;
}
/**
 * Rate limits on autonomous agent actions (AI Integration S11). Part of the enforcement ordering (step 5).
 */
export interface VolumeConstraints {
  /**
   * Maximum autonomous agent actions per hour.
   */
  maxAutonomousPerHour?: number;
  /**
   * Maximum autonomous agent actions per day.
   */
  maxAutonomousPerDay?: number;
}
/**
 * Agent-specific review sampling extending Layer 1 quality controls (AI Integration S11.2). Part of the enforcement ordering (step 6).
 */
export interface AgentReviewSampling {
  /**
   * Fraction of agent actions to sample for human review.
   */
  rate: number;
  /**
   * Sampling method (AI Integration S11.2). 'stratified': by agent type, confidence, or case characteristics. 'adversarial': targeted sampling of cases likely to reveal agent weaknesses.
   */
  method?: 'random' | 'stratified' | 'adversarial';
  /**
   * Sampling scope.
   */
  scope?: 'workflow' | 'agent';
}
/**
 * Agent disclosure requirements extending Layer 1 due process (AI Integration S12). Attach via lifecycleHook on adverse-decision-tagged transitions.
 */
export interface AgentDisclosure {
  /**
   * Disclose that an AI system assisted in the determination (AI Integration S12.2). MUST be true for rights-impacting workflows. Consistent with OMB M-24-10 and EU AI Act Art. 13.
   */
  discloseThatAgentAssisted: boolean;
  /**
   * Disclose the model identifier.
   */
  discloseModelIdentity?: boolean;
  /**
   * Disclose the agent's confidence score.
   */
  discloseConfidence?: boolean;
}
/**
 * Configuration for the Narrative provenance tier (AI Integration S13). Attach via provenanceLayer seam.
 */
export interface NarrativeTierConfig {
  /**
   * Whether agents should produce Narrative tier records.
   */
  enabled?: boolean;
  /**
   * Transition tags that require Narrative tier records from agent actors.
   */
  requiredForTags?: string[];
}
/**
 * Decision drift detection configuration (AI Integration S9).
 */
export interface DriftDetectionConfig {
  /**
   * Whether agents must disclose training data characteristics (AI Integration S9.2).
   */
  trainingDataDisclosure?: boolean;
  /**
   * Whether agents must disclose their optimization objective.
   */
  optimizationObjectiveDisclosure?: boolean;
  rubberStampMonitoring?: RubberStampConfig;
}
/**
 * Rubber-stamp detection configuration (AI Integration S9.2).
 */
export interface RubberStampConfig {
  /**
   * Whether rubber-stamp detection is active.
   */
  enabled?: boolean;
  /**
   * ISO 8601 duration below which a review is flagged as potentially rubber-stamped.
   */
  minReviewTime?: string;
  /**
   * Agreement rate above which reviewer engagement is flagged as declining.
   */
  maxAgreementRate?: number;
  /**
   * ISO 8601 duration of the evaluation window.
   */
  evaluationWindow?: string;
}
/**
 * WOS Assist Governance Proxy configuration (AI Integration S14). A WOS construct consuming the Formspec Assist protocol (Assist S2.1).
 */
export interface AssistGovernanceProxy {
  /**
   * Whether the WOS Assist Governance Proxy is active.
   */
  enabled?: boolean;
  /**
   * Per-tool-category governance configuration. The proxy consumes the Assist protocol (Assist S2.1, S7) and applies WOS deontic constraints.
   */
  toolCategories?: ToolCategoryGovernance[];
}
export interface ToolCategoryGovernance {
  /**
   * Tool category identifier.
   */
  category: string;
  constraints?: DeonticConstraints2;
  /**
   * Maximum tool invocations in this category per session.
   */
  maxInvocationsPerSession?: number;
}
/**
 * Deontic constraints specific to this tool category.
 */
export interface DeonticConstraints2 {
  /**
   * Permissions bounding what agents are allowed to produce (AI Integration S4.2).
   */
  permissions?: Permission[];
  /**
   * Prohibitions forbidding specified agent outputs or actions (AI Integration S4.3).
   */
  prohibitions?: Prohibition[];
  /**
   * Obligations requiring agents to include specified content (AI Integration S4.4).
   */
  obligations?: Obligation[];
  /**
   * Rights specifying what agents are entitled to receive as input (AI Integration S4.5).
   */
  rights?: Right[];
}
