/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Assertion Gate Library sidecar document. Provides a reusable collection of assertion gate definitions for WOS data validation pipelines. Pipelines reference assertions by identifier, enabling shared definitions across multiple pipelines and governance documents.
 */
export interface WOSAssertionGateLibrary {
  /**
   * WOS Assertion Gate Library specification version. MUST be '1.0'.
   */
  $wosAssertionLibrary: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * Canonical URI identifier for this library.
   */
  url?: string;
  /**
   * Version of this library document.
   */
  version?: string;
  /**
   * Human-readable name for this assertion library.
   */
  title?: string;
  /**
   * Human-readable description of this library's purpose.
   */
  description?: string;
  /**
   * Reusable assertion definitions. Referenced by pipeline stages via id.
   *
   * @minItems 1
   */
  assertions: [AssertionDefinition, ...AssertionDefinition[]];
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface AssertionDefinition {
  /**
   * Unique assertion identifier. Referenced by pipeline stages.
   */
  id: string;
  /**
   * Assertion gate type (Governance S5.4).
   */
  type: 'source-grounded' | 'arithmetic' | 'range' | 'consistency' | 'format' | 'cross-document' | 'temporal';
  /**
   * FEL expression defining the assertion constraint.
   */
  expression?: string;
  /**
   * Fields subject to this assertion.
   */
  fields?: string[];
  /**
   * Reference to a pipeline stage for consistency checking.
   */
  referenceStage?: string;
  /**
   * Human-readable description of what this assertion checks.
   */
  description: string;
  /**
   * Default rejection policy when this assertion fails.
   */
  rejectionPolicy?: 'retryWithCorrections' | 'escalateToSupervisor' | 'holdPendingData' | 'failWithExplanation';
}
