/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Assurance-level and subject-continuity declarations (WOS Assurance Layer).
 */
export interface WOSAssuranceDeclaration {
  /**
   * Ordered assurance level per S2.1. Base values: L1 (self-asserted), L2 (corroborated), L3 (verified), L4 (in-person). Implementations MAY define additional levels declared against the base four.
   */
  assuranceLevel?: string;
  /**
   * Subject continuity reference (S3).
   */
  subjectContinuity?: {
    reference: string;
    scope: 'instance' | 'case' | 'tenant' | 'deployment';
    [k: string]: unknown;
  };
  /**
   * Disclosure posture — independent of assuranceLevel per Invariant 6 (S4).
   */
  disclosurePosture?: 'anonymous' | 'pseudonymous' | 'identified' | 'public';
  /**
   * Provider-neutral attestation (S5).
   */
  attestation?: {
    subject: string;
    predicate: string;
    basis: string;
    validityScope?: string;
    [k: string]: unknown;
  };
}
