/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Business Calendar Config sidecar document. Defines business days, holiday schedules, and operating hours for SLA evaluation and temporal parameter resolution in WOS workflows. Government workflows measure deadlines in business days, not wall-clock time: a 30-day response window excludes weekends and holidays. The governance layer's SLA evaluation (Governance S10.3) and temporal parameter resolution (Governance S13.3) consume this sidecar when present. When absent, SLA evaluation uses wall-clock time.
 */
export interface WOSBusinessCalendarConfig {
  /**
   * WOS Business Calendar specification version. MUST be '1.0'.
   */
  $wosBusinessCalendar: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this business calendar applies to.
   */
  targetWorkflow: string;
  /**
   * Version of this Business Calendar Config document.
   */
  version?: string;
  /**
   * Human-readable name for this business calendar.
   */
  title?: string;
  /**
   * Human-readable description of this business calendar.
   */
  description?: string;
  /**
   * IANA timezone identifier. All time calculations for this calendar use this timezone. Operating hours (when present) are interpreted in this timezone.
   */
  timezone: string;
  /**
   * Ordered list of working days. A date is a business day only if its day-of-week appears in this array and the date is not a holiday. Standard US federal work week: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'].
   *
   * @minItems 1
   */
  workWeek: [
    'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday',
    ...('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[],
  ];
  /**
   * Holiday schedule. Days listed here are non-working regardless of workWeek. Includes both fixed-date holidays (e.g., July 4) and floating holidays (e.g., third Monday of January).
   */
  holidays?: Holiday[];
  operatingHours?: OperatingHours;
  /**
   * Date this calendar becomes effective (ISO 8601 date). When absent, the calendar is effective immediately.
   */
  effectiveDate?: string;
  /**
   * Date this calendar expires (ISO 8601 date). A processor MUST ignore an expired calendar and fall back to wall-clock time.
   */
  expirationDate?: string;
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface Holiday {
  /**
   * Human-readable holiday name.
   */
  name: string;
  /**
   * Fixed date for this holiday (ISO 8601 date). Required when 'rule' is not specified. One of 'date' or 'rule' MUST be present.
   */
  date?: string;
  /**
   * Recurrence rule for floating holidays. Required when 'date' is not specified. Standard rules: 'nthWeekday(n, weekday, month)' for the nth weekday in a month, 'lastWeekday(weekday, month)' for the last weekday in a month. One of 'date' or 'rule' MUST be present.
   */
  rule?: string;
  /**
   * Whether this entry is an observed date rather than the actual holiday. When a fixed-date holiday falls on a non-working day, a separate entry with 'observed: true' marks the actual day off.
   */
  observed?: boolean;
}
/**
 * Working hours within a business day. When present and an SLA is specified in hours, the processor counts only elapsed time during these hours. When absent, a business day is the full 24-hour period.
 */
export interface OperatingHours {
  /**
   * Start of the operating period (HH:MM in 24-hour format). The operating period is [start, end) -- inclusive of start, exclusive of end.
   */
  start: string;
  /**
   * End of the operating period (HH:MM in 24-hour format). MUST be after 'start'.
   */
  end: string;
}
