/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS CaseInstance document per the WOS Runtime Companion v1.0. A CaseInstance is the serialization format for a running workflow instance -- it captures the complete runtime state needed to resume processing after a crash, migrate between processors, or audit past behavior. This is a runtime artifact, not a WOS document type: it has no $wos* marker because it is produced and consumed by processors, not authored by workflow designers. The instance shape is normatively defined so that instances can migrate between conformant processors without data loss.
 */
export interface WOSCaseInstance {
  /**
   * Optional JSON Schema URI for editor validation and autocompletion.
   */
  $schema?: string;
  /**
   * Globally unique identifier for this workflow instance. Stable for the lifetime of the instance.
   */
  instanceId: string;
  /**
   * Canonical URL of the Kernel Document governing this instance. Together with definitionVersion, identifies the exact document that controls this instance's lifecycle, case state schema, and contract bindings.
   */
  definitionUrl: string;
  /**
   * Version of the Kernel Document, pinned at instance creation (Kernel S9.6). Running instances remain on their creation-time version unless explicitly migrated (Runtime Companion S11).
   */
  definitionVersion: string;
  /**
   * Active leaf states as an ordered array. The order is deterministic: document order of state declarations within the kernel, depth-first. In a workflow without parallel states, this array contains exactly one element. In a workflow with parallel states, it contains one element per active region. Empty array only for completed or terminated instances.
   *
   * @minItems 0
   */
  configuration: string[];
  /**
   * Current case file field values. The keys are field names declared in the Kernel Document's caseFile.fields (Kernel S5.2). Values conform to the declared field types (Kernel S5.3).
   */
  caseState: {
    [k: string]: unknown;
  };
  /**
   * Index into the append-only provenance log. Indicates how many provenance records have been durably persisted for this instance. Used for crash recovery: on restart, the processor knows which provenance records are already durable.
   */
  provenancePosition: number;
  /**
   * Pending timer state. Empty array when no timers are active. After a processor restart, all timers in this array are reconstituted and scheduled for firing at their original deadlines (Runtime Companion S7.3).
   */
  timers: TimerState[];
  /**
   * Durable nonterminal task state. Empty array when no tasks are active. Terminal task history lives in provenance.
   */
  activeTasks: ActiveTask[];
  /**
   * Saved history state configurations, keyed by compound state identifier. Present only when the Kernel Document uses history states (Kernel S4.14, Lifecycle Detail S3). Each entry is the saved leaf-state configuration within that compound state.
   */
  historyStore?: {
    /**
     * Saved configuration for this compound state -- the states that were active when the compound state was last exited.
     */
    [k: string]: string[];
  };
  /**
   * Active compensation logs, keyed by compensable scope identifier. Present only when compensable scopes are active (Lifecycle Detail S5). Each log records completed actions that have declared compensatingActions, in forward completion order.
   */
  compensationLogs?: {
    [k: string]: CompensationLog;
  };
  /**
   * Instance status. 'active': processing events normally. 'suspended': paused, no events processed until resumed. 'migrating': definition version change in progress. 'completed': lifecycle reached a top-level final state. 'terminated': explicitly terminated. Completed and terminated are irreversible terminal states.
   */
  status: 'active' | 'suspended' | 'migrating' | 'completed' | 'terminated';
  /**
   * ISO 8601 timestamp of instance creation.
   */
  createdAt: string;
  /**
   * ISO 8601 timestamp of last state change (transition fired, case state mutated, status changed).
   */
  updatedAt: string;
  /**
   * Events enqueued but not yet processed (Kernel S9.1 G5, Runtime Companion S12.8). FIFO order. Empty array when no events are pending. On processor restart, the processor resumes processing from the head of this queue.
   */
  pendingEvents?: PendingEvent[];
  governanceState?: GovernanceState;
  volumeCounters?: VolumeCounters;
  /**
   * Extension data. All keys MUST be prefixed with 'x-'. Implementations MAY use this for deployment-specific metadata (e.g., x-correlationId, x-tenantId, x-deploymentRegion).
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Captures the state of a pending durable timer.
 */
export interface TimerState {
  /**
   * Timer identifier, as declared in the startTimer action (Kernel S9.2).
   */
  timerId: string;
  /**
   * Absolute deadline when this timer fires (ISO 8601). If the original startTimer action used a relative duration, the processor converts it to an absolute deadline at creation time.
   */
  deadline: string;
  /**
   * Event to emit when the timer fires. Typically a $timeout.* kernel-generated event (Kernel S4.10).
   */
  event: string;
  /**
   * The state or region that scoped this timer. Used for cancellation on region exit (Lifecycle Detail S6.5) and timer reset on state reentry (Lifecycle Detail S6.4).
   */
  scopeState?: string;
}
/**
 * Durable nonterminal task state for an active task.
 */
export interface ActiveTask {
  /**
   * Stable processor task identifier.
   */
  taskId: string;
  /**
   * Reference to the task definition or task pattern.
   */
  taskRef: string;
  /**
   * Current nonterminal task status. Completed, failed, and skipped tasks leave activeTasks and remain in provenance.
   */
  status: 'created' | 'assigned' | 'claimed' | 'delegated' | 'escalated';
  /**
   * Actor assigned to complete the task.
   */
  assignedActor?: string;
  /**
   * Kernel contract map key used by this task.
   */
  contractRef?: string;
  /**
   * Contract binding type for this task when backed by a contract.
   */
  binding?: 'formspec' | 'jsonSchema';
  /**
   * Formspec Definition URL for Formspec-backed tasks.
   */
  definitionUrl?: string;
  /**
   * Pinned Formspec Definition version for Formspec-backed tasks.
   */
  definitionVersion?: string;
  /**
   * Mapping document used to prefill the task response.
   */
  prefillMappingRef?: string;
  /**
   * Mapping document used to project the completed task response into case state.
   */
  responseMappingRef?: string;
  /**
   * Task deadline.
   */
  deadline?: string;
  /**
   * Effective task impact level. Defaults to the Kernel impactLevel when absent.
   */
  impactLevel?: 'rights-impacting' | 'safety-impacting' | 'operational' | 'informational';
  context?: FormspecTaskContext;
  lastValidationOutcome?: ValidationOutcome;
  /**
   * ISO 8601 timestamp when the task was created.
   */
  createdAt: string;
  /**
   * ISO 8601 timestamp when the task state last changed.
   */
  updatedAt: string;
  /**
   * Extension data for this active task.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Presentation context for a Formspec-backed task.
 */
export interface FormspecTaskContext {
  /**
   * Processor task identifier. Stable for idempotency and provenance.
   */
  taskId: string;
  /**
   * WOS CaseInstance identifier.
   */
  instanceId: string;
  /**
   * Kernel contract map key used by the task.
   */
  contractRef: string;
  /**
   * Formspec Definition URL. Must match response.definitionUrl.
   */
  definitionUrl: string;
  /**
   * Pinned Formspec Definition version. Must match response.definitionVersion.
   */
  definitionVersion: string;
  /**
   * Task binding discriminator.
   */
  binding: 'formspec';
  /**
   * Actor assigned by the createTask action.
   */
  assignedActor: string;
  /**
   * Host-provided initial values for rendering.
   */
  prefillData?: {
    [k: string]: unknown;
  };
  /**
   * Mapping document used to prefill the Response.
   */
  prefillMappingRef?: string;
  /**
   * Mapping document used to project a completed Response into case state.
   */
  responseMappingRef?: string;
  /**
   * Task deadline.
   */
  deadline?: string;
  /**
   * Effective task impact level.
   */
  impactLevel?: 'rights-impacting' | 'safety-impacting' | 'operational' | 'informational';
  /**
   * Extension data for this task context.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Most recent Formspec task validation outcome, if validation has run.
 */
export interface ValidationOutcome {
  /**
   * Whether the Response envelope validated against Formspec response.schema.json.
   */
  envelopeValid: boolean;
  /**
   * Whether response.definitionUrl and response.definitionVersion matched the task pin.
   */
  pinMatch: boolean;
  /**
   * Whether Formspec Definition validation over response.data passed.
   */
  definitionValid: boolean;
  /**
   * WOS-level validation errors, including envelope and pin errors.
   */
  errors: {
    [k: string]: unknown;
  }[];
  /**
   * Formspec-shaped ValidationResult entries from Definition validation.
   */
  validationResults?: {
    [k: string]: unknown;
  }[];
}
/**
 * Records completed actions within a compensable scope for potential reverse-order compensation (Lifecycle Detail S5).
 */
export interface CompensationLog {
  /**
   * Identifier of the compensable scope this log belongs to.
   */
  scopeId: string;
  /**
   * Completed actions in forward completion order. On compensation, these are executed in reverse order (Lifecycle Detail S5.4).
   */
  entries: CompensationEntry[];
}
/**
 * A single entry in the compensation log -- one completed action with its compensating counterpart.
 */
export interface CompensationEntry {
  /**
   * Identifier of the original action that completed.
   */
  actionId: string;
  /**
   * Type of the original action (e.g., invokeService, setData).
   */
  actionType: string;
  /**
   * The compensating action to execute during backward recovery. Structure matches a Kernel Action (Kernel S9.2).
   */
  compensatingAction: {
    [k: string]: unknown;
  };
  /**
   * ISO 8601 timestamp when the original action completed.
   */
  completedAt: string;
  /**
   * Persisted output of the original action, available to the compensating action.
   */
  output?: {
    [k: string]: unknown;
  };
}
/**
 * An event enqueued for processing but not yet consumed by the evaluation engine.
 */
export interface PendingEvent {
  /**
   * Event name matching a transition's event property.
   */
  event: string;
  /**
   * Identifier of the actor who submitted this event.
   */
  actorId?: string;
  /**
   * Event payload, available in the evaluation context as 'event' (Kernel S7.2).
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * ISO 8601 timestamp of event submission.
   */
  timestamp: string;
  /**
   * Token for exactly-once delivery deduplication (Runtime Companion S4.3).
   */
  idempotencyToken?: string;
}
/**
 * Runtime state for governance enforcement. Present only when a Governance Document is attached to the workflow. Tracks delegation chains, active holds, and review protocol state.
 */
export interface GovernanceState {
  /**
   * Currently active delegation chains (Governance S11). Each entry records a delegation from one actor to another within a defined scope.
   */
  activeDelegations?: ActiveDelegation[];
  /**
   * Currently active holds (Governance S12). Each entry records a hold with its type, start time, and expected duration.
   */
  activeHolds?: ActiveHold[];
  /**
   * Runtime state for review protocols (Governance S4). Keyed by review protocol binding identifier. Tracks which reviews are pending, completed, and their outcomes.
   */
  reviewState?: {
    [k: string]: unknown;
  };
}
/**
 * A currently active delegation of authority from one actor to another.
 */
export interface ActiveDelegation {
  /**
   * Actor who delegated authority.
   */
  delegatorId: string;
  /**
   * Actor who received delegated authority.
   */
  delegateId: string;
  /**
   * Scope of the delegation (Governance S11.3). May be a transition tag, state identifier, or FEL expression.
   */
  scope: string;
  /**
   * Type of authority delegated (Governance S11.2).
   */
  authority?: 'signing' | 'determination' | 'review' | 'override';
  /**
   * ISO 8601 timestamp when the delegation was granted.
   */
  grantedAt: string;
  /**
   * ISO 8601 timestamp when the delegation expires. Absent if the delegation has no expiry.
   */
  expiresAt?: string;
}
/**
 * A currently active hold on the workflow instance.
 */
export interface ActiveHold {
  /**
   * Type of hold, matching a HoldPolicy's holdType (Governance S12).
   */
  holdType: string;
  /**
   * ISO 8601 timestamp when the hold began.
   */
  startedAt: string;
  /**
   * ISO 8601 timestamp when the hold is expected to end (startedAt + expectedDuration). Absent for indefinite holds.
   */
  expectedEnd?: string;
  /**
   * Event name that will resume the case from this hold.
   */
  resumeTrigger: string;
  /**
   * The lifecycle state the instance was in when the hold started.
   */
  holdState?: string;
}
/**
 * Counters for AI Integration volume constraints (AI Integration S11). Present only when an AI Integration Document is attached. Tracks autonomous actions per hour/day for autonomy cap enforcement.
 */
export interface VolumeCounters {
  /**
   * Per-agent hourly autonomous action counters. Keyed by agent actor ID.
   */
  hourly?: {
    [k: string]: VolumeCounter;
  };
  /**
   * Per-agent daily autonomous action counters. Keyed by agent actor ID.
   */
  daily?: {
    [k: string]: VolumeCounter;
  };
}
/**
 * A single volume counter tracking autonomous actions within a time window.
 */
export interface VolumeCounter {
  /**
   * Number of autonomous actions in the current window.
   */
  count: number;
  /**
   * ISO 8601 timestamp of the current counting window start.
   */
  windowStart: string;
}
