/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Optional JSON Schema URI enabling editor validation and autocompletion. When present, editors (VS Code, IntelliJ, etc.) validate the document against this schema. Omit in production documents; the authoritative schema URI is derived from the document type marker (e.g., '$wosKernel': '1.0'). Used for author-time tooling only — runtime processors MUST ignore this field.
 */
export type JsonSchemaUri = string;

/**
 * A WOS CaseInstance document per the WOS Runtime Companion v1.0. A CaseInstance is the serialization format for a running workflow instance -- it captures the complete runtime state needed to resume processing after a crash, migrate between processors, or audit past behavior. This is a runtime artifact, not a WOS document type: it has no $wos* marker because it is produced and consumed by processors, not authored by workflow designers. The instance shape is normatively defined so that instances can migrate between conformant processors without data loss.
 */
export interface WOSCaseInstance {
  $schema?: JsonSchemaUri;
  /**
   * TypeID-structured case identifier for this workflow instance. Stable for the lifetime of the instance — never reused or changed after creation. Used for routing events, correlating provenance records, and linking cross-case relationships (Runtime Companion S3.1). Processors assign this at createInstance time; authors do not choose it. Reserved family prefix: `case`.
   */
  instanceId: string;
  /**
   * Canonical URL of the Kernel Document governing this instance. Together with definitionVersion, identifies the exact document that controls this instance's lifecycle, case state schema, and contract bindings.
   */
  definitionUrl: string;
  /**
   * Version of the Kernel Document, pinned at instance creation (Kernel S9.6). Running instances remain on their creation-time version unless explicitly migrated (Runtime Companion S11).
   */
  definitionVersion: string;
  /**
   * Active leaf states as an ordered array. The order is deterministic: document order of state declarations within the kernel, depth-first. In a workflow without parallel states, this array contains exactly one element. In a workflow with parallel states, it contains one element per active region. Empty array only for completed or terminated instances.
   *
   * @minItems 0
   */
  configuration: string[];
  /**
   * Current case file field values. The keys are field names declared in the Kernel Document's caseFile.fields (Kernel S5.2). Values conform to the declared field types (Kernel S5.3). Mutated by setData actions and completed task response mappings. This is the authoritative business-data snapshot at the current point in processing.
   */
  caseState: {
    [k: string]: unknown;
  };
  /**
   * Index into the append-only provenance log. Indicates how many provenance records have been durably persisted for this instance. Used for crash recovery: on restart, the processor knows which provenance records are already durable.
   */
  provenancePosition: number;
  /**
   * Pending timer state. Empty array when no timers are active. After a processor restart, all timers in this array are reconstituted and scheduled for firing at their original deadlines (Runtime Companion S7.3).
   */
  timers: TimerState[];
  /**
   * Durable nonterminal task state. Empty array when no tasks are active. Terminal task history lives in provenance.
   */
  activeTasks: ActiveTask[];
  /**
   * Saved history state configurations, keyed by compound state identifier. Present only when the Kernel Document uses history states (Kernel S4.14, Lifecycle Detail S3). Each entry is the saved leaf-state configuration within that compound state.
   */
  historyStore?: {
    /**
     * Saved configuration for this compound state -- the states that were active when the compound state was last exited.
     */
    [k: string]: string[];
  };
  /**
   * Active compensation logs, keyed by compensable scope identifier. Present only when compensable scopes are active (Lifecycle Detail S5). Each log records completed actions that have declared compensatingActions, in forward completion order.
   */
  compensationLogs?: {
    [k: string]: CompensationLog;
  };
  /**
   * Instance status. 'active': processing events normally. 'suspended': paused, no events processed until resumed. 'migrating': definition version change in progress. 'completed': lifecycle reached a top-level final state. 'terminated': explicitly terminated. Completed and terminated are irreversible terminal states.
   */
  status: 'active' | 'suspended' | 'migrating' | 'completed' | 'terminated';
  /**
   * ISO 8601 timestamp when this instance was created by the processor (Runtime Companion S3.1). Immutable after creation — never updated on transitions or state changes.
   */
  createdAt: string;
  /**
   * ISO 8601 timestamp of last state change (transition fired, case state mutated, status changed).
   */
  updatedAt: string;
  /**
   * Events enqueued but not yet processed (Kernel S9.1 G5, Runtime Companion S12.8). FIFO order. Empty array when no events are pending. On processor restart, the processor resumes processing from the head of this queue.
   */
  pendingEvents?: PendingEvent[];
  governanceState?: GovernanceState;
  volumeCounters?: VolumeCounters;
  extensions?: ExtensionsMap;
  /**
   * This interface was referenced by `WOSCaseInstance`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * Captures the state of a pending durable timer.
 */
export interface TimerState {
  /**
   * Timer identifier, as declared in the startTimer action (Kernel S9.2).
   */
  timerId: string;
  /**
   * Absolute deadline when this timer fires (ISO 8601). If the original startTimer action used a relative duration, the processor converts it to an absolute deadline at creation time.
   */
  deadline: string;
  /**
   * Event to emit when the timer fires. Typically a $timeout.* kernel-generated event (Kernel S4.10).
   */
  event: string;
  /**
   * The state or region that scoped this timer. Used for cancellation on region exit (Lifecycle Detail S6.5) and timer reset on state reentry (Lifecycle Detail S6.4).
   */
  scopeState?: string;
  /**
   * This interface was referenced by `TimerState`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * Durable nonterminal task state for an active task.
 */
export interface ActiveTask {
  /**
   * Stable processor-assigned identifier for this task. Used for idempotent event routing, provenance correlation, and delegation references.
   */
  taskId: string;
  /**
   * Reference to the task definition, task pattern, or human-readable label identifying this task's type within the workflow.
   */
  taskRef: string;
  /**
   * Current nonterminal task status. Completed, failed, and skipped tasks leave activeTasks and remain in provenance.
   */
  status: 'created' | 'assigned' | 'claimed' | 'delegated' | 'escalated';
  /**
   * Identifier of the actor assigned to complete this task. Set by createTask; may change on delegation or escalation.
   */
  assignedActor?: string;
  /**
   * Key into the Kernel Document's contracts map identifying which contract governs this task (Kernel S7.2).
   */
  contractRef?: string;
  /**
   * Contract binding type for this task when backed by a contract. Drives which renderer the task delivery layer invokes.
   */
  binding?: 'formspec' | 'jsonSchema';
  /**
   * Formspec Definition URL for Formspec-backed tasks. Pinned at task creation; must match response.definitionUrl on submission.
   */
  definitionUrl?: string;
  /**
   * Pinned Formspec Definition version for Formspec-backed tasks. Must match response.definitionVersion on submission.
   */
  definitionVersion?: string;
  /**
   * URI of the Mapping document used to prefill the task form from current case state before rendering.
   */
  prefillMappingRef?: string;
  /**
   * URI of the Mapping document used to project a completed task Response back into case state on submission.
   */
  responseMappingRef?: string;
  /**
   * Absolute ISO 8601 deadline by which this task must be completed before SLA timers fire or escalation occurs.
   */
  deadline?: string;
  /**
   * Effective task impact level. Defaults to the Kernel impactLevel when absent.
   */
  impactLevel?: 'rights-impacting' | 'safety-impacting' | 'operational' | 'informational';
  context?: FormspecTaskContext;
  lastValidationOutcome?: ValidationOutcome;
  /**
   * ISO 8601 timestamp when this task was created by the processor's createTask action.
   */
  createdAt: string;
  /**
   * ISO 8601 timestamp when this task's state last changed (assignment, claim, escalation, or partial save).
   */
  updatedAt: string;
  extensions?: ExtensionsMap;
  /**
   * This interface was referenced by `ActiveTask`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * Presentation context for a Formspec-backed task.
 */
export interface FormspecTaskContext {
  /**
   * Processor-assigned task identifier. Stable for idempotency, provenance, and delegation lookups throughout the task lifecycle.
   */
  taskId: string;
  /**
   * Identifier of the WOS CaseInstance this task belongs to. Used by the form renderer to route task completion events back to the correct instance. Reserved family prefix: `case`.
   */
  instanceId: string;
  /**
   * Key into the Kernel Document's contracts map governing this task's form definition and response schema.
   */
  contractRef: string;
  /**
   * Formspec Definition URL. Pinned at task creation time; must match response.definitionUrl to pass envelope validation.
   */
  definitionUrl: string;
  /**
   * Pinned Formspec Definition version. Must match response.definitionVersion to pass envelope validation.
   */
  definitionVersion: string;
  /**
   * Task binding discriminator. Always 'formspec' in FormspecTaskContext — identifies this context shape as requiring Formspec rendering.
   */
  binding: 'formspec';
  /**
   * Actor assigned to complete this task, as set by the createTask action. The form renderer uses this to authorize task access.
   */
  assignedActor: string;
  /**
   * Host-provided initial field values pre-populated into the form before the actor sees it. Applied after prefillMappingRef if both are present.
   */
  prefillData?: {
    [k: string]: unknown;
  };
  /**
   * URI of the Mapping document used to derive prefill field values from current case state before rendering the form.
   */
  prefillMappingRef?: string;
  /**
   * URI of the Mapping document used to project a completed Formspec Response into case state on task completion.
   */
  responseMappingRef?: string;
  /**
   * Absolute ISO 8601 deadline by which this task must be completed before SLA timers fire or escalation occurs.
   */
  deadline?: string;
  /**
   * Effective task impact level. Drives UI warnings and access-control enforcement in the Formspec renderer.
   */
  impactLevel?: 'rights-impacting' | 'safety-impacting' | 'operational' | 'informational';
  extensions?: ExtensionsMap;
  /**
   * This interface was referenced by `FormspecTaskContext`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * Vendor extension data attached to this node. All keys MUST start with 'x-' (see Kernel §10.6). The reserved namespace 'x-wos-*' is for WOS Working Group use only; third-party extensions MUST use a unique vendor prefix (e.g., 'x-acme-', 'x-vendor-'). Processors MUST ignore unknown extension keys to preserve forward compatibility. Extension values are unconstrained — any JSON value is valid, but authors are encouraged to document the shape in their vendor spec.
 */
export interface ExtensionsMap {
  [k: string]: unknown;
}
/**
 * Most recent Formspec task validation outcome, if validation has run.
 */
export interface ValidationOutcome {
  /**
   * Whether the Response envelope validated against Formspec response.schema.json.
   */
  envelopeValid: boolean;
  /**
   * Whether response.definitionUrl and response.definitionVersion matched the task pin.
   */
  pinMatch: boolean;
  /**
   * Whether Formspec Definition validation over response.data passed.
   */
  definitionValid: boolean;
  /**
   * WOS-level validation errors, including envelope and pin errors.
   */
  errors: {
    [k: string]: unknown;
  }[];
  /**
   * Formspec-shaped ValidationResult entries from Definition validation.
   */
  validationResults?: {
    [k: string]: unknown;
  }[];
  /**
   * This interface was referenced by `ValidationOutcome`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * Records completed actions within a compensable scope for potential reverse-order compensation (Lifecycle Detail S5).
 */
export interface CompensationLog {
  /**
   * Identifier of the compensable scope this log belongs to. Matches a compensableScope state identifier in the Kernel Document (Lifecycle Detail S5).
   */
  scopeId: string;
  /**
   * Completed actions in forward completion order. On compensation, these are executed in reverse order (Lifecycle Detail S5.4).
   */
  entries: CompensationEntry[];
  /**
   * This interface was referenced by `CompensationLog`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * A single entry in the compensation log -- one completed action with its compensating counterpart.
 */
export interface CompensationEntry {
  /**
   * Identifier of the original Kernel action that completed and was recorded for potential compensation.
   */
  actionId: string;
  /**
   * Type of the original action that completed (e.g., invokeService, setData, createTask). Matches a Kernel action type (Kernel S9.2).
   */
  actionType: string;
  /**
   * The compensating action to execute during backward recovery in reverse entry order. Structure matches a Kernel Action (Kernel S9.2).
   */
  compensatingAction: {
    [k: string]: unknown;
  };
  /**
   * ISO 8601 timestamp when the original action completed and was logged for compensation purposes.
   */
  completedAt: string;
  /**
   * Persisted output of the original action, available to the compensating action.
   */
  output?: {
    [k: string]: unknown;
  };
  /**
   * This interface was referenced by `CompensationEntry`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * An event enqueued for processing but not yet consumed by the evaluation engine.
 */
export interface PendingEvent {
  /**
   * Event name matching a transition's event property in the Kernel Document. May also be a kernel-generated event like '$timeout.task' (Kernel S9.1).
   */
  event: string;
  /**
   * Identifier of the actor who submitted this event. Used for audit trails and role-based transition guards.
   */
  actorId?: string;
  /**
   * Arbitrary event payload, available in guard expression evaluation context as 'event' (Kernel S7.2). Structure is workflow-specific.
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * ISO 8601 timestamp when this event was enqueued by the actor or system component.
   */
  timestamp: string;
  /**
   * Opaque token for exactly-once delivery deduplication (Runtime Companion S4.3). The processor rejects duplicate events with the same token.
   */
  idempotencyToken?: string;
  /**
   * This interface was referenced by `PendingEvent`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * Runtime state for governance enforcement. Present only when a Governance Document is attached to the workflow. Tracks delegation chains, active holds, and review protocol state.
 */
export interface GovernanceState {
  /**
   * Currently active delegation chains (Governance S11). Each entry records a delegation from one actor to another within a defined scope.
   */
  activeDelegations?: ActiveDelegation[];
  /**
   * Currently active holds (Governance S12). Each entry records a hold with its type, start time, and expected duration.
   */
  activeHolds?: ActiveHold[];
  /**
   * Runtime state for review protocols (Governance S4). Keyed by review protocol binding identifier. Tracks which reviews are pending, completed, and their outcomes.
   */
  reviewState?: {
    [k: string]: unknown;
  };
  /**
   * This interface was referenced by `GovernanceState`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * A currently active delegation of authority from one actor to another.
 */
export interface ActiveDelegation {
  /**
   * Identifier of the actor who granted this delegation. Must be an actor with the relevant authority at the time of granting.
   */
  delegatorId: string;
  /**
   * Identifier of the actor who received the delegated authority. This actor may act on behalf of the delegator within the declared scope.
   */
  delegateId: string;
  /**
   * Scope of the delegation (Governance S11.3). May be a transition tag, state identifier, or FEL expression.
   */
  scope: string;
  /**
   * Type of authority delegated (Governance S11.2). Determines which governed transitions the delegate may trigger.
   */
  authority?: 'signing' | 'determination' | 'review' | 'override';
  /**
   * ISO 8601 timestamp when this delegation was recorded by the governance system.
   */
  grantedAt: string;
  /**
   * ISO 8601 timestamp when the delegation expires. Absent if the delegation has no expiry.
   */
  expiresAt?: string;
  /**
   * This interface was referenced by `ActiveDelegation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * A currently active hold on the workflow instance.
 */
export interface ActiveHold {
  /**
   * Type of hold, matching a HoldPolicy's holdType (Governance S12).
   */
  holdType: string;
  /**
   * ISO 8601 timestamp when this hold was placed on the instance by the governance system.
   */
  startedAt: string;
  /**
   * ISO 8601 timestamp when the hold is expected to end (startedAt + expectedDuration). Absent for indefinite holds.
   */
  expectedEnd?: string;
  /**
   * Event name that, when received, will lift this hold and allow the instance to resume normal processing.
   */
  resumeTrigger: string;
  /**
   * The lifecycle state the instance was in when the hold started. Stored to verify state has not changed on hold removal.
   */
  holdState?: string;
  /**
   * This interface was referenced by `ActiveHold`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * Counters for AI Integration volume constraints (AI Integration S11). Present only when an AI Integration Document is attached. Tracks autonomous actions per hour/day for autonomy cap enforcement.
 */
export interface VolumeCounters {
  /**
   * Per-agent hourly autonomous action counters. Keyed by agent actor ID.
   */
  hourly?: {
    [k: string]: VolumeCounter;
  };
  /**
   * Per-agent daily autonomous action counters. Keyed by agent actor ID.
   */
  daily?: {
    [k: string]: VolumeCounter;
  };
  /**
   * This interface was referenced by `VolumeCounters`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * A single volume counter tracking autonomous actions within a time window.
 */
export interface VolumeCounter {
  /**
   * Number of autonomous actions taken by this agent in the current counting window. Compared to the cap declared in the AI Integration Document.
   */
  count: number;
  /**
   * ISO 8601 timestamp marking the start of the current counting window. Resets each hour (hourly) or each UTC midnight (daily).
   */
  windowStart: string;
  /**
   * This interface was referenced by `VolumeCounter`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
