/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Correspondence Metadata Config sidecar document. Declares the metadata schema for correspondence entries stored in case state. Government workflows track correspondence (letters, phone calls, emails, portal submissions, in-person interactions) as part of the case record. The kernel's existing event mechanism handles correspondence events -- events that match no transition are recorded in provenance (Kernel S4.9). This sidecar defines structured metadata for consistent cataloging and retrieval without adding new event types or modifying lifecycle semantics.
 */
export interface WOSCorrespondenceMetadataConfig {
  /**
   * WOS Correspondence Metadata Config specification version. MUST be '1.0'.
   */
  $wosCorrespondenceMetadata: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this correspondence config applies to.
   */
  targetWorkflow: string;
  /**
   * Version of this Correspondence Metadata Config document.
   */
  version?: string;
  /**
   * Human-readable name for this correspondence configuration.
   */
  title?: string;
  /**
   * Human-readable description of this correspondence configuration.
   */
  description?: string;
  /**
   * Case state field path where correspondence entries are stored. The workflow stores an array of correspondence entry objects at this path.
   */
  correspondenceField: string;
  /**
   * Templates defining the metadata structure for correspondence entries. Each template declares the channel, direction, actor type, and required fields for a category of correspondence.
   *
   * @minItems 1
   */
  entryTemplates: [EntryTemplate, ...EntryTemplate[]];
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface EntryTemplate {
  /**
   * Unique template identifier. Referenced by correspondence entries via templateRef.
   */
  id: string;
  /**
   * Human-readable description of when this template applies.
   */
  description?: string;
  /**
   * Communication channel. 'in-person': face-to-face contact. 'phone': telephone call. 'mail': physical mail. 'email': electronic mail. 'portal': web portal submission or message. 'fax': facsimile transmission. Extensible via x- prefixed values in the extensions property.
   */
  channel: 'in-person' | 'phone' | 'mail' | 'email' | 'portal' | 'fax';
  /**
   * Direction of the correspondence. 'inbound': received by the agency. 'outbound': sent by the agency.
   */
  direction: 'inbound' | 'outbound';
  /**
   * Who sent or received the correspondence. 'applicant': the primary case subject. 'representative': authorized representative acting on behalf of the applicant. 'third-party': external party (e.g., employer, medical provider). 'system': automated system-generated correspondence. 'agency': agency staff.
   */
  actorType: 'applicant' | 'representative' | 'third-party' | 'system' | 'agency';
  /**
   * Fields that MUST be present in a correspondence entry using this template, beyond the base metadata (templateRef, channel, direction, actorType, contentRef, summary, timestamp).
   */
  requiredFields?: string[];
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
