/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Optional JSON Schema URI enabling editor validation and autocompletion. When present, editors (VS Code, IntelliJ, etc.) validate the document against this schema. Omit in production documents; the authoritative schema URI is derived from the document type marker (e.g., '$wosKernel': '1.0'). Used for author-time tooling only — runtime processors MUST ignore this field.
 */
export type JsonSchemaUri = string;

/**
 * A WOS Correspondence Metadata Config sidecar document. Declares the metadata schema for correspondence entries stored in case state. Government workflows track correspondence (letters, phone calls, emails, portal submissions, in-person interactions) as part of the case record. The kernel's existing event mechanism handles correspondence events -- events that match no transition are recorded in provenance (Kernel S4.9). This sidecar defines structured metadata for consistent cataloging and retrieval without adding new event types or modifying lifecycle semantics.
 */
export interface WOSCorrespondenceMetadataConfig {
  /**
   * WOS Correspondence Metadata Config specification version marker. MUST be exactly '1.0'. Processors use this field to detect the document type and select the appropriate schema version for validation. Omitting or misspelling this marker causes the document to be rejected as an unrecognized document type.
   */
  $wosCorrespondenceMetadata: '1.0';
  $schema?: JsonSchemaUri;
  /**
   * Absolute URI of the WOS Kernel Document this correspondence configuration applies to. Processors use this field to bind the sidecar to its parent workflow and validate that correspondence entries are recorded against the correct case type. MUST be an absolute URI matching the '$id' of the target kernel document.
   */
  targetWorkflow: string;
  /**
   * Semver version string for this Correspondence Metadata Config document, used for change tracking and compatibility checks.
   */
  version?: string;
  /**
   * Human-readable display name for this correspondence configuration document, shown in tooling and audit reports.
   */
  title?: string;
  /**
   * Human-readable summary explaining what kinds of correspondence this configuration covers and which workflow it supports.
   */
  description?: string;
  /**
   * Dot-separated case state field path where correspondence entries are stored as an array. The workflow processor appends correspondence entry objects to this path when correspondence events are recorded in provenance. MUST refer to an array-typed field in the case state.
   */
  correspondenceField: string;
  /**
   * Templates defining the metadata structure for correspondence entries. Each template declares the channel, direction, actor type, and required fields for a category of correspondence.
   *
   * @minItems 1
   */
  entryTemplates: [EntryTemplate, ...EntryTemplate[]];
  extensions?: ExtensionsMap;
  /**
   * This interface was referenced by `WOSCorrespondenceMetadataConfig`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
export interface EntryTemplate {
  /**
   * Unique template identifier. Referenced by correspondence entries via templateRef.
   */
  id: string;
  /**
   * Human-readable description of the correspondence category this template covers, used in tooling and audit summaries.
   */
  description?: string;
  /**
   * Communication channel. 'in-person': face-to-face contact. 'phone': telephone call. 'mail': physical mail. 'email': electronic mail. 'portal': web portal submission or message. 'fax': facsimile transmission. Extensible via x- prefixed values in the extensions property.
   */
  channel: 'in-person' | 'phone' | 'mail' | 'email' | 'portal' | 'fax';
  /**
   * Direction of the correspondence. 'inbound': received by the agency. 'outbound': sent by the agency.
   */
  direction: 'inbound' | 'outbound';
  /**
   * Who sent or received the correspondence. 'applicant': the primary case subject. 'representative': authorized representative acting on behalf of the applicant. 'third-party': external party (e.g., employer, medical provider). 'system': automated system-generated correspondence. 'agency': agency staff.
   */
  actorType: 'applicant' | 'representative' | 'third-party' | 'system' | 'agency';
  /**
   * Fields that MUST be present in a correspondence entry using this template, beyond the base metadata (templateRef, channel, direction, actorType, contentRef, summary, timestamp).
   */
  requiredFields?: string[];
  extensions?: ExtensionsMap;
  /**
   * This interface was referenced by `EntryTemplate`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: {
    [k: string]: unknown;
  };
}
/**
 * Vendor extension data attached to this node. All keys MUST start with 'x-' (see Kernel §10.6). The reserved namespace 'x-wos-*' is for WOS Working Group use only; third-party extensions MUST use a unique vendor prefix (e.g., 'x-acme-', 'x-vendor-'). Processors MUST ignore unknown extension keys to preserve forward compatibility. Extension values are unconstrained — any JSON value is valid, but authors are encouraged to document the shape in their vendor spec.
 */
export interface ExtensionsMap {
  [k: string]: unknown;
}
