/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Drift Monitor Config sidecar document. Provides drift detection and monitoring configuration for agents in a WOS workflow -- drift detection methods, evaluation windows, alert thresholds, rubber-stamp detection, and deployment sequence policies. Monitoring parameters can be tuned independently of the governance document.
 */
export interface WOSDriftMonitorConfig {
  /**
   * WOS Drift Monitor Config specification version. MUST be '1.0'.
   */
  $wosDriftMonitor: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this monitor applies to.
   */
  targetWorkflow: string;
  /**
   * Version of this Drift Monitor Config document.
   */
  version?: string;
  /**
   * Human-readable name for this drift monitor configuration.
   */
  title?: string;
  /**
   * Per-agent monitoring configurations.
   *
   * @minItems 1
   */
  monitors: [AgentMonitor, ...AgentMonitor[]];
  deploymentSequence?: DeploymentSequence;
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface AgentMonitor {
  /**
   * Agent identifier to monitor.
   */
  agentRef: string;
  /**
   * ISO 8601 duration of the evaluation window.
   */
  evaluationWindow: string;
  /**
   * Metrics to track for this agent.
   *
   * @minItems 1
   */
  metrics: [MonitorMetric, ...MonitorMetric[]];
  rubberStamp?: RubberStampConfig;
  /**
   * Conditions that generate alerts or trigger automatic governance actions.
   */
  alertThresholds?: AlertThreshold[];
}
export interface MonitorMetric {
  /**
   * Metric name.
   */
  name: string;
  /**
   * Statistical method for drift detection. 'psi': Population Stability Index. 'ks': Kolmogorov-Smirnov test. 'chi2': Chi-squared test. 'accuracy': accuracy against human-reviewed ground truth. 'custom': implementation-defined method.
   */
  method?: 'psi' | 'ks' | 'chi2' | 'accuracy' | 'custom';
  /**
   * Threshold value for drift detection. Semantics depend on the method.
   */
  threshold?: number;
}
/**
 * Rubber-stamp detection for human reviewers of this agent's output.
 */
export interface RubberStampConfig {
  /**
   * Whether rubber-stamp detection is active.
   */
  enabled?: boolean;
  /**
   * ISO 8601 duration below which a review is flagged as potentially rubber-stamped.
   */
  minReviewTime?: string;
  /**
   * Agreement rate above which reviewer engagement is flagged.
   */
  maxAgreementRate?: number;
  /**
   * ISO 8601 duration of the evaluation window for rubber-stamp metrics.
   */
  evaluationWindow?: string;
}
export interface AlertThreshold {
  /**
   * FEL expression or metric condition that triggers the alert.
   */
  condition: string;
  /**
   * Alert severity level.
   */
  severity: 'info' | 'warning' | 'critical';
  /**
   * Automatic governance action to take when threshold is crossed. 'notify': alert administrators. 'demoteToAssistive': cap autonomy at assistive. 'demoteToManual': cap autonomy at manual. 'suspend': suspend agent invocations.
   */
  action?: 'notify' | 'demoteToAssistive' | 'demoteToManual' | 'suspend';
  /**
   * Roles to notify when this threshold is crossed.
   */
  notifyRoles?: string[];
}
/**
 * Shadow/canary/production deployment sequence policy. RECOMMENDED for rights-impacting and safety-impacting workflows.
 */
export interface DeploymentSequence {
  /**
   * Whether the shadow/canary/production deployment sequence is enforced.
   */
  enabled?: boolean;
  /**
   * ISO 8601 duration of the shadow phase.
   */
  shadowDuration?: string;
  /**
   * Fraction of invocations routed to the canary version.
   */
  canaryPercentage?: number;
  /**
   * ISO 8601 duration of the canary phase.
   */
  canaryDuration?: string;
  /**
   * Elevated review sampling rate during the canary phase.
   */
  canaryReviewSamplingRate?: number;
}
