/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Due Process Config sidecar document. Provides detailed due process configuration -- notice templates, explanation templates, appeal routing, continuation-of-service policies -- for a WOS Workflow Governance Document. Operational parameters can be updated independently of the governance structure.
 */
export interface WOSDueProcessConfig {
  /**
   * WOS Due Process Config specification version. MUST be '1.0'.
   */
  $wosDueProcess: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * URI of the WOS Workflow Governance Document this config targets.
   */
  targetGovernance: string;
  /**
   * Version of this Due Process Config document.
   */
  version?: string;
  /**
   * Templates for adverse decision notices.
   */
  noticeTemplates?: NoticeTemplate[];
  /**
   * Templates for decision explanations at various levels.
   */
  explanationTemplates?: ExplanationTemplate[];
  appealRouting?: AppealRouting;
  /**
   * Continuation-of-service policies for different adverse decision types.
   */
  continuationPolicies?: ContinuationPolicy[];
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface NoticeTemplate {
  /**
   * Unique template identifier.
   */
  id: string;
  /**
   * Notice title displayed to the recipient.
   */
  title: string;
  /**
   * Required sections in the notice.
   */
  sections: string[];
  /**
   * Optional reference to a Formspec Definition for structured notice rendering.
   */
  formspecDefinitionRef?: string;
  /**
   * Human-readable description of when this template is used.
   */
  description?: string;
}
export interface ExplanationTemplate {
  /**
   * Unique template identifier.
   */
  id: string;
  /**
   * Explanation level this template serves.
   */
  level: 'individualized' | 'categorical' | 'aggregate';
  /**
   * Required elements in the explanation.
   */
  requiredElements?: string[];
  /**
   * Human-readable description of this template.
   */
  description?: string;
}
/**
 * Detailed appeal routing configuration.
 */
export interface AppealRouting {
  /**
   * Default pool of eligible appeal reviewers.
   */
  defaultReviewerPool?: string;
  /**
   * How independence from the original determination is ensured.
   */
  independenceConstraint: string;
  /**
   * Ordered escalation path for contested appeal reviews.
   */
  escalationPath?: string[];
}
export interface ContinuationPolicy {
  /**
   * Type of adverse decision this policy applies to.
   */
  decisionType: string;
  /**
   * Scope of service continuation.
   */
  scope: string;
  /**
   * ISO 8601 duration of the continuation period.
   */
  duration?: string;
  /**
   * Human-readable description of this continuation policy.
   */
  description?: string;
}
