/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Equity Config sidecar document. Provides detailed equity monitoring configuration -- protected category definitions, disparity calculation methods, reporting schedules, remediation triggers. Equity monitoring applies to human AND AI decisions.
 */
export interface WOSEquityConfig {
  /**
   * WOS Equity Config specification version. MUST be '1.0'.
   */
  $wosEquityConfig: '1.0';
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this config targets. Follows the same targetWorkflow binding pattern as Layer 1 and Layer 2 sidecars.
   */
  targetWorkflow: string;
  version?: string;
  title?: string;
  /**
   * Demographic or categorical groupings for equity monitoring.
   */
  protectedCategories?: ProtectedCategory[];
  /**
   * Statistical methods for computing disparity.
   */
  disparityMethods?: DisparityMethod[];
  reportingSchedule?: ReportingSchedule;
  /**
   * Conditions that trigger structured remediation review.
   */
  remediationTriggers?: RemediationTrigger[];
  extensions?: {
    [k: string]: unknown;
  };
}
export interface ProtectedCategory {
  id: string;
  /**
   * Case file path for grouping.
   */
  groupByPath: string;
  description?: string;
  /**
   * Expected group values for validation.
   */
  groups?: string[];
}
export interface DisparityMethod {
  id: string;
  /**
   * Statistical method for disparity calculation.
   */
  method: 'rateDifference' | 'rateRatio' | 'standardizedDifference' | 'chi2';
  description?: string;
}
/**
 * Automated equity reporting configuration.
 */
export interface ReportingSchedule {
  /**
   * ISO 8601 duration.
   */
  frequency?: string;
  recipientRoles?: string[];
  includeHistoricalTrend?: boolean;
}
export interface RemediationTrigger {
  /**
   * Condition expression.
   */
  condition: string;
  /**
   * Action to take.
   */
  action: 'review' | 'audit' | 'suspend' | 'notify';
  notifyRoles?: string[];
  description?: string;
}
