/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type State = {
  [k: string]: unknown;
} & {
  /**
   * State type (Kernel S4.3). 'atomic': no substates. 'compound': contains substates with initialState. 'parallel': contains concurrent regions. 'final': completion indicator, no outgoing transitions.
   */
  type: 'atomic' | 'compound' | 'parallel' | 'final';
  /**
   * Actions executed when this state is entered.
   */
  onEntry?: Action[];
  /**
   * Actions executed when this state is exited.
   */
  onExit?: Action[];
  /**
   * Outgoing transitions from this state. Evaluated in document order -- first matching guard wins (Kernel S4.6).
   */
  transitions?: Transition[];
  /**
   * Semantic tags for governance attachment via lifecycleHook (Kernel S4.12). Conventional tags: determination, review, adverse-decision, quality-check, intake, appeal, notification, hold.
   */
  tags?: string[];
  /**
   * Initial substate identifier. REQUIRED when type = 'compound'. MUST NOT appear on atomic, parallel, or final states. Enforced structurally by the allOf block on this State (Kernel S4.3).
   */
  initialState?: string;
  /**
   * Substates within a compound state. REQUIRED (non-empty) when type = 'compound'. MUST NOT appear on atomic, parallel, or final states. Enforced structurally by the allOf block on this State (Kernel S4.3).
   */
  states?: {
    [k: string]: State;
  };
  /**
   * Named concurrent regions within a parallel state. REQUIRED (non-empty) when type = 'parallel'. MUST NOT appear on atomic, compound, or final states. Enforced structurally by the allOf block on this State (Kernel S4.3, S4.4).
   */
  regions?: {
    [k: string]: Region;
  };
  /**
   * Cancellation policy for parallel states (Kernel S4.4). 'wait-all': exit when all regions reach final state (default). 'cancel-siblings': exit when any region reaches final, cancel others. 'fail-fast': exit immediately on any error final state. Only permitted when type = 'parallel'; enforced structurally by the allOf block on this State.
   */
  cancellationPolicy?: 'wait-all' | 'cancel-siblings' | 'fail-fast';
  /**
   * History state mode for compound states (Kernel S4.14). When present, overrides initialState on reentry: 'shallow' resumes the last active direct substate, 'deep' restores the full nested configuration. Semantics defined in the Lifecycle Detail Companion (S3). Only permitted when type = 'compound'; enforced structurally by the allOf block on this State.
   */
  historyState?: 'shallow' | 'deep';
  /**
   * Human-readable description of this state.
   */
  description?: string;
  /**
   * Extension data for this state.
   */
  extensions?: {
    [k: string]: unknown;
  };
};

/**
 * A WOS Kernel Document per the Workflow Orchestration Standard (WOS) Kernel Specification v1.0. The kernel is the minimal orchestration substrate: it defines lifecycle topology (states, transitions, events, milestones), case state (typed data with append-only mutation history), actor model (human and system, extensible via actorExtension seam), impact level classification, contract validation interface, provenance Facts tier, durable execution guarantees, and five named extension seams. The kernel is self-sufficient -- a kernel-only deployment orchestrates workflows without requiring any governance layer. WOS is a companion framework to Formspec v1.0 that MUST NOT alter core Formspec processing semantics.
 */
export interface WOSKernelDocument {
  /**
   * WOS Kernel specification version. MUST be '1.0'. Identifies this document as a WOS Kernel Document and pins the specification version.
   */
  $wosKernel: '1.0';
  /**
   * Optional JSON Schema URI for editor validation and autocompletion.
   */
  $schema?: string;
  /**
   * Canonical URI identifier for this Kernel Document. Stable across versions -- the pair (url, version) SHOULD be globally unique.
   */
  url?: string;
  /**
   * Version of this Kernel Document. SemVer is RECOMMENDED.
   */
  version?: string;
  /**
   * Human-readable name for this workflow.
   */
  title?: string;
  /**
   * Human-readable description of the workflow's purpose and scope.
   */
  description?: string;
  /**
   * Workflow lifecycle state. Transitions: draft -> active -> retired.
   */
  status?: 'draft' | 'active' | 'retired';
  /**
   * Consequence level classification for decisions made within this workflow (Kernel S6). 'rights-impacting': decisions affect individual legal rights -- full due process required (Layer 1). 'safety-impacting': decisions affect safety -- full due process required. 'operational': organizational operations -- due process RECOMMENDED. 'informational': no binding decisions -- due process OPTIONAL. Default: 'operational'.
   */
  impactLevel?: 'rights-impacting' | 'safety-impacting' | 'operational' | 'informational';
  /**
   * Declarations of actors participating in this workflow (Kernel S3). The kernel defines human and system actor types. Additional types are registered via the actorExtension seam.
   */
  actors?: ActorDeclaration[];
  lifecycle: Lifecycle;
  caseFile?: CaseFile;
  /**
   * Named contract references for typed data exchanges (Kernel S11). Maps contract names to contract references. Two bindings: Formspec (recommended) and JSON Schema (baseline).
   */
  contracts?: {
    [k: string]: ContractReference;
  };
  provenance?: ProvenanceConfig;
  execution?: ExecutionConfig;
  /**
   * Determines when the processor evaluates transition guards (Runtime Companion S10). 'event-driven' (default): guards are evaluated only when an explicit event arrives. 'continuous': after any case state mutation, the processor re-evaluates all guards in the current configuration -- if any guard that was previously false now evaluates to true, the corresponding transition fires. Continuous mode imposes a convergence cap of 100 re-evaluation cycles per triggering mutation.
   */
  evaluationMode?: 'event-driven' | 'continuous';
  /**
   * Maximum cascade depth for relationship-triggered events ($related.*) before the processor halts generation (Kernel S4.10). Prevents unbounded cascading in cyclically related cases. Default: 3.
   */
  maxRelationshipEventDepth?: number;
  /**
   * Custody posture declaration seam (S10.5). Opaque to the kernel; bindings populate this with declared posture semantics. A monolithic binding may declare a single posture; a distributed binding may declare a full Trust Profile object.
   */
  custodyHook?: {
    [k: string]: unknown;
  };
  /**
   * Extension data. All keys MUST be prefixed with 'x-'. The standard extensibility mechanism for implementation-specific or experimental features (Kernel S10.6).
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface ActorDeclaration {
  /**
   * Unique identifier for this actor declaration within the workflow.
   */
  id: string;
  /**
   * Actor type (Kernel S3). 'human': a person who performs tasks and exercises judgment -- provenance requires identity, role, timestamp. 'system': a deterministic software component -- provenance requires component identifier, version, timestamp. Additional types registered via actorExtension seam.
   */
  type: 'human' | 'system';
  /**
   * Human-readable description of this actor's role in the workflow.
   */
  description?: string;
  /**
   * Extension data for this actor declaration.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Lifecycle topology defining states, transitions, events, and milestones (Kernel S4). The lifecycle is a deterministic pure function: (current states x event x guards -> next states).
 */
export interface Lifecycle {
  /**
   * Identifier of the initial state. Execution begins here when a workflow instance is created.
   */
  initialState: string;
  /**
   * Map of state identifiers to state definitions. At least two states (initial and one final) are needed for a meaningful workflow.
   */
  states: {
    [k: string]: State;
  };
  /**
   * Named conditions on case state that indicate meaningful progress (Kernel S4.13). Milestones are observable but do not affect lifecycle state.
   */
  milestones?: {
    [k: string]: Milestone;
  };
}
export interface Action {
  /**
   * Action type (Kernel S9.2).
   */
  action: 'createTask' | 'invokeService' | 'setData' | 'emitEvent' | 'startTimer' | 'cancelTimer' | 'log';
  /**
   * Reference to a task definition. Used with createTask.
   */
  taskRef?: string;
  /**
   * Actor identifier to assign the task to. Used with createTask.
   */
  assignTo?: string;
  /**
   * Reference to an external service. Used with invokeService.
   */
  serviceRef?: string;
  /**
   * Idempotency key for deduplicating service invocations (Kernel S9.3). Closes the crash-between-invoke-and-persist window.
   */
  idempotencyKey?: string;
  /**
   * Correlation key for routing external callbacks to the correct workflow instance (Kernel S9.4).
   */
  correlationKey?: string;
  /**
   * Case file field path. Used with setData.
   */
  path?: string;
  /**
   * Value to set. Used with setData. May be a literal or FEL expression string.
   */
  value?: {
    [k: string]: unknown;
  };
  /**
   * Event type identifier. Used with emitEvent.
   */
  eventType?: string;
  /**
   * Event data payload. Used with emitEvent.
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * Timer identifier. Used with startTimer and cancelTimer.
   */
  timerId?: string;
  /**
   * ISO 8601 duration. Used with startTimer.
   */
  duration?: string;
  /**
   * ISO 8601 datetime deadline. Used with startTimer and createTask.
   */
  deadline?: string;
  /**
   * Event to emit when timer fires. Used with startTimer.
   */
  event?: string;
  /**
   * Log message. Used with log.
   */
  message?: string;
  /**
   * Human-readable description of what this action does.
   */
  description?: string;
  compensatingAction?: Action1;
  /**
   * Reference to a contract in the contracts map for validation or Formspec-backed task presentation.
   */
  contractRef?: string;
  /**
   * Mapping document used to prefill a Formspec-backed task response. Used with createTask; overrides the ContractReference value for this task.
   */
  prefillMappingRef?: string;
  /**
   * Mapping document used to project a completed Formspec Response into case state. Used with createTask; overrides the ContractReference value for this task.
   */
  responseMappingRef?: string;
  /**
   * Event emitted when a Formspec-backed task completes successfully.
   */
  completionEvent?: string;
  /**
   * Event emitted when a Formspec-backed task fails validation, ledger gating, abandonment, or post-pass checks.
   */
  failureEvent?: string;
  /**
   * Extension data for this action.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Semantically meaningful reversal action (Kernel S9.5). The compensation seam only -- detailed execution semantics deferred to Lifecycle Detail companion.
 */
export interface Action1 {
  /**
   * Action type (Kernel S9.2).
   */
  action: 'createTask' | 'invokeService' | 'setData' | 'emitEvent' | 'startTimer' | 'cancelTimer' | 'log';
  /**
   * Reference to a task definition. Used with createTask.
   */
  taskRef?: string;
  /**
   * Actor identifier to assign the task to. Used with createTask.
   */
  assignTo?: string;
  /**
   * Reference to an external service. Used with invokeService.
   */
  serviceRef?: string;
  /**
   * Idempotency key for deduplicating service invocations (Kernel S9.3). Closes the crash-between-invoke-and-persist window.
   */
  idempotencyKey?: string;
  /**
   * Correlation key for routing external callbacks to the correct workflow instance (Kernel S9.4).
   */
  correlationKey?: string;
  /**
   * Case file field path. Used with setData.
   */
  path?: string;
  /**
   * Value to set. Used with setData. May be a literal or FEL expression string.
   */
  value?: {
    [k: string]: unknown;
  };
  /**
   * Event type identifier. Used with emitEvent.
   */
  eventType?: string;
  /**
   * Event data payload. Used with emitEvent.
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * Timer identifier. Used with startTimer and cancelTimer.
   */
  timerId?: string;
  /**
   * ISO 8601 duration. Used with startTimer.
   */
  duration?: string;
  /**
   * ISO 8601 datetime deadline. Used with startTimer and createTask.
   */
  deadline?: string;
  /**
   * Event to emit when timer fires. Used with startTimer.
   */
  event?: string;
  /**
   * Log message. Used with log.
   */
  message?: string;
  /**
   * Human-readable description of what this action does.
   */
  description?: string;
  compensatingAction?: Action1;
  /**
   * Reference to a contract in the contracts map for validation or Formspec-backed task presentation.
   */
  contractRef?: string;
  /**
   * Mapping document used to prefill a Formspec-backed task response. Used with createTask; overrides the ContractReference value for this task.
   */
  prefillMappingRef?: string;
  /**
   * Mapping document used to project a completed Formspec Response into case state. Used with createTask; overrides the ContractReference value for this task.
   */
  responseMappingRef?: string;
  /**
   * Event emitted when a Formspec-backed task completes successfully.
   */
  completionEvent?: string;
  /**
   * Event emitted when a Formspec-backed task fails validation, ledger gating, abandonment, or post-pass checks.
   */
  failureEvent?: string;
  /**
   * Extension data for this action.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface Transition {
  /**
   * Triggering event identifier.
   */
  event: string;
  /**
   * Target state identifier.
   */
  target: string;
  /**
   * FEL expression that must evaluate to true for the transition to fire. Evaluated in the evaluation context (Kernel S7).
   */
  guard?: string;
  /**
   * Actions executed during the transition, after source onExit and before target onEntry.
   */
  actions?: Action[];
  /**
   * Semantic tags for governance attachment via lifecycleHook (Kernel S4.12).
   */
  tags?: string[];
  /**
   * Human-readable explanation of this transition.
   */
  description?: string;
}
export interface Region {
  /**
   * Initial state identifier for this parallel region.
   */
  initialState: string;
  /**
   * States within this parallel region.
   */
  states: {
    [k: string]: State;
  };
}
export interface Milestone {
  /**
   * FEL expression evaluated against case state. When true, the milestone is reached.
   */
  condition: string;
  /**
   * Human-readable description of what this milestone represents.
   */
  description?: string;
}
/**
 * Typed data schema for the case state (Kernel S5). Case state is an append-only log independent of lifecycle state.
 */
export interface CaseFile {
  /**
   * Named fields with type declarations. Each field defines a typed data slot in the case state.
   */
  fields: {
    [k: string]: FieldDefinition;
  };
  /**
   * Typed relationships to other case instances (Kernel S5.5). Relationships are metadata -- they do NOT affect lifecycle evaluation. Cross-case behavioral interaction uses correlationKey (Kernel S9.4).
   */
  relationships?: CaseRelationship[];
}
export interface FieldDefinition {
  /**
   * Data type of this field.
   */
  type: 'string' | 'number' | 'integer' | 'boolean' | 'date' | 'datetime' | 'object' | 'array';
  /**
   * Human-readable description of this field.
   */
  description?: string;
  /**
   * Default value for this field.
   */
  default?: {
    [k: string]: unknown;
  };
}
export interface CaseRelationship {
  /**
   * Relationship type. Standard values: parent, child, sibling, related, supersedes. Extensible via x- prefixed values.
   */
  type: string;
  /**
   * URI reference to the related case instance.
   */
  targetCase: string;
  /**
   * Semantic label describing the relationship.
   */
  relationship?: string;
  /**
   * When true, the target case SHOULD also record the inverse relationship.
   */
  bidirectional?: boolean;
}
export interface ContractReference {
  /**
   * Contract binding type (Kernel S11.2). 'formspec': Formspec Definition (recommended) -- full reactive behavior, cross-field Shapes, Mapping DSL. 'jsonSchema': JSON Schema (baseline) -- structural validation only.
   */
  binding: 'formspec' | 'jsonSchema';
  /**
   * URI reference to the contract document (Formspec Definition or JSON Schema).
   */
  ref: string;
  /**
   * Human-readable description of this contract's purpose.
   */
  description?: string;
  /**
   * Mapping document used to prefill Formspec-backed tasks that use this contract. Prefer the same bidirectional Mapping document as responseMappingRef when the host supports Mapping Bidirectional.
   */
  prefillMappingRef?: string;
  /**
   * Mapping document used to project completed Formspec Responses into WOS case state. If absent, Runtime Companion S15 forbids automatic host-defined Response-to-case projection.
   */
  responseMappingRef?: string;
}
/**
 * Provenance configuration for the Facts tier (Kernel S8).
 */
export interface ProvenanceConfig {
  /**
   * Cryptographic digest algorithm for input/output tamper detection (Kernel S8.3). Implementation-defined but recorded here for auditability.
   */
  digestAlgorithm?: string;
  /**
   * Extension data for provenance configuration.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Durable execution configuration (Kernel S9).
 */
export interface ExecutionConfig {
  /**
   * Maximum total workflow duration as ISO 8601 duration (Kernel S9.7).
   */
  workflowTimeout?: string;
  /**
   * Default timeout for human tasks as ISO 8601 duration.
   */
  defaultTaskTimeout?: string;
  /**
   * Default timeout for external service invocations as ISO 8601 duration.
   */
  defaultServiceTimeout?: string;
  /**
   * When true, the workflow scope is compensable (Kernel S9.5). Enables the compensation seam.
   */
  compensable?: boolean;
  /**
   * Instance versioning policy (Kernel S9.6). 'pinned': instance bound to creation-time definition version. 'migrateable': instance may be explicitly migrated to a newer version.
   */
  instanceVersioning?: 'pinned' | 'migrateable';
  /**
   * Extension data for execution configuration.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
