/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Lifecycle Detail Configuration document per the WOS Lifecycle Detail Companion v1.0. Provides detailed compensation, history, and timer configuration that elaborates the kernel's lifecycle semantics. This is an optional companion to a WOS Kernel Document -- a Kernel Structural processor does not need it. A Kernel Complete processor SHOULD use it to configure advanced execution behavior: compensation recovery mode, parallel cancellation behavior, history state policies, and timer tolerance.
 */
export interface WOSLifecycleDetailConfiguration {
  /**
   * WOS Lifecycle Detail specification version. MUST be '1.0'.
   */
  $wosLifecycleDetail: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this configuration targets.
   */
  targetWorkflow: string;
  /**
   * Version of this Lifecycle Detail Configuration.
   */
  version?: string;
  /**
   * Human-readable name.
   */
  title?: string;
  compensation?: CompensationConfig;
  timerConfig?: TimerConfig;
  scxmlMapping?: ScxmlMappingConfig;
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Compensation execution configuration (Lifecycle Detail S5). Elaborates the kernel's compensation seam (Kernel S9.5).
 */
export interface CompensationConfig {
  /**
   * Default recovery mode for compensable scopes (Lifecycle Detail S5.6). 'backward': execute compensation in reverse order, then transition to error state. 'forward': skip compensation, retry or take alternative path.
   */
  defaultRecoveryMode?: 'backward' | 'forward';
  /**
   * Behavior when a compensating action itself fails. 'continue': best effort, proceed to next compensation. 'halt': stop compensation sequence on first failure.
   */
  onCompensationFailure?: 'continue' | 'halt';
  /**
   * Per-scope compensation overrides for specific states or regions.
   */
  scopeOverrides?: CompensationScopeOverride[];
}
export interface CompensationScopeOverride {
  /**
   * Reference to a state or region identifier in the kernel lifecycle.
   */
  scopeRef: string;
  /**
   * Recovery mode override for this scope.
   */
  recoveryMode?: 'backward' | 'forward';
  /**
   * Compensation failure behavior override for this scope.
   */
  onCompensationFailure?: 'continue' | 'halt';
  /**
   * Human-readable explanation of why this scope has a non-default compensation policy.
   */
  description?: string;
}
/**
 * Timer behavior configuration (Lifecycle Detail S6).
 */
export interface TimerConfig {
  /**
   * Maximum acceptable delay between a timer's scheduled firing time and actual firing. ISO 8601 duration. A tolerance greater than the timer's own duration is a conformance violation (Lifecycle Detail S6.6).
   */
  firingTolerance?: string;
  /**
   * Whether timers created in a state's onEntry are automatically cancelled and recreated when the state is re-entered (Lifecycle Detail S6.4). Default: true.
   */
  resetOnReentry?: boolean;
}
/**
 * SCXML interoperability mapping configuration (Lifecycle Detail S7).
 */
export interface ScxmlMappingConfig {
  /**
   * Whether SCXML export/import is enabled for this workflow.
   */
  enabled?: boolean;
  /**
   * How FEL guard expressions are mapped to SCXML's expression language. 'ecmascript': automatic translation to ECMAScript. 'xpath': automatic translation to XPath. 'manual': expressions must be manually mapped.
   */
  expressionMapping?: 'ecmascript' | 'xpath' | 'manual';
  /**
   * Whether WOS-specific properties with no SCXML equivalent (tags, impact level, contracts, milestones) are silently dropped on export. When false, export fails if unsupported properties are present.
   */
  dropUnsupported?: boolean;
  /**
   * Prefix added to kernel-generated events (which use '$' prefix in WOS) when exported to SCXML, since '$' may not be valid in all SCXML implementations.
   */
  eventPrefixMapping?: string;
}
