/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Notification Template Config sidecar document. Defines reusable templates for notices that WOS workflows generate during governance events: adverse decision notices, hold notifications, appeal acknowledgments, SLA warnings, and case status updates. Government workflows have strict notice requirements -- an adverse benefits decision must include the specific determination, individualized reason codes, appeal rights, and filing deadlines. Templates separate notice content from governance logic, enabling independent versioning, localization, and audit. Referenced by notificationTemplateRef (Governance S12.2) and noticeTemplateRef (Governance S3.1).
 */
export interface WOSNotificationTemplateConfig {
  /**
   * WOS Notification Template specification version. MUST be '1.0'.
   */
  $wosNotificationTemplate: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this notification template config applies to.
   */
  targetWorkflow: string;
  /**
   * Version of this Notification Template Config document.
   */
  version?: string;
  /**
   * Human-readable name for this notification template configuration.
   */
  title?: string;
  /**
   * Human-readable description of this notification template collection.
   */
  description?: string;
  /**
   * Named notification templates. Template keys are the identifiers referenced by notificationTemplateRef (Governance S12.2) and noticeTemplateRef (Governance S3.1) in governance documents.
   */
  templates: {
    [k: string]: NotificationTemplate;
  };
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface NotificationTemplate {
  /**
   * Template category. Determines which governance mechanism uses this template. 'adverse-decision': adverse decision notice (Governance S3.1-S3.2). 'hold-notification': hold notice (Governance S12.2). 'appeal-acknowledgment': appeal receipt confirmation (Governance S3.5). 'sla-warning': SLA deadline warning (Governance S10.3). 'case-status-update': general case status notification. 'resume-notification': notice that a case resumed from hold (Governance S12.3).
   */
  category:
    | 'adverse-decision'
    | 'hold-notification'
    | 'appeal-acknowledgment'
    | 'sla-warning'
    | 'case-status-update'
    | 'resume-notification';
  /**
   * Human-readable description of when this template is used.
   */
  description?: string;
  /**
   * Subject line or title for the notification. MAY contain placeholder variables using {{variableName}} syntax.
   */
  subject?: string;
  /**
   * Ordered content sections composing the notification body. For 'adverse-decision' templates, sections MUST address: specific determination, individualized reason codes, appeal rights and filing deadline, and appeal instructions (Notification Template S4.4).
   *
   * @minItems 1
   */
  sections: [TemplateSection, ...TemplateSection[]];
  /**
   * Variables that MUST be present in the rendering context. If any required variable is missing, the processor MUST NOT send the notification and MUST record the failure in provenance.
   */
  requiredVariables?: string[];
  /**
   * Channels through which this notification can be delivered. 'postal': physical mail. 'email': electronic mail. 'portal': web portal notification. 'sms': text message. 'in-app': in-application notification. When absent, delivery channel is implementation-defined.
   */
  deliveryChannels?: ('postal' | 'email' | 'portal' | 'sms' | 'in-app')[];
  /**
   * Reference to a locale-specific variant of this template.
   */
  localeRef?: string;
  /**
   * Regulatory or statutory authority requiring this notification.
   */
  authority?: string;
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface TemplateSection {
  /**
   * Section identifier. MUST be unique within the template.
   */
  id: string;
  /**
   * Section heading displayed in the rendered notification.
   */
  title?: string;
  /**
   * Type of content in this section. 'text': free-text with optional placeholders. 'structured': structured content with labeled fields. 'appeal-rights': standardized appeal rights block (must include filing deadline, review body, continuation status). 'action-required': describes actions the recipient must take. 'contact-information': contact details for questions.
   */
  contentType: 'text' | 'structured' | 'appeal-rights' | 'action-required' | 'contact-information';
  /**
   * Content body. MAY contain placeholder variables using {{variableName}} syntax. Required when contentType is 'text' or 'structured'. For 'appeal-rights', 'action-required', and 'contact-information', content provides additional context beyond the structured elements.
   */
  content?: string;
  /**
   * Whether this section MUST appear in the rendered notification. Default: true.
   */
  required?: boolean;
  /**
   * FEL expression that controls section visibility. When the expression evaluates to false, the section is omitted from the rendered notification. Evaluated against the standard FEL evaluation context (Kernel S7.3).
   */
  condition?: string;
}
