/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Policy Parameter Config sidecar document. Provides date-indexed parameter values for temporal parameter resolution in WOS workflows. Government workflows apply rules effective at specific dates, not today's date. Each parameter declares its effective-date schedule and a resolution date reference -- the case state field that determines which date-effective value applies. Follows the OpenFisca model of date-indexed parameter values.
 */
export interface WOSPolicyParameterConfig {
  /**
   * WOS Policy Parameter Config specification version. MUST be '1.0'.
   */
  $wosPolicyParameters: '1.0';
  /**
   * Optional JSON Schema URI for editor validation.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document these parameters apply to.
   */
  targetWorkflow: string;
  /**
   * Version of this Policy Parameter Config document.
   */
  version?: string;
  /**
   * Human-readable name for this parameter configuration.
   */
  title?: string;
  /**
   * Human-readable description of this parameter set.
   */
  description?: string;
  /**
   * Named parameters with date-indexed values. Parameter names become available in the evaluation context under 'parameters.[name]'.
   */
  parameters: {
    [k: string]: ParameterDefinition;
  };
  /**
   * Named regulatory version bindings with date-indexed document references. Binding names become available in the evaluation context under 'parameters.[name]', resolved to the effective URI for the case's resolution date.
   */
  bindings?: {
    [k: string]: RegulatoryBinding;
  };
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface ParameterDefinition {
  /**
   * Human-readable description of this parameter.
   */
  description: string;
  /**
   * Parameter value type.
   */
  type: 'number' | 'integer' | 'string' | 'boolean';
  /**
   * Unit of measure.
   */
  unit?: string;
  /**
   * Case state field path that provides the resolution date. Different parameters MAY resolve against different dates.
   */
  resolutionDateRef: string;
  /**
   * Regulatory or statutory authority for this parameter.
   */
  authority?: string;
  /**
   * Date-indexed values ordered by effective date. Each entry is effective from its date until the next entry's date.
   *
   * @minItems 1
   */
  values: [DateValue, ...DateValue[]];
}
export interface DateValue {
  /**
   * Date this value becomes effective (ISO 8601 date).
   */
  effectiveDate: string;
  /**
   * The parameter value effective from this date until the next entry.
   */
  value: {
    [k: string]: unknown;
  };
  /**
   * Specific authority for this value change.
   */
  authority?: string;
}
export interface RegulatoryBinding {
  /**
   * Unique binding identifier. Becomes the key in the evaluation context under 'parameters.[id]'.
   */
  id: string;
  /**
   * Human-readable description of what this binding controls.
   */
  description: string;
  /**
   * Case state field path that provides the resolution date. Uses the same mechanism as ParameterDefinition.resolutionDateRef.
   */
  resolutionDateRef: string;
  /**
   * Type of document being versioned. 'formspec': Formspec Definition (Core S1.4). 'jsonSchema': JSON Schema document. 'service': service endpoint URI. 'mapping': Formspec Mapping DSL document. Processors MAY apply type-specific validation but MUST NOT alter the resolution mechanism based on bindingType.
   */
  bindingType: 'formspec' | 'jsonSchema' | 'service' | 'mapping';
  /**
   * Regulatory or statutory authority for this binding.
   */
  authority?: string;
  /**
   * Date-indexed document references ordered by effective date. Each entry is effective from its date until the next entry's date.
   *
   * @minItems 1
   */
  values: [BindingDateValue, ...BindingDateValue[]];
}
export interface BindingDateValue {
  /**
   * Date this binding becomes effective (ISO 8601 date).
   */
  effectiveDate: string;
  /**
   * URI of the document version effective from this date until the next entry.
   */
  value: string;
  /**
   * Specific authority for this version change.
   */
  authority?: string;
}
