/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A persisted WOS provenance record emitted by runtime execution. Facts-tier semantics are normative in the kernel; higher tiers reuse the same envelope and advertise their tier through `auditLayer`. State transition records whose transitionTags include 'determination' MUST include a caseFileSnapshot so later notices, appeals, and override reviews can reproduce the exact factual basis used by the decision.
 */
export type FactsTierRecord = {
  [k: string]: unknown;
} & CapabilityInvocationRecord &
  CorrectionAuthorizedRecord &
  AmendmentAuthorizedRecord &
  DeterminationAmendedRecord &
  RescissionAuthorizedRecord &
  DeterminationRescindedRecord &
  ReinstatedRecord &
  AuthorizationAttestationRecord &
  ClockStartedRecord &
  ClockResolvedRecord &
  IdentityAttestationRecord &
  ClockSkewObservedRecord &
  CommitAttemptFailureRecord &
  AuthorizationRejectedRecord &
  MigrationPinChangedRecord & {
    /**
     * TypeID-structured identifier for this facts-tier provenance record. Reserved family prefix: `prov`.
     */
    id: string;
    /**
     * Provenance record discriminator naming which facts-tier payload shape and processing rules apply. Includes kernel lifecycle and mutation kinds plus ADR-0066/0070/0071 shapes and provenance-log overlays (`caseCreated`, intake outcomes, `signatureAffirmation`) merged at the log `items` allOf seam. Determination snapshot enforcement applies when this value is `stateTransition` and transition tags include `determination`.
     */
    recordKind:
      | 'authorizationAttestation'
      | 'authorizationRejected'
      | 'amendmentAuthorized'
      | 'capabilityInvocation'
      | 'caseCreated'
      | 'caseStateMutation'
      | 'clockResolved'
      | 'clockSkewObserved'
      | 'clockStarted'
      | 'commitAttemptFailure'
      | 'correctionAuthorized'
      | 'determinationAmended'
      | 'determinationRescinded'
      | 'identityAttestation'
      | 'intakeAccepted'
      | 'intakeDeferred'
      | 'intakeRejected'
      | 'instanceMigrated'
      | 'migrationPinChanged'
      | 'reinstated'
      | 'rescissionAuthorized'
      | 'signatureAffirmation'
      | 'stateTransition';
    /**
     * RFC 3339 / ISO 8601 timestamp stamped by the runtime append path before persistence.
     */
    timestamp: string;
    /**
     * Identifier of the actor who triggered the record, when the processor can name one.
     */
    actorId?: string;
    /**
     * Kernel lifecycle state label naming the configuration leaf immediately before this transition-oriented provenance record was emitted.
     */
    fromState?: string;
    /**
     * Kernel lifecycle state label naming the configuration leaf immediately after this transition-oriented provenance record was emitted.
     */
    toState?: string;
    /**
     * Triggering event or reserved event literal carried by the record kind.
     */
    event?: string;
    /**
     * Arbitrary JSON object carrying record-kind-specific correlation keys, diagnostics, or structured details not represented by top-level scalar provenance fields.
     */
    data?: {
      [k: string]: unknown;
    };
    /**
     * Audit tier for the persisted/exported record. Facts-tier records are normative in the kernel; higher layers reuse the same envelope and set a different tier literal.
     */
    auditLayer: 'facts' | 'reasoning' | 'counterfactual' | 'narrative';
    /**
     * Actor classification when the processor can resolve one canonically. Reserved literals are `human`, `system`, and `agent`; extension values MUST use an `x-` prefix.
     */
    actorType?: (
      | ('human' | 'system' | 'agent')
      | {
          [k: string]: unknown;
        }
    ) &
      string;
    /**
     * Lifecycle state at the time of the action when the processor can determine it canonically.
     */
    lifecycleState?: string;
    /**
     * Version of the governing Kernel Document stamped at append time.
     */
    definitionVersion: string;
    /**
     * Input entity references used by this activity.
     */
    inputs?: string[];
    /**
     * Output entity references generated by this activity.
     */
    outputs?: string[];
    /**
     * Outcome literal recorded on a Facts-tier provenance record when the processor completes (or declines to complete) an action. Open enum: the listed values are reserved across all tiers; vendor extensions MUST use an `x-` prefix to avoid future conflicts. Reserved literals currently defined: `preconditionNotSatisfied` (AI Integration §3.3.1 -- emitted when a capability precondition FEL expression evaluates to false or non-boolean, blocking agent invocation and falling through to the fallback chain) and `convergenceCapReached` (Runtime §10.3 -- emitted when continuous-mode re-evaluation hits the 100-cycle convergence cap for a single triggering mutation).
     */
    outcome?: (
      | ('preconditionNotSatisfied' | 'convergenceCapReached')
      | {
          [k: string]: unknown;
        }
    ) &
      string;
    /**
     * Semantic tags copied from the firing transition when this record represents a state transition. The presence of 'determination' makes caseFileSnapshot mandatory.
     */
    transitionTags?: string[];
    caseFileSnapshot?: CaseFileSnapshot;
    /**
     * Origin of the mutation when recordKind is 'caseStateMutation'. OPTIONAL on other record kinds. Reserved literals trace the provenance chain from human entry through AI extraction to system-fetch and computed derivation.
     */
    mutationSource?: (
      | ('human-entered' | 'human-corrected' | 'agent-extracted' | 'system-fetched' | 'computed' | 'self-attested')
      | {
          [k: string]: unknown;
        }
    ) &
      string;
    /**
     * OPTIONAL verification strength of this mutation. When present, signals the degree of independent confirmation behind the written value. Tying this to 'determination'-tagged transitions is policy-shaped (governance profile), not a blanket kernel MUST.
     */
    verificationLevel?: (
      | ('independent' | 'attested' | 'corroborated' | 'authoritative')
      | {
          [k: string]: unknown;
        }
    ) &
      string;
    /**
     * Lowercase hex rendering of the 32-byte Trellis `canonical_event_hash` stamped after custody admission, when present.
     */
    canonicalEventHash?: string;
    [k: string]: unknown;
  };
/**
 * Shape constraint layered on Facts-tier provenance records emitted by the AI §3.3.1 capability-invocation path. A record representing a precondition-blocked invocation (`recordKind == "capabilityInvocation"` AND `data.invocationBlocked == true`) MUST carry `outcome: "preconditionNotSatisfied"` so audit tooling can distinguish a declarative precondition gate from an agent failure. This `$def` is composed into `FactsTierRecord.allOf` below; runtime provenance logs that `$ref` this schema's `FactsTierRecord` (for example `wos-provenance-log.schema.json`) inherit the same MUST. Records with other `recordKind` values or absent `data.invocationBlocked` fall outside the guard and are unaffected.
 */
export type CapabilityInvocationRecord = {
  [k: string]: unknown;
} & {
  /**
   * Provenance record discriminator. `capabilityInvocation` selects records emitted by the AI §3.3.1 capability-invocation path (whether the invocation proceeded, was blocked by a precondition, or failed post-invocation).
   */
  recordKind?: 'capabilityInvocation';
  /**
   * Record payload for a capability-invocation provenance entry. Carries the AI §3.3.1 `invocationBlocked` flag plus any additional context the processor chooses to record (capability id, resolved precondition value, expression source, etc.).
   */
  data?: {
    /**
     * True when the processor declined to invoke the agent because a capability precondition evaluated to `false` or a non-boolean (AI Integration §3.3.1). The processor MUST then fall through to the fallback chain (AI §8). False (or absent) means the capability was invoked.
     */
    invocationBlocked?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0066 D-1 mode 1 (`correction`): a typo-class fix to a prior record's surface that does not change the determination outcome. The authorizing act records who approved the correction, the targeted prior event hash, the field set being corrected, the reason, and the authority basis. Spec MUST source: ADR-0066 §Five-Mode Taxonomy + Authorizing-Act Pair (Q26 maximalist).
 */
export type CorrectionAuthorizedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Discriminator for ADR-0066 mode 1 correction-authorizing acts.
   */
  recordKind?: 'correctionAuthorized';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0066 D-1 mode 2 (`amendment`): a substantive change to a prior determination that explicitly references the prior outcome. The authorizing act records who approved the amendment, the targeted prior event hash, the prior determination hash, the reason, and the authority basis. The paired determination-change record is `determinationAmended`. Spec MUST source: ADR-0066 §Five-Mode Taxonomy + Authorizing-Act Pair (Q26 maximalist).
 */
export type AmendmentAuthorizedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Discriminator for ADR-0066 mode 2 amendment-authorizing acts.
   */
  recordKind?: 'amendmentAuthorized';
  [k: string]: unknown;
};
/**
 * Shape constraint for the determination-change half of an ADR-0066 mode-2 amendment. Recorded after the paired `amendmentAuthorized` event lands. Carries the prior determination hash, the new determination value (any JSON shape per the workflow contract), and the back-reference to the authorizing event. Verifiers MUST be able to walk amendmentAuthorizationEventHash -> priorDeterminationHash to confirm the chain. Spec MUST source: ADR-0066 D-1 + Q26.
 */
export type DeterminationAmendedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Discriminator for the post-authorization determination-change event of an ADR-0066 mode 2 amendment.
   */
  recordKind?: 'determinationAmended';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0066 D-1 mode 4 (`rescission`): a determination is withdrawn entirely, leaving the case without an active determination. The authorizing act records who approved the rescission, the targeted event, the prior determination hash, reason, authority basis, and (optionally) a migration pin change when the rescission accompanies a chain-pin shift (ADR-0071). Paired determination-state record: `determinationRescinded`. Spec MUST source: ADR-0066 D-1 + Q26 maximalist + ADR-0071 D-3.
 */
export type RescissionAuthorizedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Discriminator for ADR-0066 mode 4 rescission-authorizing acts.
   */
  recordKind?: 'rescissionAuthorized';
  [k: string]: unknown;
};
/**
 * Shape constraint for the determination-state half of an ADR-0066 mode-4 rescission. Recorded after the paired `rescissionAuthorized` event lands. Carries the prior determination hash and the back-reference to the authorizing event. After this record, the case has no active determination until a new determination event fires or a `reinstated` event reactivates the prior one. Spec MUST source: ADR-0066 D-1 + Q26.
 */
export type DeterminationRescindedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Discriminator for the post-authorization determination-removal event of an ADR-0066 mode 4 rescission.
   */
  recordKind?: 'determinationRescinded';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0066 D-1 mode 5 (`reinstatement`): a previously rescinded determination is restored. Q26 maximalist Five-Mode position requires reinstatement be a first-class mode rather than an inverse rescission, so verifiers can distinguish 'never rescinded' from 'rescinded then restored' cases. Carries the prior rescission event hash, the reactivation authorization event hash (a separate `authorizationAttestation` with `policyPredicate: "reinstatement-authority"`), and the reason. Spec MUST source: ADR-0066 D-1 + Q26 maximalist five-mode position.
 */
export type ReinstatedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Discriminator for ADR-0066 mode 5 reinstatement (Q26 maximalist five-mode).
   */
  recordKind?: 'reinstated';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0066's authority-attestation primitive: a free-standing record of who holds amendment / rescission / reinstatement / correction authority under what policy predicate. Authorization attestations stand alone in the chain so policy auditors can verify authority basis without parsing every authorizing-act record. Reserved policyPredicate values are `amendment-authority`, `rescission-authority`, `reinstatement-authority`, `correction-authority`; vendor extensions MUST use `x-` prefix. Spec MUST source: ADR-0066 §Authority-Attestation Primitive.
 */
export type AuthorizationAttestationRecord = {
  [k: string]: unknown;
} & {
  /**
   * Record-kind discriminator identifying authorization attestation provenance records in runtime logs and schema views.
   */
  recordKind?: 'authorizationAttestation';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0067's clock-start event. Pins the clock identity, kind (open enum: AppealClock, ProcessingSLA, GrantExpiry, StatuteClock), origin event, ISO-8601 duration, and computed deadline. Optional `calendarRef` and `statuteReference` capture business-calendar and regulatory-source bindings respectively. Open-enum kind allows vendor `x-` extensions for domain-specific clocks (e.g. `x-medicaid-redetermination-clock`). Spec MUST source: ADR-0067 D-2.
 */
export type ClockStartedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Record-kind discriminator identifying clock started provenance records in runtime logs and schema views.
   */
  recordKind?: 'clockStarted';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0067's clock-resolution event. Closed-enum resolution: `satisfied` (clock target met), `elapsed` (deadline reached without satisfaction), `paused` (clock halted by an explicit pause event), `cancelled` (clock voided by upstream rescission/correction). Q11 maximalist position: when `resolution = "paused"` the resolving event MUST be present (the pause event itself); when `resolution = "elapsed"` and `resolvingEventHash` is absent, the record represents a synthetic-elapsed emission (the deadline simply passed with no event). Spec MUST source: ADR-0067 D-3 + Q11 maximalist.
 */
export type ClockResolvedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Record-kind discriminator identifying clock resolved provenance records in runtime logs and schema views.
   */
  recordKind?: 'clockResolved';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0068's tenant-independent identity-attestation primitive. Pins the subject's tenant-independent global identifier, assurance level, attestation provider, attested predicates (open list), and timestamp. Q31-relevant: cross-tenant case movement uses supersession (WOS/kernel caseRelationships per kernel spec S5.5; not modeled as a field here) rather than identity migration; this primitive carries identity attestation that travels with the case file but does not itself rewrite tenant boundaries. Spec MUST source: ADR-0068 D-1.
 */
export type IdentityAttestationRecord = {
  [k: string]: unknown;
} & {
  /**
   * Record-kind discriminator identifying identity attestation provenance records in runtime logs and schema views.
   */
  recordKind?: 'identityAttestation';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0069's clock-skew observation event. Emitted when the absolute difference between processor-authored timestamp and Trellis substrate-created timestamp exceeds the deployment-configured threshold (default 1000ms). Provides a tamper-evident trail of time-source disagreement so downstream verifiers can decide whether to trust deadline computations on adjacent events. Spec MUST source: ADR-0069 D-2 (Q12 maximalist threshold).
 */
export type ClockSkewObservedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Record-kind discriminator identifying clock skew observed provenance records in runtime logs and schema views.
   */
  recordKind?: 'clockSkewObserved';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0070 D-2's commit-attempt failure event. Emitted when the kernel's commit path to Trellis fails (network timeout, substrate down, hash conflict, other). Carries the target event hash, failure kind (closed enum), attempt count, retry budget, and optional error payload for diagnostics. The kernel records every commit failure so retries are accountable; the kernel-side `stalled` instance status (case-instance schema) lights up when retry budgets exhaust. Spec MUST source: ADR-0070 D-2.
 */
export type CommitAttemptFailureRecord = {
  [k: string]: unknown;
} & {
  /**
   * Discriminator for ADR-0070 D-2 commit-attempt failure events.
   */
  recordKind?: 'commitAttemptFailure';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0070 D-3's authorization-rejection event. Emitted when an actor attempts an action they lack authority for (action policy denied, role-based gate failed, deontic constraint violated). Carries the attempted actor / action / target plus a rejection reason and optional policy-decision back-reference. Pairs with `authorizationAttestation` records: when an attempt fails because no matching attestation exists, audit reviewers can walk the rejection back to the missing authority. Action format follows verb:resource convention (e.g. `transition:approve`, `submit:taskResponse`). Spec MUST source: ADR-0070 D-3.
 */
export type AuthorizationRejectedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Discriminator for ADR-0070 D-3 authorization-rejection events.
   */
  recordKind?: 'authorizationRejected';
  [k: string]: unknown;
};
/**
 * Shape constraint for ADR-0071's migration-pin-change event. Records a transition between spec-version pin sets governing a workflow instance: prior and new four-field pin tree (formspec.definitionVersion, wos.$wosWorkflowVersion, trellis.envelopeVersion, trellis.conformanceClass). Q33 maximalist position pins all four spec layers explicitly so verifiers can replay the chain against the exact spec versions in force at each segment. Carries authorizing actor, authority basis, and migration rationale. Composes with `rescissionAuthorized.data.migrationPinChange` when a chain re-pin accompanies a rescission. Spec MUST source: ADR-0071 D-1 + Q33 maximalist.
 */
export type MigrationPinChangedRecord = {
  [k: string]: unknown;
} & {
  /**
   * Record-kind discriminator identifying migration pin changed provenance records in runtime logs and schema views.
   */
  recordKind?: 'migrationPinChanged';
  [k: string]: unknown;
};
/**
 * Shape constraint layered on Facts-tier provenance records that mark the governed-case boundary. The kernel reserves the `caseCreated` kind and the canonical event literal `case.created`, and it requires the created governed-case reference in `data.caseRef`. The kernel does not freeze the rest of the binding-specific `data` keys; bindings may carry different evidence references inside `data` as long as the record still identifies the created governed case.
 */
export type CaseCreatedRecord = {
  [k: string]: unknown;
};
/**
 * Shape constraint layered on Facts-tier provenance records emitted when runtime intake acceptance succeeds. Accepted intake creates or updates governed-case handling, so the record MUST carry the canonical event literal `case.intake.accepted`, binding/intake context in `data`, the accepted case disposition, the canonical governed-case reference, and at least one governed-case output reference.
 */
export type IntakeAcceptedRecord = {
  [k: string]: unknown;
};
/**
 * Shape constraint layered on Facts-tier provenance records emitted when runtime intake acceptance rejects a handoff. Rejection records remain detached from governed case mutation and therefore do not require governed-case outputs.
 */
export type IntakeRejectedRecord = {
  [k: string]: unknown;
};
/**
 * Shape constraint layered on Facts-tier provenance records emitted when runtime intake acceptance defers a handoff. Deferred records preserve intake context and reason code without creating or updating governed case state.
 */
export type IntakeDeferredRecord = {
  [k: string]: unknown;
};
/**
 * Shape constraint layered on Facts-tier provenance records emitted by the Signature Profile. A `recordKind == "signatureAffirmation"` record MUST carry the signer, role, document, hash, timestamp, identity-binding, consent, provider, ceremony, profile, Formspec response, and custody eligibility fields required by Signature Profile §2.8.
 */
export type SignatureAffirmationRecord = {
  [k: string]: unknown;
} & {
  /**
   * `signatureAffirmation` selects records emitted when a Signature Profile signing act is accepted.
   */
  recordKind?: string;
  [k: string]: unknown;
};

/**
 * Append-only audit log produced by WOS runtime execution. Per ADR 0063 §2.3 this is a runtime artifact (not author-time), emitted by processors, never hand-authored. The required `$wosProvenanceLog` marker gives runtime artifacts the same identity discipline as author-time documents and lets the lint parser detect them uniformly. Wraps every persisted record kind: state-transition records (Kernel §8), case-file snapshots (Kernel §8 — required when transitionTags includes 'determination'), capability-invocation records (AI Integration §3.3.1), signature-affirmation records (Signature Profile §2.8), case-state mutation records carrying mutationSource / verificationLevel (Kernel §5.4, ADR 0080), iteration records (Kernel §4.10/foreach), and verification certificates (formerly the runtime half of `wos-verification-report`). Facts-tier semantics are normative in the kernel and live in the merged `wos-workflow.schema.json` $defs (ADR 0076 step 5 promotion: FactsTierRecord, MutationSource, VerificationLevel, CaseFileSnapshot, CapabilityInvocationRecord). Higher tiers reuse the same envelope with `auditLayer` set accordingly. This schema validates the post-append export shape -- not unstamped in-memory constructors.
 */
export interface WOSProvenanceLog {
  /**
   * Top-level marker identifying this object as a WOS Provenance Log runtime artifact, pinned to the 1.0 line. Required per ADR 0063 §2.3 so the lint parser detects runtime artifacts uniformly with author-time documents.
   */
  $wosProvenanceLog: '1.0';
  /**
   * Ordered sequence of persisted provenance records emitted during a workflow run. Records are append-only and their order matches emission order; consumers MUST preserve ordering when re-exporting.
   */
  provenanceLog: (FactsTierRecord &
    CaseCreatedRecord &
    IntakeAcceptedRecord &
    IntakeRejectedRecord &
    IntakeDeferredRecord &
    SignatureAffirmationRecord)[];
}
/**
 * Canonical case-file snapshot captured immediately before a determination-tagged transition fires. The value is the factual input to the determination; jcsCanonical and sha256 make the snapshot stable and tamper-evident for notices, appeals, and audit export.
 */
export interface CaseFileSnapshot {
  /**
   * Raw case-file JSON value observed immediately before the determination transition fires. This value may be an object, array, string, number, boolean, or null depending on the processor's case-state representation.
   */
  value: {
    [k: string]: unknown;
  };
  /**
   * Canonical JSON string for value using JCS (RFC 8785) canonicalization semantics. Identical case-file state MUST produce byte-identical canonical strings.
   */
  jcsCanonical: string;
  /**
   * Lowercase SHA-256 hex digest of jcsCanonical. This digest links the human-readable snapshot to tamper-evident exports without requiring downstream systems to reserialize value.
   */
  sha256: string;
}
