/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Optional JSON Schema URI enabling editor validation, type generation, and autocompletion.
 */
export type JsonSchemaUri = string;
/**
 * Local id for a sibling object within the Signature Profile document.
 */
export type Identifier = string;
/**
 * Closed set of signer roles understood by WOS Signature Profile runtime semantics.
 */
export type SignerRole =
  | 'signer'
  | 'in-person-signer'
  | 'certified-recipient'
  | 'witness'
  | 'notary'
  | 'approver'
  | 'form-filler'
  | 'viewer';
/**
 * Digest algorithm used to bind a signable document to its signature evidence record.
 */
export type HashAlgorithm = string;
export type CompletionRequirement = {
  [k: string]: unknown;
} & {
  /**
   * Completion rule used to decide when selected signing steps satisfy the overall signature flow.
   */
  type: 'all-required' | 'any-required' | 'count' | 'role-set';
  /**
   * Minimum number of selected signing steps that must affirm when the completion type is count.
   */
  count?: number;
  /**
   * @minItems 1
   */
  roleIds?: [Identifier, ...Identifier[]];
};
/**
 * Path to evidence in a Formspec response, case file, or profile-supported evidence source.
 */
export type CasePath = string;
/**
 * Closed WOS authentication methods plus vendor x-* methods for identity binding evidence.
 */
export type AuthenticationMethod = string;
/**
 * Ordered assurance strength reached by the identity-binding evidence for a signing act.
 */
export type AssuranceLevel = 'none' | 'low' | 'standard' | 'high' | 'very-high';
/**
 * Package-local key for maps and catalogs; keys are not URI cross-artifact references.
 */
export type Key = string;
/**
 * Lifecycle or timer event name emitted by WOS runtime for signature policy actions.
 */
export type EventName = string;
/**
 * ISO 8601 duration used for reminder schedules and signature expiry policy timing.
 */
export type Duration = string;

/**
 * A WOS Signature Profile Document per the WOS Signature Profile specification v1.0. Declares signer roles, signing flow, document binding, consent evidence, identity-binding requirements, and policy hooks for signature workflows. WOS governs the workflow semantics and emits SignatureAffirmation provenance; Trellis owns anchoring and certificate/export composition.
 */
export interface WOSSignatureProfileDocument {
  /**
   * WOS Signature Profile document marker and version pin. Processors use this field to identify the document as a Signature Profile and to reject incompatible signature workflow semantics before runtime execution begins.
   */
  $wosSignatureProfile: '1.0';
  $schema?: JsonSchemaUri;
  targetWorkflow: TargetWorkflow;
  /**
   * Version of this Signature Profile Document. SemVer is RECOMMENDED.
   */
  version?: string;
  /**
   * Human-readable title for this signature profile, suitable for authoring tools and validation reports.
   */
  title?: string;
  /**
   * Human-readable description of the signature workflow and the signing ceremony it governs.
   */
  description?: string;
  /**
   * Signature roles bound to kernel human actors.
   *
   * @minItems 1
   */
  roles: [SignatureRole, ...SignatureRole[]];
  /**
   * Documents that can be signed under this profile.
   *
   * @minItems 1
   */
  documents: [SignatureDocument, ...SignatureDocument[]];
  signingFlow: SigningFlow;
  evidence: SignatureEvidence;
  /**
   * Named authentication policies referenced by signature roles.
   */
  authenticationPolicies?: AuthenticationPolicy[];
  reminders?: ReminderPolicy;
  expiryPolicy?: ExpiryPolicy;
  declinePolicy?: DeclinePolicy;
  voidPolicy?: VoidPolicy;
  reassignmentPolicy?: ReassignmentPolicy;
  extensions?: ExtensionsMap;
}
/**
 * The WOS Kernel Document this signature profile targets.
 */
export interface TargetWorkflow {
  /**
   * Canonical URI of the target WOS Kernel Document that this Signature Profile augments.
   */
  url: string;
  /**
   * SemVer range expression for compatible kernel document versions.
   */
  compatibleVersions?: string;
}
export interface SignatureRole {
  id: Identifier;
  role: SignerRole;
  /**
   * Local id for a sibling object within the Signature Profile document.
   */
  actorId: string;
  /**
   * Whether this role must affirm for the configured signing-flow completion requirement to be satisfied.
   */
  required?: boolean;
  /**
   * Key of a policy in authenticationPolicies.
   */
  authenticationPolicyKey?: string;
  /**
   * Human-readable explanation of the signer role and why it participates in this profile.
   */
  description?: string;
}
export interface SignatureDocument {
  id: Identifier;
  /**
   * URI reference to the signable document artifact whose digest is bound to the signing evidence.
   */
  documentRef: string;
  /**
   * Digest of the signable document bytes.
   */
  documentHash: string;
  documentHashAlgorithm: HashAlgorithm;
  /**
   * Optional URI reference to rendered-document metadata or to the rendered artifact shown to signers.
   */
  renderingRef?: string;
  /**
   * Optional URI reference to the canonical Formspec response that supplied signature evidence.
   */
  formspecResponseRef?: string;
}
/**
 * Signing flow declaration.
 */
export interface SigningFlow {
  /**
   * Signing flow pattern used by the runtime to decide ordering, guard selection, and completion semantics.
   */
  type: 'sequential' | 'parallel' | 'routed' | 'free-for-all';
  /**
   * @minItems 1
   */
  steps: [SigningStep, ...SigningStep[]];
  completion?: CompletionRequirement;
}
export interface SigningStep {
  id: Identifier;
  roleId: Identifier;
  documentId: Identifier;
  /**
   * FEL expression evaluated against case state to decide whether this routed signing step is selected.
   */
  guard?: string;
  /**
   * Sibling signing-step ids that must complete before this step.
   */
  dependsOn?: Identifier[];
  /**
   * Whether this signing step must affirm before the configured flow completion requirement can pass.
   */
  required?: boolean;
}
/**
 * Evidence inputs required before WOS emits SignatureAffirmation.
 */
export interface SignatureEvidence {
  /**
   * Required provenance record kind emitted by WOS when all signature evidence requirements pass.
   */
  recordKind: 'signatureAffirmation';
  /**
   * @minItems 1
   */
  requiredFields: [CasePath, ...CasePath[]];
  consentReference: ConsentReference;
  identityBinding: IdentityBindingRequirement;
  /**
   * Whether resulting SignatureAffirmation records are eligible for WOS custodyHook admission.
   */
  custodyHookEligible: true;
}
export interface ConsentReference {
  /**
   * URI reference to the consent text that the signer accepted as part of the signing ceremony.
   */
  consentTextRef: string;
  /**
   * Version of the consent text accepted by the signer and recorded in signature evidence.
   */
  consentVersion: string;
  /**
   * Path to evidence in a Formspec response, case file, or profile-supported evidence source.
   */
  acceptedAtPath: string;
  /**
   * Path to evidence in a Formspec response, case file, or profile-supported evidence source.
   */
  affirmationPath: string;
}
export interface IdentityBindingRequirement {
  method: AuthenticationMethod;
  assuranceLevel: AssuranceLevel;
  /**
   * URI reference to the identity or signature provider required for this identity binding.
   */
  providerRef?: string;
  /**
   * URI reference to an external identity attestation that supports this signature evidence.
   */
  externalAttestationRef?: string;
}
export interface AuthenticationPolicy {
  key: Key;
  method: AuthenticationMethod;
  assuranceLevel: AssuranceLevel;
  /**
   * URI reference to the identity provider or signature ceremony provider used by this policy.
   */
  providerRef?: string;
  /**
   * Whether this authentication policy requires evidence from an in-person or notary ceremony.
   */
  requiresInPerson?: boolean;
  /**
   * Whether this authentication policy requires credential evidence from the ceremony provider.
   */
  requiresCredentialEvidence?: boolean;
}
export interface ReminderPolicy {
  eventName: EventName;
  /**
   * @minItems 1
   */
  schedule: [Duration, ...Duration[]];
  templateKey?: Key;
}
export interface ExpiryPolicy {
  eventName: EventName;
  after: Duration;
  transitionId?: Identifier;
}
export interface DeclinePolicy {
  /**
   * Lifecycle or timer event name emitted by WOS runtime for signature policy actions.
   */
  transitionId: string;
  /**
   * Whether a signer decline must include a non-empty reason before the runtime accepts it.
   */
  reasonRequired?: boolean;
}
export interface VoidPolicy {
  /**
   * @minItems 1
   */
  authorizedActorIds: [Identifier, ...Identifier[]];
  /**
   * Whether an authorized void operation must include a non-empty reason before it is accepted.
   */
  reasonRequired?: boolean;
}
export interface ReassignmentPolicy {
  /**
   * @minItems 1
   */
  authorizedActorIds: [Identifier, ...Identifier[]];
  /**
   * Accountability mode for reassignment; WOS preserves original and new signer evidence.
   */
  accountability: 'preserve-original-assignment';
  /**
   * Whether reassignment must include a non-empty reason before the runtime accepts it.
   */
  reasonRequired?: boolean;
}
/**
 * Vendor extension data attached to this node. All keys MUST start with x-.
 */
export interface ExtensionsMap {
  [k: string]: unknown;
}
