/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single tooling-artifact schema absorbing five formerly-separate tooling schemas per ADR 0076 D-5: wos-lint-diagnostic, conformance-trace, wos-synth-trace, wos-mcp-tools, and wos-extension-registry. These artifacts are consumed by tooling (CI pipelines, LLM authoring loops, IDE integrations, MCP hosts), never hand-authored by workflow designers. The schema acts as a discriminated union: a document carrying $wosTooling at version 1.0 declares its kind (lintDiagnostic / conformanceTrace / synthTrace / mcpToolCatalog / extensionRegistry) and conforms to that view. Sub-views are exposed via $views per Q3 owner decision (tooling-schema sub-views, not core-schema annotations).
 */
export type WOSTooling = {
  [k: string]: unknown;
} & {
  /**
   * Sole top-level version marker that identifies this object as a WOS Tooling artifact and pins it to the 1.0 line of the merged tooling schema (ADR 0076 D-5). Tooling consumers select the appropriate sub-view based on the `kind` discriminator.
   */
  $wosTooling: '1.0';
  /**
   * Discriminator selecting which sub-view this document conforms to. The five tooling artifact kinds (lintDiagnostic, conformanceTrace, synthTrace, mcpToolCatalog, extensionRegistry) were formerly separate schemas; merged here per ADR 0076 D-5.
   */
  kind: 'lintDiagnostic' | 'conformanceTrace' | 'synthTrace' | 'mcpToolCatalog' | 'extensionRegistry';
};
