/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Verification Report sidecar document. Records the results of SMT-based formal verification of deontic constraints and governance rules. Captures which constraints were verified, the result (proven-safe, proven-unsafe, inconclusive), counterexamples, and solver metadata. Reports are immutable provenance artifacts.
 */
export interface WOSVerificationReport {
  /**
   * WOS Verification Report specification version. MUST be '1.0'.
   */
  $wosVerificationReport: '1.0';
  $schema?: string;
  /**
   * URI of the WOS Kernel Document whose constraints were verified. Follows the same targetWorkflow binding pattern as Layer 1 and Layer 2 sidecars.
   */
  targetWorkflow: string;
  version?: string;
  /**
   * When the verification was performed.
   */
  timestamp: string;
  solver: SolverInfo;
  /**
   * Per-constraint verification results.
   *
   * @minItems 1
   */
  results: [ConstraintResult, ...ConstraintResult[]];
  summary?: VerificationSummary;
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Information about the verification tool.
 */
export interface SolverInfo {
  /**
   * Solver name.
   */
  name: string;
  /**
   * Solver version.
   */
  version: string;
  /**
   * Solver timeout per constraint.
   */
  timeout?: string;
}
export interface ConstraintResult {
  /**
   * Reference to the deontic constraint that was verified.
   */
  constraintRef: string;
  /**
   * Verification result. 'proven-safe': constraint holds for all possible inputs within declared domains. 'proven-unsafe': a counterexample exists. 'inconclusive': solver timed out or construct outside verifiable subset.
   */
  result: 'proven-safe' | 'proven-unsafe' | 'inconclusive';
  counterexample?: Counterexample;
  /**
   * Time the solver spent on this constraint in milliseconds.
   */
  solverTimeMs?: number;
  /**
   * Additional notes from the verification process.
   */
  notes?: string;
}
/**
 * Counterexample data when result is 'proven-unsafe'.
 */
export interface Counterexample {
  /**
   * Input values that violate the constraint.
   */
  inputs?: {
    [k: string]: unknown;
  };
  /**
   * Human-readable explanation of why this input violates the constraint.
   */
  explanation?: string;
}
/**
 * Aggregate verification summary.
 */
export interface VerificationSummary {
  totalConstraints?: number;
  provenSafe?: number;
  provenUnsafe?: number;
  inconclusive?: number;
  totalSolverTimeMs?: number;
}
