/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single author-time schema for a WOS workflow. Scales from Forms+ intake (~30 lines) to complex case management (~3000 lines) without changing shape. Required core: impactLevel, actors, lifecycle. Optional embedded blocks (governance, agents, aiOversight, signature, custody, advanced, assurance) appear only when product behavior demands them. Conditional rules require governance for rights-impacting/safety-impacting workflows, agents block for agent-typed actors, and signature block for signature-gated transitions. Deployment-environment configuration (calendars, notification templates, ontology alignment) lives in two sidecars referenced by targetWorkflow URI. See ADR 0076 (merged-envelope consolidation) and ADR 0063 (embedded-vs-sidecar identity boundary).
 */
export type WOSWorkflow = RightsImpactingAndSafetyImpactingWorkflowsMUSTEmbedGovernance &
  WorkflowsWhoseActorsIncludeAnyAgentTypedActorMUSTDeclareAgents & {
    [k: string]: unknown;
  } & WorkflowsWithBothAgentsAndAdvancedFeaturesSHOULDDeclareAiOversight &
  EmbeddedBlocksMUSTNOTDeclareTargetWorkflowADR006321 &
  EmbeddedBlocksMUSTNOTDeclareIndependentUrlOrVersionADR006321 & {
    /**
     * Sole top-level version marker that identifies this object as a WOS Workflow Document and pins it to the 1.0 line of the merged-schema product-tier model (ADR 0076). Stream identity (governance, agents, signature, custody, advanced) is implicit in the envelope version; compliance claims compose as $wosWorkflow@X.Y. Replaces the historical four-document markers $wosKernel / $wosWorkflowGovernance / $wosAIIntegration / $wosAdvanced.
     */
    $wosWorkflow: '1.0';
    /**
     * Canonical URI identifier for this Workflow Document. The URL names the workflow definition, not any particular instance — all versions of the same workflow SHOULD share this URL, and the pair (url, version) SHOULD be globally unique. Sidecars (`wos-delivery`, `wos-ontology-alignment`) join by this URL via `targetWorkflow`. Prefer stable, resolvable URIs under a namespace the authoring organization controls.
     */
    url: string;
    /**
     * Version string for this Workflow Document. Semantic Versioning (SemVer 2.0.0) is RECOMMENDED so processors and governance layers can reason about compatibility. Instance versioning (Kernel §9.6) pins each running workflow instance to the (url, version) pair of the definition that created it.
     */
    version: string;
    /**
     * Short human-readable name for this workflow, suitable for lists, navigation, and audit summaries. Not interpreted by the processor.
     */
    title: string;
    /**
     * Free-text description of this workflow's purpose, scope, and intended audience. Consumed by documentation tooling and LLM authoring agents; not interpreted by the processor.
     */
    description?: string;
    /**
     * Publication status of this workflow definition. `draft` means the definition is being authored and SHOULD NOT instantiate production cases. `active` means the definition is in effect and new instances MAY be created. `deprecated` means no new instances SHOULD be created, though existing pinned instances continue executing.
     */
    status?: 'draft' | 'active' | 'deprecated';
    /**
     * Consequence level classification for decisions made within this workflow (Kernel §6). `rights-impacting`: decisions affect individual legal rights — full due process REQUIRED (governance block MUST be present). `safety-impacting`: decisions affect safety — full due process REQUIRED (governance block MUST be present). `operational`: organizational operations — governance RECOMMENDED. `informational`: no binding decisions — governance OPTIONAL. Drives conditional block requirements via the schema's allOf rules.
     */
    impactLevel: 'informational' | 'operational' | 'rights-impacting' | 'safety-impacting';
    caseFile?: CaseFile;
    intake?: IntakeReference;
    /**
     * Non-empty list of actors (humans, systems, or agents) that may perform transitions. Each entry has a unique `id`; transitions reference these ids. When any actor uses type `agent`, the `agents` and `aiOversight` blocks are required (lint WOS-AGENT-XREF-001).
     *
     * @minItems 1
     */
    actors: [Actor, ...Actor[]];
    lifecycle: Lifecycle;
    contracts?: Contracts;
    bindings?: OutputBinding[];
    provenance?: ProvenanceConfig;
    governance?: Governance;
    /**
     * Per-agent declarations (model, autonomy, deontic constraints, drift policy) embedded in the merged workflow. Required when any actor has type agent (lint WOS-AGENT-XREF-001).
     */
    agents?: AgentDeclaration[];
    aiOversight?: AIOversight;
    signature?: Signature;
    custody?: Custody;
    advanced?: Advanced;
    assurance?: Assurance;
    /**
     * Vendor-namespaced extension container realizing Kernel §10.6 (the `extensions` seam — one of the canonical six per ADR 0077). Every key MUST start with `x-`; the prefix `x-wos-` is RESERVED for future normative WOS use (lint K-EXT-002 warns). Values are opaque to the processor; vendors document their own subkeys.
     */
    extensions?: {
      [k: string]: unknown;
    };
    /**
     * Standard JSON Schema annotation declaring the meta-schema URI. Not interpreted by the WOS processor; consumed by IDEs/validators for tooling integration.
     */
    $schema?: string;
    /**
     * Execution configuration (Kernel §9). Workflow/task/service timeouts, compensability, and instance-versioning policy. Honored by the durable runtime adapter; spec-authoritative semantics live in `wos-runtime`.
     */
    execution?: {
      /**
       * Maximum total workflow duration as an ISO 8601 duration. The durable runtime treats this as the outer case-level timeout.
       */
      workflowTimeout?: string;
      /**
       * Default task timeout as an ISO 8601 duration when an individual task omits an explicit SLA or timeout override.
       */
      defaultTaskTimeout?: string;
      /**
       * Default service-call timeout as an ISO 8601 duration when an invocation does not declare a narrower timeout.
       */
      defaultServiceTimeout?: string;
      /**
       * Whether the workflow scope is compensable under Kernel §9.5, meaning failed side effects require declared compensation behavior.
       */
      compensable?: boolean;
      /**
       * Instance versioning policy (Kernel §9.6). `pinned` keeps each running instance bound to the (url, version) of the Kernel Document that created it. `migrateable` permits explicit migration to a newer compatible revision when the runtime records the migration. Omitted policy MUST be treated as `pinned` (spec §1483).
       */
      instanceVersioning?: 'pinned' | 'migrateable';
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^x-".
       */
      [k: string]: unknown;
    };
    /**
     * Evaluation mode for guards and computed expressions (Kernel §12). `event-driven` (default) re-evaluates on transition events; `continuous` re-evaluates on any case-file mutation.
     */
    evaluationMode?: 'event-driven' | 'continuous';
    /**
     * Cascade depth cap for `$related.*` events under Kernel §4.10. Zero disables relationship-event expansion.
     */
    maxRelationshipEventDepth?: number;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
export type EmbeddedBlocksMUSTNOTDeclareTargetWorkflowADR006321 = {
  [k: string]: unknown;
};
export type EmbeddedBlocksMUSTNOTDeclareIndependentUrlOrVersionADR006321 = {
  [k: string]: unknown;
};
/**
 * Structured case data for instances of this workflow: either inline `fields` (FieldDeclaration map) or a pinned `contractRef` (Formspec Definition recommended). Mutually exclusive shapes per CaseFile oneOf.
 */
export type CaseFile = {
  /**
   * Inline field declarations for the case data shape. Each entry's key is the field name and value is a `FieldDeclaration` describing type and constraints. Use `fields` for self-contained workflows; use `contractRef` to reference an external contract (Formspec recommended).
   */
  fields?: {
    [k: string]: FieldDeclaration;
  };
  /**
   * URI reference to an external contract document defining the case data shape. Recommended binding is a Formspec Definition (per the canonical `contractHook` seam, ADR 0077 §10.2); JSON Schema is the baseline binding. Mutually exclusive with inline `fields`.
   */
  contractRef?: string;
  /**
   * Optional version string pin for the referenced contract. When omitted, processors resolve the latest published version of `contractRef`. Pinning is RECOMMENDED for case instances that must replay against archived semantics (Kernel §9.6).
   */
  contractVersion?: string;
  [k: string]: unknown;
} & {
  [k: string]: unknown;
};
export type State = {
  [k: string]: unknown;
} & ForEachStatesMUSTDeclareCollectionBodyLintKFOREACH001KFOREACH002 & {
    type: 'atomic' | 'compound' | 'parallel' | 'foreach' | 'final';
    tags?: string[];
    transitions?: Transition[];
    /**
     * Nested substates for compound states (`type=='compound'`). Map of substate identifier to State declaration. Compound states enter their declared `initial` substate; history states (Kernel §4.14) optionally restore the most recently active substate on re-entry.
     */
    states?: {
      [k: string]: State;
    };
    /**
     * Parallel regions for parallel states (`type=='parallel'`). Map of region identifier to a region object containing its own `initial` and `states`. All regions execute concurrently; the parallel state exits only when join semantics declared by `cancellationPolicy` are satisfied (Kernel §4.8).
     */
    regions?: {
      [k: string]: unknown;
    };
    /**
     * Ordered list of actions the processor MUST execute on state entry, before any transitions are evaluated. Action shape follows Kernel §9.2 action execution model (invokeService, startTimer, emitEvent, etc.). Actions execute in declaration order; the state is considered entered only after all onEntry actions succeed.
     */
    onEntry?: unknown[];
    /**
     * Ordered list of actions the processor MUST execute on state exit, after the outgoing transition has been selected but before the next state is entered. Same action shape as onEntry. Exit actions cannot abort the transition; they execute as side effects.
     */
    onExit?: unknown[];
    /**
     * ISO 8601 duration after which the processor emits a `$timeout.state` event if the state has not been exited. The lifecycle handles the timeout like any other event (Kernel §4.10). Hold policies (Governance §12) MAY override stateTimeout with policy-specific durations.
     */
    stateTimeout?: string;
    /**
     * Foreach states only (`type=='foreach'`). FEL expression yielding a bounded array. The processor evaluates the expression at state entry, instantiates `body` once per item, and aggregates per `mergeStrategy`. Per ADR 0078, the array MUST be bounded — unbounded collections are rejected.
     */
    collection?: string;
    /**
     * Foreach states only. Variable name bound to the current item within `body`. Defaults to `$item`. Referenced in body actions and guards as `$item.fieldName` or whatever name is declared.
     */
    itemVariable?: string;
    /**
     * Foreach states only. Variable name bound to the current item index (0-based) within `body`. Defaults to `$index`. Useful for ordered processing or correlation with parallel arrays.
     */
    indexVariable?: string;
    /**
     * Foreach states only. Maximum number of items processed concurrently. Positive integer for bounded concurrency; null for unbounded (processor decides). Zero is rejected (would deadlock; lint K-FOREACH-003 also enforces post-coercion). Processors MAY refuse unbounded concurrency on rights-impacting workflows.
     */
    concurrency?: number | null;
    /**
     * Foreach states only. FEL expression evaluated after each iteration; when true, terminates the foreach early. Useful for early-exit on first match or threshold reached.
     */
    breakCondition?: string;
    /**
     * Foreach states only. Case-file path where iteration results are written per `mergeStrategy`. Per ADR 0078, the write goes through the governed output-commit pipeline (ADR 0080) with `mutationSource: computed`.
     */
    outputPath?: string;
    mergeStrategy?: 'shallow' | 'deep' | 'collect';
    body?: State;
    /**
     * Identifier of the initial substate for compound states. MUST be a key in `states`. Required when `type=='compound'` (Kernel S4.3).
     */
    initialState?: string;
    /**
     * Final states only (`type=='final'`). Stable code identifying the workflow's terminal outcome. Recorded in Facts-tier provenance and consumed by reporting / case-closure pipelines. Distinct from `tags` (which compose) — outcomeCode is singular.
     */
    outcomeCode?: string;
    [k: string]: unknown;
  };
/**
 * Substrate adapter discriminator (ADR 0064). Selects which AgentInvoker implementation handles invocations of this agent at runtime. Each `kind` corresponds to one adapter crate (`wos-agent-anthropic`, `wos-agent-mcp`, `wos-agent-a2a`, `wos-agent-http`, `wos-agent-stub`, `wos-agent-sdk-claude`). Deployment binds the discriminator to a concrete adapter; the workflow stays substrate-portable.
 */
export type InvokerSpec = Anthropic | ClaudeAgentSdk | Mcp | A2A | Http | Stub;

export interface RightsImpactingAndSafetyImpactingWorkflowsMUSTEmbedGovernance {
  [k: string]: unknown;
}
export interface WorkflowsWhoseActorsIncludeAnyAgentTypedActorMUSTDeclareAgents {
  [k: string]: unknown;
}
export interface WorkflowsWithBothAgentsAndAdvancedFeaturesSHOULDDeclareAiOversight {
  [k: string]: unknown;
}
/**
 * Author-time field declaration in a contract intake binding (Kernel §9.1). Pairs a field name with its primitive type and optional documentation; the bound contract carries the semantic meaning.
 */
export interface FieldDeclaration {
  type: 'string' | 'number' | 'integer' | 'boolean' | 'array' | 'object' | 'date' | 'datetime';
  /**
   * When true, the field MUST be present and non-null at validation time. When omitted or false, the field is optional. Enforcement layer is the contract validator bound by `contractHook`.
   */
  required?: boolean;
  /**
   * Free-text description of the field's purpose, displayed to authoring tools and rendered into LLM-readable artifacts. Not interpreted by the processor; the field's semantic meaning lives in the bound contract.
   */
  description?: string;
  [k: string]: unknown;
}
/**
 * Public-intake form. References a Formspec definition. Validated intake is converted to caseFile via IntakeHandoff (ADR 0073).
 */
export interface IntakeReference {
  /**
   * URI reference to the Formspec Definition that defines the public-intake form. Validated intake responses are converted to `caseFile` via `IntakeHandoff` per ADR 0073. Required for any workflow that accepts public intake.
   */
  contractRef: string;
  /**
   * Optional version pin for the intake form contract. When omitted, processors resolve latest. Pinning is RECOMMENDED for SBA pilot deployments to keep production replay deterministic.
   */
  contractVersion?: string;
  mode?: 'workflowInitiated' | 'publicIntake';
  [k: string]: unknown;
}
export interface Actor {
  /**
   * Stable identifier for this actor within the workflow document. MUST be unique across actors[]. Cross-references include `Transition.actor` (who acts on the transition) and, when type=='agent', `agents[].id`. Identifier convention: camelCase or kebab-case strings; no whitespace.
   */
  id: string;
  /**
   * Actor classification. Canonical values are `human`, `system`, and `agent`; vendor-defined values MUST use an `x-` prefixed identifier via the `actorExtension` seam (ADR 0077).
   */
  type: (
    | ('human' | 'system' | 'agent')
    | {
        [k: string]: unknown;
      }
  ) &
    string;
  /**
   * Optional human-readable role label for documentation and notice rendering. Not interpreted by the processor; the actor identity for execution and authority decisions is `id`, not `role`.
   */
  role?: string;
  [k: string]: unknown;
}
/**
 * Author-time state machine: `initialState` plus a map of state identifiers to State declarations (atomic, compound, parallel, foreach, or final). Topology is immutable for a pinned (url, version); runtime instances follow this graph.
 */
export interface Lifecycle {
  /**
   * Map of state identifier to State declaration. Defines the workflow's complete topology: atomic states (one transition target per event), compound states (nested substates), parallel states (concurrent regions), foreach states (bounded iteration per ADR 0078), and final states.
   */
  states: {
    [k: string]: State;
  };
  /**
   * Identifier of the lifecycle's initial state — the state instances enter on creation. MUST match a key in `states`. Per Kernel §4.1, every workflow has exactly one initial state.
   */
  initialState: string;
  [k: string]: unknown;
}
export interface ForEachStatesMUSTDeclareCollectionBodyLintKFOREACH001KFOREACH002 {
  [k: string]: unknown;
}
export interface Transition {
  /**
   * Trigger event for this transition. When omitted, the transition is anonymous: it does not match an external event but still participates in continuous-mode guard re-scan (Runtime Companion §10.3).
   */
  event?:
    | TransitionEventTimer
    | TransitionEventMessage
    | TransitionEventSignal
    | TransitionEventCondition
    | TransitionEventError;
  /**
   * FEL expression evaluated before the transition fires. When the guard returns true, the transition is selected; when it returns false, the transition is skipped. When the guard throws or evaluates to a non-boolean, the processor MUST reject per Kernel §4.6/§4.7 transition resolution. Guards are stateless — they read case state but MUST NOT mutate it. The compiled FEL AST drives lint analysis (K-012 syntax, K-017 cross-case-state reference, K-019 function-set, AI-058 boolean shape).
   */
  guard?: string;
  tags?: string[];
  /**
   * Actor identifier responsible for performing this transition. MUST match an entry in the workflow's `actors[].id` and MUST use the same lexical pattern as `actors[].id` (ASCII letter first, then letters, digits, `.`, `_`, `-`). Single-actor transitions name one actor; multi-actor (signature-gated) transitions use the `actors` array (lint WOS-SIG-COVER-001 enforces signer coverage). Load-bearing for authority decisions and signature workflow correctness.
   */
  actor?: string;
  /**
   * Ordered list of actions the processor MUST execute as part of this transition, after guard evaluation and before destination state entry. Action shape per Kernel §9.2. Actions execute atomically with the state change — failure rolls back per Kernel §9.5 compensation.
   */
  actions?: unknown[];
  /**
   * Identifier of the destination state. MUST match a key in the enclosing lifecycle's states (or a substate when nested). The processor MUST reject transitions whose `target` does not resolve.
   */
  target: string;
  [k: string]: unknown;
}
/**
 * Typed transition event branch for durable timer correlation and synthesized $timeout.* runtime delivery (Kernel §4.5, §4.9.10). Authors pair timerId with startTimer actions and select source for the fixed timeout prefix family.
 */
export interface TransitionEventTimer {
  kind: 'timer';
  /**
   * Timer correlation identifier within the workflow instance (Kernel §9.2, §9.7). Paired with startTimer and cancelTimer actions. Together with source and optional firesAs it determines which process_event string the runtime delivers when the timer elapses; authors SHOULD reuse the same timerId on the matching startTimer action.
   */
  timerId: string;
  /**
   * Kernel timer category used when synthesizing the $timeout.* process_event family when firesAs is absent (Kernel §4.9.10). task, service, state, signal, and workflow map to fixed prefixes; custom covers author-specific timer identifiers including dotted names.
   */
  source: 'task' | 'service' | 'state' | 'signal' | 'workflow' | 'custom';
  /**
   * Optional relative ISO 8601 duration carried on timer-kind transition events for authoring parity with embedded timer shapes (Kernel §9.2). Mirrors startTimer duration when authors document the intended expiry window on the transition itself.
   */
  duration?: string;
  /**
   * Optional absolute deadline as RFC 3339 date-time for timer-kind transition events when modeling fixed clock firing instead of relative duration semantics alone (Kernel §9.2).
   */
  expiresAt?: string;
  /**
   * Exact process_event string emitted when this timer elapses, overriding default $timeout.* synthesis from timerId and source (Kernel §4.9.10). Use for dotted author timer names such as resubmitExpired instead of the synthesized prefix form.
   */
  firesAs?: string;
}
/**
 * Typed transition event branch for author-defined message names delivered through process_event (Kernel §4.5). Message names MUST NOT use a leading $; reserved kernel prefixes use timer, signal, or error branches instead.
 */
export interface TransitionEventMessage {
  kind: 'message';
  /**
   * Author-defined message event name for explicit process_event delivery (Kernel §4.5). MUST NOT begin with `$` because reserved kernel prefixes are modeled as other TransitionEvent kinds. Dots are permitted as an informal namespacing convention.
   */
  name: string;
  /**
   * Optional correlation key for matching async external callbacks to the originating workflow transition (Kernel §4.5, §9.4). Integration profiles surface this through CloudEvents attributes such as woscorrelationkey for callback routing and deduplication.
   */
  correlationKey?: string;
  /**
   * Optional opaque JSON payload carried with the message event for structured integration callbacks and author-defined event contracts (Kernel §4.5 companion). Omitted when producers supply only the event name and correlation metadata is unnecessary.
   */
  data?: {
    [k: string]: unknown;
  };
}
/**
 * Typed transition event branch for signal delivery including kernel sentinels such as $join (Kernel §4.8) and $compensation.complete (LCD §5.9), plus author-defined signal names.
 */
export interface TransitionEventSignal {
  kind: 'signal';
  /**
   * Signal name for lifecycle delivery, including kernel sentinels `$join` (Kernel §4.8) and `$compensation.complete` (LCD §5.9), plus author-defined identifiers. Unlike messages, leading `$` is permitted for kernel-reserved signal identifiers.
   */
  name: string;
  /**
   * Delivery scope for signal-kind transition events (Kernel §4.9.10). instance targets the current workflow instance; related targets correlated companion cases; broadcast fans out to subscribed instances according to binding-specific subscription rules.
   */
  scope: 'instance' | 'related' | 'broadcast';
}
/**
 * Typed transition event branch for continuous evaluation mode: FEL predicates that participate in post-mutation guard re-scan without an external process_event name (Kernel §12.3).
 */
export interface TransitionEventCondition {
  kind: 'condition';
  /**
   * FEL predicate evaluated during continuous evaluation after case-file mutation so the transition competes in guard re-scan ordering without matching an external event name (Kernel §12.3).
   */
  expression: string;
}
/**
 * Typed transition event branch for synthetic $error class dispatch: runtime process_event uses the literal $error while the typed code carries the discriminant (Kernel §4.5, §4.9.10).
 */
export interface TransitionEventError {
  kind: 'error';
  /**
   * Normative error code for synthetic `$error` class dispatch while the runtime boundary still receives the literal process_event name `$error` (Kernel §4.5, §4.9.10). Dot-separated codes align integration failures, contract violations, and processor faults.
   */
  code: string;
  /**
   * Optional JSON Pointer to the failing action when the runtime attaches structural context for diagnostics and recovery UX on error-kind transition events (Kernel §4.5). Omit when the error code alone suffices for routing and operator playbooks.
   */
  actionPath?: string;
}
/**
 * Named validation and capability contracts referenced by lifecycle transitions, output bindings, and the governed output-commit pipeline (ADR 0080). Contracts compose with the `contractHook` seam (ADR 0077 §10.2). Concrete shape varies by binding kind; see kernel/spec.md §9.2 for the merged contract surface.
 */
export interface Contracts {
  [k: string]: unknown;
}
/**
 * Governed output-commit pipeline projection. Per ADR 0080: source surface + contractRef + projection map + writeScope + mutationSource + verificationLevel. Validated mutations + Facts-tier provenance emit deterministically.
 */
export interface OutputBinding {
  /**
   * Source surface that triggers this binding. Identifier of a state, transition, capability, or signal whose completion projects mutations through the governed output-commit pipeline (ADR 0080). The binding fires when the source surface emits its terminal event.
   */
  on?: string;
  /**
   * URI of the contract that validates the projected mutation before commit. Per ADR 0080's six-surface pipeline, every binding MUST reference a contract; the validator gates the commit. Formspec contract recommended for case-data writes.
   */
  contractRef?: string;
  /**
   * Map of source-output keys to case-file field paths. Defines how the source surface's output projects into the case state. Concrete shape is binding-specific; for Formspec bindings, projection follows the Mapping spec.
   */
  projection?: {
    [k: string]: unknown;
  };
  writeScope?: string[];
  /**
   * Provenance origin of the projected mutation under the governed output-commit pipeline (ADR 0080). Recorded in Facts-tier provenance (Kernel §8); load-bearing for audit traceability and rights-impacting decision review. The closed-set values describe canonical provenance origins; vendor-namespaced `x-` values cover origins outside the canonical set.
   */
  mutationSource?:
    | ('agent-extracted' | 'system-fetched' | 'human-entered' | 'human-corrected' | 'computed' | 'self-attested')
    | string;
  /**
   * Strength of verification applied to the projected mutation under the governed output-commit pipeline (ADR 0080). Higher levels increase audit weight and enable stricter governance gates (e.g., `authoritative` defeats lower-tier challenges in ADR 0066 amendment/supersession evaluation). The closed-set values describe canonical verification regimes; vendor-namespaced `x-` values cover bespoke regimes (e.g., FHE-attested, dual-control). Lint WOS-VER-LEVEL-001 warns when `agents[].fallbackChain` is declared without any `verificationLevel` on the workflow.
   */
  verificationLevel?: ('independent' | 'attested' | 'corroborated' | 'authoritative') | string;
  [k: string]: unknown;
}
export interface ProvenanceConfig {
  /**
   * Minimum provenance tier emitted. Facts is kernel default. Higher tiers attach via provenanceLayer seam (ADR 0077).
   */
  tier?: 'facts' | 'reasoning' | 'counterfactual' | 'narrative' | 'full';
  [k: string]: unknown;
}
/**
 * Embedded Layer-1 governance (due process, review protocols, validation pipelines, policy parameters) inside the author-time workflow envelope. Required for rights-impacting and safety-impacting impactLevel per kernel and ADR 0076 D-2.
 */
export interface Governance {
  /**
   * Due-process policy block covering notice, explanation, appeal, counterfactual, and continuation-of-services requirements.
   */
  dueProcess?: {
    [k: string]: unknown;
  };
  /**
   * Review protocol declarations describing independence, sampling, sequencing, and scope for governed review tasks.
   */
  reviewProtocols?: unknown[];
  /**
   * Governance pipeline declarations that define named stages and assertions used to evaluate controlled decisions.
   */
  pipelines?: unknown[];
  /**
   * Governance task catalog describing review, notice, escalation, and remediation tasks available to the workflow.
   */
  taskCatalog?: unknown[];
  /**
   * Delegation policy block defining who may delegate authority, who may receive it, and what scope limits apply.
   */
  delegation?: {
    [k: string]: unknown;
  };
  /**
   * Hold policy block describing allowed hold types, resume triggers, timeout behavior, and tagged lifecycle states.
   */
  holds?: {
    [k: string]: unknown;
  };
  /**
   * Named policy-parameter values resolved by governance rules, notices, timers, and runtime policy checks.
   */
  policyParameters?: {
    [k: string]: unknown;
  };
  /**
   * Ordered escalation levels used by timers, holds, review protocols, and unresolved governance work.
   */
  escalationLevels?: unknown[];
  /**
   * Five-mode amendment taxonomy declared by this workflow's governance, per ADR-0066 D-1 + Q26 maximalist closed-five position. Closed enum -- vendor extensions are deliberately not permitted at this key so the lint that pairs each declared mode with its authorizing-act record kind (correctionAuthorized, amendmentAuthorized, rescissionAuthorized, reinstated; supersession is governed at the WOS/kernel layer per kernel spec caseRelationships (S5.5), not as a property on this workflow document) stays exhaustive. Authoring this enum makes the lint cheaper to land in follow-up work; absence here means the workflow asserts no amendments are permitted.
   */
  amendmentTaxonomy?: ('correction' | 'amendment' | 'supersession' | 'rescission' | 'reinstatement')[];
  [k: string]: unknown;
}
/**
 * Was wos-ai-integration.schema.json AgentDeclaration plus wos-agent-config.schema.json plus wos-drift-monitor.schema.json. Inlined per ADR 0076.
 */
export interface AgentDeclaration {
  /**
   * Stable agent identifier referenced by workflow actors, invoker bindings, provenance records, and governance rules.
   */
  id: string;
  /**
   * Provider or deployment model identifier used for this agent, recorded so invocations and provenance can be tied to a concrete model family.
   */
  modelIdentifier?: string;
  /**
   * Provider or deployment model version used for this agent, recorded so behavior can be audited across upgrades and recalibrations.
   */
  modelVersion?: string;
  modelVersionPolicy?: 'pinned' | 'minor-allowed' | 'major-allowed';
  autonomy?: 'readOnly' | 'assistive' | 'supervised' | 'autonomous';
  deonticConstraints?: {
    kind: 'permission' | 'prohibition' | 'obligation' | 'right';
    /**
     * FEL expression evaluated against the invocation context to decide whether this deontic constraint applies to the agent output or action.
     */
    expression: string;
    [k: string]: unknown;
  }[];
  /**
   * Minimum calibrated confidence the agent must meet before its output may be used at the configured autonomy level.
   */
  confidenceFloor?: number;
  /**
   * Policy describing how an agent confidence score decays over time or across drift signals before recalibration or human review is required.
   */
  confidenceDecay?: {
    [k: string]: unknown;
  };
  fallbackChain?: string[];
  /**
   * Capabilities this agent may perform, such as extraction, classification, drafting, or tool invocation; runtime policy evaluates requests against this list.
   */
  capabilities?: unknown[];
  /**
   * Agent-specific drift monitoring configuration, including observed signals and the governance response when drift is detected.
   */
  driftMonitoring?: {
    [k: string]: unknown;
  };
  invoker?: InvokerSpec;
  [k: string]: unknown;
}
export interface Anthropic {
  kind: 'anthropic';
  /**
   * Anthropic model identifier used for the invocation, recorded so behavior can be audited by model family and release.
   */
  model: string;
  /**
   * Optional Anthropic adapter configuration reference resolved by deployment tooling before invoking the selected model.
   */
  configRef?: string;
}
export interface ClaudeAgentSdk {
  kind: 'claudeAgentSdk';
  /**
   * Claude Agent SDK configuration reference resolved by deployment tooling before starting the agent session.
   */
  configRef: string;
}
export interface Mcp {
  kind: 'mcp';
  /**
   * MCP server identifier resolved at deployment time before dispatching the configured tool invocation.
   */
  server: string;
  /**
   * Tool name on the selected MCP server that the agent is allowed to call for this capability.
   */
  tool: string;
}
export interface A2A {
  kind: 'a2a';
  /**
   * External orchestrator identifier resolved at deployment time before dispatching the agent capability request.
   */
  orchestrator: string;
}
export interface Http {
  kind: 'http';
  /**
   * HTTP endpoint URI used by the invoker when dispatching the agent capability request over HTTP.
   */
  endpoint: string;
  /**
   * Optional URI to OpenAPI / JSON Schema describing the contract.
   */
  schemaRef?: string;
}
/**
 * Deterministic in-memory stub used by conformance fixtures (`wos-agent-stub`).
 */
export interface Stub {
  kind: 'stub';
  /**
   * Canned responses streamed in declaration order per (capability_id, invocation_index).
   */
  responses?: {
    /**
     * Capability id this response satisfies. When omitted, matches any capability.
     */
    capabilityId?: string;
    /**
     * Output payload returned by the invoker.
     */
    output: {
      [k: string]: unknown;
    };
    /**
     * Confidence score returned with the stubbed agent response; omitted values default to full confidence in tests.
     */
    confidence?: number;
    /**
     * Citation array returned with the stubbed agent response and copied into invocation output for tests.
     */
    citations?: unknown[];
  }[];
}
/**
 * Cross-cutting AI oversight embedded in the workflow envelope: disclosure posture, drift detection, narrative tier handling, volume constraints. Pairs with the agents array (ADR 0076).
 */
export interface AIOversight {
  /**
   * Disclosure policy for AI assistance in the workflow, including when people must be told that an agent contributed to a task, recommendation, or determination.
   */
  disclosure?: {
    [k: string]: unknown;
  };
  /**
   * Workflow-level drift detection settings for AI agents, including monitoring cadence, recalibration triggers, and demotion behavior when model quality changes.
   */
  driftDetection?: {
    [k: string]: unknown;
  };
  /**
   * Workflow-level throughput limits for autonomous or assisted AI work, used to cap volume and force human review when operating limits are exceeded.
   */
  volumeConstraints?: {
    [k: string]: unknown;
  };
  /**
   * Narrative authority tier for AI-generated explanations, distinguishing assistive narrative from authoritative reasoning used in rights-impacting decisions.
   */
  narrativeTier?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Embedded DocuSign-tier signature profile (roles, documents, signingFlow, evidence) inside the author-time envelope. Required when transitions gate on kind signature (lint WOS-SIG-COVER-001).
 */
export interface Signature {
  /**
   * Optional JSON Schema URI annotation for the embedded signature block; workflow identity remains on the enclosing envelope.
   */
  $schema?: string;
  /**
   * Optional human-readable note describing the embedded signature flow. Identity (url, version) is governed by the enclosing $wosWorkflow envelope per ADR 0063 §2.1; legacy `targetWorkflow` / `version` / `title` properties are retired.
   */
  description?: string;
  /**
   * Signature role declarations binding signing roles to kernel actors.
   *
   * @minItems 1
   */
  roles: [
    {
      /**
       * Stable signing-role identifier referenced by signing steps, completion rules, and audit evidence.
       */
      id: string;
      /**
       * Human-readable role label shown to signers and recorded in signature audit evidence.
       */
      role: string;
      /**
       * Workflow actor identifier bound to this signing role when the role is assigned to a specific actor.
       */
      actorId: string;
      /**
       * Whether this signing role is required before the signature flow can reach completion.
       */
      required?: boolean;
      /**
       * Authentication-policy key that this signing role must satisfy before completing a signature step.
       */
      authenticationPolicyKey?: string;
      /**
       * Human-readable description of the signing role and its responsibility in the signature flow.
       */
      description?: string;
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^x-".
       */
      [k: string]: unknown;
    },
    ...{
      /**
       * Stable signing-role identifier referenced by signing steps, completion rules, and audit evidence.
       */
      id: string;
      /**
       * Human-readable role label shown to signers and recorded in signature audit evidence.
       */
      role: string;
      /**
       * Workflow actor identifier bound to this signing role when the role is assigned to a specific actor.
       */
      actorId: string;
      /**
       * Whether this signing role is required before the signature flow can reach completion.
       */
      required?: boolean;
      /**
       * Authentication-policy key that this signing role must satisfy before completing a signature step.
       */
      authenticationPolicyKey?: string;
      /**
       * Human-readable description of the signing role and its responsibility in the signature flow.
       */
      description?: string;
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^x-".
       */
      [k: string]: unknown;
    }[],
  ];
  /**
   * Signable document declarations.
   *
   * @minItems 1
   */
  documents: [
    {
      /**
       * Stable signable-document identifier referenced by signing steps, evidence records, and custody bindings.
       */
      id: string;
      /**
       * Reference to the signable document artifact that the signer is affirming.
       */
      documentRef: string;
      /**
       * Digest value for the signable document, computed with documentHashAlgorithm and bound into signature evidence.
       */
      documentHash: string;
      /**
       * Hash algorithm used to compute documentHash for this signable document. Core admits sha-256; vendor algorithms must use the x-* extension namespace.
       */
      documentHashAlgorithm: 'sha-256' | string;
      /**
       * Reference to the rendering artifact or template used to produce the signable document view.
       */
      renderingRef?: string;
      /**
       * Reference to the Formspec response whose rendered content or data is bound into the signable document.
       */
      formspecResponseRef?: string;
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^x-".
       */
      [k: string]: unknown;
    },
    ...{
      /**
       * Stable signable-document identifier referenced by signing steps, evidence records, and custody bindings.
       */
      id: string;
      /**
       * Reference to the signable document artifact that the signer is affirming.
       */
      documentRef: string;
      /**
       * Digest value for the signable document, computed with documentHashAlgorithm and bound into signature evidence.
       */
      documentHash: string;
      /**
       * Hash algorithm used to compute documentHash for this signable document. Core admits sha-256; vendor algorithms must use the x-* extension namespace.
       */
      documentHashAlgorithm: 'sha-256' | string;
      /**
       * Reference to the rendering artifact or template used to produce the signable document view.
       */
      renderingRef?: string;
      /**
       * Reference to the Formspec response whose rendered content or data is bound into the signable document.
       */
      formspecResponseRef?: string;
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^x-".
       */
      [k: string]: unknown;
    }[],
  ];
  /**
   * Signing flow declaration: sequential, parallel, routed, or free-for-all.
   */
  signingFlow: {
    type: 'sequential' | 'parallel' | 'routed' | 'free-for-all';
    /**
     * @minItems 1
     */
    steps: [
      {
        /**
         * Stable signing-step identifier referenced by dependencies, decline paths, expiry paths, and evidence records.
         */
        id: string;
        /**
         * Signing-role identifier responsible for completing this signing step.
         */
        roleId: string;
        /**
         * Signable-document identifier this signing step asks the signer to affirm.
         */
        documentId: string;
        /**
         * FEL guard expression evaluated to decide whether this routed signing step is required for the case.
         */
        guard?: string;
        dependsOn?: string[];
        /**
         * Whether this signing step is required when its guard and dependencies are satisfied.
         */
        required?: boolean;
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^x-".
         */
        [k: string]: unknown;
      },
      ...{
        /**
         * Stable signing-step identifier referenced by dependencies, decline paths, expiry paths, and evidence records.
         */
        id: string;
        /**
         * Signing-role identifier responsible for completing this signing step.
         */
        roleId: string;
        /**
         * Signable-document identifier this signing step asks the signer to affirm.
         */
        documentId: string;
        /**
         * FEL guard expression evaluated to decide whether this routed signing step is required for the case.
         */
        guard?: string;
        dependsOn?: string[];
        /**
         * Whether this signing step is required when its guard and dependencies are satisfied.
         */
        required?: boolean;
        /**
         * This interface was referenced by `undefined`'s JSON-Schema definition
         * via the `patternProperty` "^x-".
         */
        [k: string]: unknown;
      }[],
    ];
    completion?: {
      /**
       * Completion rule type that determines whether all required signatures, any required signature, a counted threshold, or a named role set is required. Canonical values are 'all-required', 'any-required', 'count', and 'role-set'.
       */
      type: 'all-required' | 'any-required' | 'count' | 'role-set';
      /**
       * Number of completed signatures required when the completion rule uses a count-based threshold.
       */
      count?: number;
      roleIds?: string[];
    };
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * Signature evidence requirements emitted into SignatureAffirmation provenance.
   */
  evidence: {
    /**
     * Record-kind discriminator for signature affirmation evidence emitted by the signature runtime.
     */
    recordKind: 'signatureAffirmation';
    requiredFields: string[];
    consentReference: {
      /**
       * Reference to the exact consent text shown to the signer before affirmation.
       */
      consentTextRef: string;
      /**
       * Version identifier for the consent text shown to the signer before affirmation.
       */
      consentVersion: string;
      /**
       * JSON path or case-file path where the signer acceptance timestamp is recorded for consent evidence.
       */
      acceptedAtPath: string;
      /**
       * JSON path or case-file path where the signer affirmation value is recorded for consent evidence.
       */
      affirmationPath: string;
    };
    identityBinding: {
      /**
       * Canonical authentication method recorded in signature evidence, or an x-* vendor token.
       */
      method:
        | (
            | 'none'
            | 'email-otp'
            | 'sms-otp'
            | 'knowledge-based'
            | 'oidc'
            | 'webauthn'
            | 'credential'
            | 'in-person'
            | 'notary'
          )
        | string;
      /**
       * Identity-assurance level for the signer binding. Accepts NIST-style `ial1`–`ial3` / `aal1`–`aal3`, ranked `low`–`very-high`, or vendor `x-*` tokens.
       */
      assuranceLevel:
        | ('ial1' | 'ial2' | 'ial3' | 'aal1' | 'aal2' | 'aal3')
        | ('low' | 'standard' | 'high' | 'very-high')
        | string;
      /**
       * Identity provider or credential service reference recorded with the signer identity binding.
       */
      providerRef?: string;
      /**
       * Reference to an external identity attestation that supports the signer identity binding.
       */
      externalAttestationRef?: string;
    };
    /**
     * Whether signature evidence produced under this profile is eligible for custody-hook anchoring.
     */
    custodyHookEligible: boolean;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^x-".
     */
    [k: string]: unknown;
  };
  /**
   * Authentication policy declarations referenced by role.authenticationPolicyKey.
   */
  authenticationPolicies?: {
    /**
     * Stable authentication-policy key referenced by signature roles and signing steps.
     */
    key: string;
    /**
     * Canonical authentication method required by this policy, or an x-* vendor token.
     */
    method:
      | (
          | 'none'
          | 'email-otp'
          | 'sms-otp'
          | 'knowledge-based'
          | 'oidc'
          | 'webauthn'
          | 'credential'
          | 'in-person'
          | 'notary'
        )
      | string;
    /**
     * Required identity-assurance level before a signer may affirm. Same union as `evidence.identityBinding.assuranceLevel`: IAL/AAL, ranked labels, or `x-*` vendor tokens.
     */
    assuranceLevel:
      | ('ial1' | 'ial2' | 'ial3' | 'aal1' | 'aal2' | 'aal3')
      | ('low' | 'standard' | 'high' | 'very-high')
      | string;
    /**
     * Reference to the identity provider, notary system, or credential service used to satisfy this authentication policy.
     */
    providerRef?: string;
    /**
     * Whether the authentication policy requires in-person verification before the signer may complete the step.
     */
    requiresInPerson?: boolean;
    /**
     * Whether the signer must produce credential evidence before the authentication policy is considered satisfied.
     */
    requiresCredentialEvidence?: boolean;
  }[];
  /**
   * Reminder policy emitting timer-driven events while signing is pending.
   */
  reminders?: {
    /**
     * Runtime event name emitted when a signature reminder is due under this reminder policy.
     */
    eventName: string;
    /**
     * ISO 8601 durations relative to signing-flow start.
     */
    schedule: string[];
    /**
     * Notification template key used to render signature reminder notices.
     */
    templateKey?: string;
  };
  expiryPolicy?: {
    /**
     * Runtime event name emitted when a signature request reaches its configured expiry deadline.
     */
    eventName: string;
    /**
     * ISO-8601 duration after which an incomplete signature request expires and follows the expiry path.
     */
    after: string;
    /**
     * Transition identifier fired when a signature request expires and the workflow follows the expiry path.
     */
    transitionId?: string;
  };
  declinePolicy?: {
    /**
     * Transition identifier fired when a signer declines and the signature workflow follows the decline path.
     */
    transitionId: string;
    /**
     * Whether a signer must provide a structured reason when declining a requested signature step.
     */
    reasonRequired?: boolean;
  };
  reassignmentPolicy?: {
    authorizedActorIds: string[];
    /**
     * Accountability mode recorded when a pending signature task is reassigned to another authorized actor.
     */
    accountability: string;
    /**
     * Whether a structured reason is required before a pending signature task may be reassigned.
     */
    reasonRequired?: boolean;
  };
  /**
   * Audit certificate emission policy. Captures what the certificate carries when issued.
   */
  auditCertificate?: {
    /**
     * Audit certificate format emitted when signature evidence is summarized for downstream verification or export.
     */
    format?: string;
    /**
     * Whether generated signature audit certificates include actor identifiers, roles, and authentication context.
     */
    includeActorMetadata?: boolean;
    /**
     * Whether generated signature audit certificates include references to supporting evidence and custody records.
     */
    includeEvidenceLinks?: boolean;
    /**
     * Signing mode summarized in the audit certificate, using the existing signing-flow type values.
     */
    signingMode?: 'sequential' | 'parallel' | 'routed' | 'free-for-all';
  };
  /**
   * Void policy declaring who may void the signing flow and whether a reason is required.
   */
  voidPolicy?: {
    authorizedActorIds: string[];
    /**
     * Whether a structured reason is required before the signature package may be voided.
     */
    reasonRequired?: boolean;
  };
  /**
   * This interface was referenced by `Signature`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: unknown;
}
/**
 * Embedded Trellis custody binding (trust profile, anchor requirements) for workflows that claim anchoring on transitions or signature events.
 */
export interface Custody {
  /**
   * URI reference to the Trellis trust profile governing custody anchors, evidence binding, and verification expectations.
   */
  trustProfileRef?: string;
  /**
   * Per-transition or per-event anchoring rules.
   */
  anchorRequirements?: {
    /**
     * Lifecycle event or custody milestone that triggers anchoring of the specified workflow evidence into the named ledger.
     */
    on: string;
    anchor: 'required' | 'optional' | 'deferred';
    /**
     * Trellis ledger identifier that receives the custody anchor for this requirement when the trigger condition occurs.
     */
    trellisLedger?: string;
    [k: string]: unknown;
  }[];
  /**
   * URI reference to the export bundle profile that defines how workflow evidence is packaged for external custody transfer.
   */
  exportBundleRef?: string;
  [k: string]: unknown;
}
/**
 * Optional. Constraint zones (DCR), equity guardrails, SMT verifiable constraints, multi-step session config, circuit breakers. Was wos-advanced.schema.json plus wos-equity.schema.json plus wos-verification-report.schema.json (author-time half).
 */
export interface Advanced {
  /**
   * Named constraint zones that group states, actors, tools, or transitions under shared runtime restrictions and governance checks.
   */
  constraintZones?: unknown[];
  /**
   * Equity guardrail configuration used to evaluate outcome predicates, cohort checks, and remediation requirements before governed actions proceed.
   */
  equityGuardrails?: {
    [k: string]: unknown;
  };
  /**
   * Verifiable constraint declarations that bind governed workflow behavior to machine-checkable evidence, proofs, or runtime attestations.
   */
  verifiableConstraints?: unknown[];
  /**
   * Circuit-breaker policy for stopping or degrading workflow automation when configured risk, error-rate, or external-dependency thresholds are crossed.
   */
  circuitBreaker?: {
    [k: string]: unknown;
  };
  /**
   * Shadow-mode configuration for evaluating a policy or automation path without making it authoritative for the live workflow outcome.
   */
  shadowMode?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Optional. Assurance level declaration, attestation, subject continuity. Was wos-assurance.schema.json.
 */
export interface Assurance {
  level?: 'baseline' | 'elevated' | 'high';
  /**
   * Assurance attestation policy describing what evidence must exist before an identity, authority, or continuity claim is accepted.
   */
  attestation?: {
    [k: string]: unknown;
  };
  /**
   * Subject-continuity rules that bind a person, actor, or case subject across identity events and assurance upgrades.
   */
  subjectContinuity?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
