/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Workflow Governance Document per the WOS Workflow Governance Specification v1.0 (Layer 1). Targets a WOS Kernel Document and declares due process requirements, review protocols, data validation pipelines with assertion gates, structured audit (Reasoning and Counterfactual tiers), quality controls (review sampling, separation of duties, override authority), rejection and remediation policies, task catalog with verifiability matrix, delegation of authority, and typed hold policies. Layer 1 exists because human workflows need it -- due process, review protocols, and data validation predate AI. WOS MUST NOT alter core Formspec processing semantics.
 */
export interface WOSWorkflowGovernanceDocument {
  /**
   * WOS Workflow Governance specification version. MUST be '1.0'. Identifies this document as a WOS Workflow Governance Document.
   */
  $wosWorkflowGovernance: '1.0';
  /**
   * Optional JSON Schema URI for editor validation and autocompletion.
   */
  $schema?: string;
  /**
   * URI of the WOS Kernel Document this governance document targets. MUST match the url property of the target Kernel Document (Governance S14).
   */
  targetWorkflow: string;
  /**
   * Version of this Workflow Governance Document.
   */
  version?: string;
  /**
   * Human-readable name for this governance configuration.
   */
  title?: string;
  /**
   * Human-readable description of the governance requirements.
   */
  description?: string;
  dueProcess?: DueProcess;
  /**
   * Review protocol bindings declaring which protocols apply to which transition tags (Governance S4).
   */
  reviewProtocols?: ReviewProtocolBinding[];
  /**
   * Data validation pipelines for staged processing with assertion gates (Governance S5).
   */
  pipelines?: Pipeline[];
  audit?: AuditConfig;
  qualityControls?: QualityControls;
  /**
   * Task patterns with verifiability classification (Governance S9).
   */
  taskCatalog?: TaskPattern[];
  /**
   * Delegation of authority declarations (Governance S11). Defines who is authorized to make specific types of determinations. Attaches via lifecycleHook on determination-tagged transitions.
   */
  delegations?: Delegation[];
  /**
   * Maximum sub-delegation chain levels (Governance S11.5). 1 (default): direct delegation only, no sub-delegation. 2: one level of sub-delegation allowed. 0: delegation enforcement disabled entirely.
   */
  maxDelegationDepth?: number;
  /**
   * Typed hold policies for case suspension (Governance S12). Attach via lifecycleHook on hold-tagged states.
   */
  holdPolicies?: HoldPolicy[];
  /**
   * Schema upgrade lifecycle operation (S2.9).
   */
  schemaUpgrade?: {
    priorVersion: string;
    newVersion: string;
    migrationMechanism: 'formspec-changelog' | 'custom-map' | 'declared-equivalence';
    scope: 'instance' | 'workflow' | 'tenant';
    [k: string]: unknown;
  };
  /**
   * Extension data. All keys MUST be prefixed with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
/**
 * Due process requirements for adverse decisions (Governance S3). Normative for workflows with rights-impacting or safety-impacting impact level.
 */
export interface DueProcess {
  /**
   * FEL expression that determines when this due process policy applies (Runtime Companion S8.2). Evaluated against the evaluation context. When absent, the policy applies unconditionally.
   */
  scope?: string;
  adverseDecisionPolicy?: AdverseDecisionPolicy;
}
/**
 * Policy governing adverse decisions: denial, reduction, termination, or other unfavorable determinations.
 */
export interface AdverseDecisionPolicy {
  /**
   * When true, affected individuals MUST receive notice before an adverse decision takes effect (Governance S3.2). The notice MUST include: the specific determination, individualized factual basis, appeal rights, and (if Layer 2 active) AI assistance disclosure.
   */
  noticeRequired?: boolean;
  /**
   * When notice is delivered relative to the adverse decision taking effect.
   */
  noticeTiming?: 'beforeEffective' | 'onEffective' | 'afterEffective';
  /**
   * ISO 8601 duration defining the minimum delay between notice delivery and the decision taking effect. Only meaningful when noticeTiming is 'beforeEffective'.
   */
  noticeGracePeriod?: string;
  /**
   * Reference to a Notification Template sidecar for notice formatting.
   */
  noticeTemplateRef?: string;
  /**
   * Level of explanation provided with adverse decisions (Governance S3.3). 'individualized': REQUIRED for rights-impacting. 'categorical': RECOMMENDED for operational. 'aggregate': minimum for informational.
   */
  explanationLevel?: 'individualized' | 'categorical' | 'aggregate';
  /**
   * When true, adverse decision explanations MUST include positive and negative counterfactuals (Governance S3.4). REQUIRED when impactLevel is 'rights-impacting'.
   */
  counterfactualRequired?: boolean;
  appealMechanism?: AppealMechanism;
}
/**
 * Appeal mechanism configuration (Governance S3.5).
 */
export interface AppealMechanism {
  /**
   * When true, an appeal pathway is available for adverse decisions.
   */
  enabled?: boolean;
  /**
   * ISO 8601 duration for the appeal filing window.
   */
  appealWindow?: string;
  /**
   * Constraint on appeal reviewers. MUST be independent of the original determination (Governance S3.5).
   */
  reviewerConstraint?: string;
  /**
   * Roles eligible to review appeals.
   */
  reviewerRoles?: string[];
  /**
   * When true, the workflow MUST maintain current service levels during the appeal window (Governance S3.6).
   */
  continuationOfServices?: boolean;
  /**
   * Scope of service continuation during appeal.
   */
  continuationScope?: string;
}
export interface ReviewProtocolBinding {
  /**
   * Semantic transition tags this protocol binding matches (Governance S4.3). Matches any transition or state in the kernel that carries any of these tags.
   *
   * @minItems 1
   */
  tags: [string, ...string[]];
  /**
   * Review protocols to apply (Governance S4.1). Multiple protocols MAY be combined.
   *
   * @minItems 1
   */
  protocols: [
    'independentFirst' | 'considerOpposite' | 'calibratedConfidence' | 'dualBlind' | 'unassisted',
    ...('independentFirst' | 'considerOpposite' | 'calibratedConfidence' | 'dualBlind' | 'unassisted')[],
  ];
  /**
   * Optional: target a specific transition by identifier instead of by tag. Overrides tag-based matching for this binding.
   */
  transitionOverride?: string;
  /**
   * FEL expression that determines when this protocol binding applies (Runtime Companion S8.2). Evaluated against the evaluation context. When absent, the binding applies to all matching tagged transitions.
   */
  scope?: string;
  /**
   * Human-readable explanation of why this protocol combination was chosen.
   */
  description?: string;
}
export interface Pipeline {
  /**
   * Unique pipeline identifier.
   */
  id: string;
  /**
   * Ordered processing stages. Each stage's output is validated before the next stage executes.
   *
   * @minItems 1
   */
  stages: [PipelineStage, ...PipelineStage[]];
  /**
   * Human-readable pipeline description.
   */
  description?: string;
}
export interface PipelineStage {
  /**
   * Unique stage identifier within this pipeline.
   */
  id: string;
  /**
   * Stage type (Governance S5.3). 'contract-validation': validate against a contract. 'assertion-gate': apply assertion checks. 'transform': apply data transformation. 'human-review': route to human.
   */
  type: 'contract-validation' | 'assertion-gate' | 'transform' | 'human-review';
  /**
   * Reference to a contract for validation. Used with contract-validation type.
   */
  contractRef?: string;
  /**
   * Assertion checks for assertion-gate stages.
   */
  assertions?: Assertion[];
  /**
   * What happens when this stage fails (Governance S8.1).
   */
  rejectionPolicy?: 'retryWithCorrections' | 'escalateToSupervisor' | 'holdPendingData' | 'failWithExplanation';
  /**
   * Human-readable stage description.
   */
  description?: string;
  /**
   * Extension data for this stage.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface Assertion {
  /**
   * Assertion gate type (Governance S5.4).
   */
  type: 'source-grounded' | 'arithmetic' | 'range' | 'consistency' | 'format' | 'cross-document' | 'temporal';
  /**
   * Human-readable description of what this assertion checks.
   */
  description?: string;
  /**
   * FEL expression defining the assertion constraint. Evaluated in the pipeline's data context.
   */
  expression?: string;
  /**
   * Fields subject to this assertion. Used with source-grounded and consistency types.
   */
  fields?: string[];
  /**
   * Reference to a prior pipeline stage for consistency checking.
   */
  referenceStage?: string;
  /**
   * Override rejection policy for this specific assertion.
   */
  rejectionPolicy?: 'retryWithCorrections' | 'escalateToSupervisor' | 'holdPendingData' | 'failWithExplanation';
}
/**
 * Structured audit configuration for Reasoning and Counterfactual tiers (Governance S6).
 */
export interface AuditConfig {
  reasoningTier?: ReasoningTierConfig;
  counterfactualTier?: CounterfactualTierConfig;
}
/**
 * Reasoning tier configuration (Governance S6.2). Attach to transitions tagged 'determination'.
 */
export interface ReasoningTierConfig {
  /**
   * Transition tags that require Reasoning tier records.
   */
  requiredForTags?: string[];
  /**
   * When true, Reasoning tier records MUST include decision requirements declarations.
   */
  requireDecisionRequirements?: boolean;
}
/**
 * Counterfactual tier configuration (Governance S6.4). Attach to transitions tagged 'adverse-decision' in rights-impacting workflows.
 */
export interface CounterfactualTierConfig {
  /**
   * Transition tags that require Counterfactual tier records.
   */
  requiredForTags?: string[];
  /**
   * When true, negative counterfactuals MUST explicitly address protected characteristics.
   */
  requireProtectedCharacteristics?: boolean;
}
/**
 * Quality control configuration: review sampling, separation of duties, override authority (Governance S7).
 */
export interface QualityControls {
  reviewSampling?: ReviewSampling;
  separationOfDuties?: SeparationOfDuties;
  overrideAuthority?: OverrideAuthority;
}
/**
 * Review sampling configuration (Governance S7.1).
 */
export interface ReviewSampling {
  /**
   * Fraction of decisions to sample for quality review (Governance S7.1). 0.1 means 10% of decisions are reviewed.
   */
  rate: number;
  /**
   * Sampling method.
   */
  method?: 'random' | 'stratified';
  /**
   * Sampling scope: per-workflow or per-actor.
   */
  scope?: 'workflow' | 'actor';
}
/**
 * Separation of duties rules (Governance S7.2).
 */
export interface SeparationOfDuties {
  /**
   * Scope of separation (Governance S7.2). 'sameInstance': reviewer != decision-maker within the same workflow instance. 'global': reviewer != decision-maker across all instances.
   */
  scope: 'sameInstance' | 'global';
  /**
   * Roles excluded from reviewing their own category of work.
   */
  excludeRoles?: string[];
}
/**
 * Override authority requirements (Governance S7.3).
 */
export interface OverrideAuthority {
  /**
   * When true, overrides MUST include structured rationale (Governance S7.3).
   */
  requireStructuredRationale?: boolean;
  /**
   * When true, the processor MUST verify the overriding actor has override authority.
   */
  requireAuthorityVerification?: boolean;
  /**
   * When true, overrides MUST reference supporting evidence.
   */
  requireSupportingEvidence?: boolean;
}
export interface TaskPattern {
  /**
   * Task pattern name.
   */
  pattern: string;
  /**
   * Whether the task's output can be independently verified (Governance S9.1).
   */
  verifiable: 'yes' | 'partially' | 'no';
  /**
   * How verification is performed, if verifiable.
   */
  verificationMethod?: string;
  /**
   * Human-readable description of this task pattern.
   */
  description?: string;
}
export interface Delegation {
  /**
   * Unique delegation identifier.
   */
  id: string;
  /**
   * Actor reference of the authority granting the delegation.
   */
  delegator: string;
  /**
   * Actor reference receiving the delegated authority.
   */
  delegate: string;
  scope: DelegationScope;
  /**
   * Type of authority delegated (Governance S11.2). 'signing': authority to sign official determinations. 'determination': authority to make case decisions. 'review': authority to review others' work. 'override': authority to override prior determinations.
   */
  authority: 'signing' | 'determination' | 'review' | 'override';
  /**
   * Reference to the legal delegation order, memorandum, or statutory citation.
   */
  legalInstrument?: string;
  /**
   * Date the delegation becomes active.
   */
  effectiveDate?: string;
  /**
   * Date the delegation expires.
   */
  expirationDate?: string;
  /**
   * Whether the delegation can be revoked.
   */
  revocable?: boolean;
  /**
   * Date the delegation was revoked, if applicable.
   */
  revokedDate?: string;
  /**
   * Whether this delegation permits the delegate to further sub-delegate authority (Governance S11.5). Default: false.
   */
  allowsSubDelegation?: boolean;
  /**
   * Minimum distinct authorities required for delegation to take effect (S4.9). Omit for single-authority delegation.
   */
  quorumCount?: number;
  /**
   * Eligible authority principal IDs (S4.9). Required when quorumCount is set.
   */
  quorumPool?: string[];
}
/**
 * Limits on the delegated authority.
 */
export interface DelegationScope {
  /**
   * Impact levels this delegation covers.
   */
  impactLevels?: ('rights-impacting' | 'safety-impacting' | 'operational' | 'informational')[];
  /**
   * Case types this delegation covers.
   */
  caseTypes?: string[];
  /**
   * Maximum dollar value for determinations under this delegation.
   */
  maxDollarThreshold?: number;
  /**
   * Additional FEL expression narrowing the delegation scope.
   */
  conditions?: string;
}
export interface HoldPolicy {
  /**
   * Reason for the hold. Standard values: pending-applicant-response, pending-external-verification, pending-legal-review, pending-legislation, pending-related-case, voluntary-hold, legal-hold. Extensible via x- prefixed values. Note: legal-hold has distinct semantics per S7.15 -- it has no event-based resumeTrigger, survives terminal workflow states, and blocks data destruction/retention expiry regardless of ordinary workflow state.
   */
  holdType: string;
  /**
   * ISO 8601 duration or the string 'indefinite'.
   */
  expectedDuration: string;
  /**
   * Event name that resumes the case from this hold. The processor listens for this event -- NOT a FEL condition polled on a schedule.
   */
  resumeTrigger?: string;
  /**
   * Action when expectedDuration expires without the resume trigger (Governance S12.2). 'escalate': route to supervisor. 'auto-resume': resume the case automatically. 'cancel': cancel the case.
   */
  timeoutAction?: 'escalate' | 'auto-resume' | 'cancel';
  /**
   * Reference to a Notification Template sidecar for hold notifications.
   */
  notificationTemplateRef?: string;
  /**
   * FEL expression that determines when this hold policy applies (Runtime Companion S8.2). Evaluated against the evaluation context. When absent, the policy applies to all holds of the declared holdType.
   */
  scope?: string;
  /**
   * Human-readable description of this hold policy.
   */
  description?: string;
}
