/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Delivery Config sidecar document. Consolidates three deployment-environment concerns that share a single tenancy and lifecycle: business calendar (working days, holidays, operating hours for SLA evaluation), notification templates (reusable notice bodies for adverse-decision, hold, appeal, and SLA notifications), and correspondence metadata (templates for cataloging inbound/outbound case communications). Delivery prose lives in `specs/sidecars/delivery.md`. Joined to a workflow by `targetWorkflow` URI. Per ADR 0076 D-3: replaces the prior wos-business-calendar, wos-notification-template, and wos-correspondence-metadata sidecars; the schema family lands at six files with the delivery and ontology-alignment sidecars as the only sidecars. At least one of `calendar` / `notifications` / `correspondence` MUST be present; absent blocks indicate a deployment that does not require that concern.
 */
export type WOSDeliveryConfig = {
  [k: string]: unknown;
} & {
  /**
   * WOS Delivery Config specification version. MUST be '1.0'. Identifies this document as a WOS Delivery Config sidecar (calendar + notifications + correspondence) and pins the specification version. Processors reject documents with unsupported versions.
   */
  $wosDelivery: '1.0';
  $schema?: JsonSchemaUri;
  /**
   * Absolute URI of the WOS Kernel Document this delivery sidecar applies to. Processors load the sidecar when the kernel document's URI matches and resolve calendar lookups, notification template keys, and correspondence templates against this single document. When multiple delivery sidecars target the same workflow, the most recently effective one wins for calendar resolution (Governance S10.3); for templates and correspondence, processors merge by key and reject duplicates.
   */
  targetWorkflow: string;
  /**
   * Version of this Delivery Config document. SemVer is RECOMMENDED. Increment when calendar holiday lists, notification template content, or correspondence templates change.
   */
  version?: string;
  /**
   * Human-readable name for this delivery configuration. Displayed in provenance audit trails and tooling when identifying the deployment-environment configuration for this workflow.
   */
  title?: string;
  /**
   * Human-readable description of this delivery configuration. Documents which jurisdiction's calendar applies, which notification templates are configured, and which correspondence channels are enabled for the target workflow.
   */
  description?: string;
  calendar?: CalendarBlock;
  notifications?: NotificationsBlock;
  correspondence?: CorrespondenceBlock;
  extensions?: ExtensionsMap;
};
/**
 * Optional JSON Schema URI enabling editor validation and autocompletion. When present, editors (VS Code, IntelliJ, etc.) validate the document against this schema. Omit in production documents; the authoritative schema URI is derived from the document type marker (e.g., '$wosDelivery': '1.0'). Used for author-time tooling only — runtime processors MUST ignore this field.
 */
export type JsonSchemaUri = string;

/**
 * Business calendar block. Defines business days, holiday schedules, and operating hours for SLA evaluation and temporal parameter resolution. Government workflows measure deadlines in business days, not wall-clock time: a 30-day response window excludes weekends and holidays. Consumed by Governance S10.3 (SLA evaluation) and Governance S13.3 (temporal parameter resolution). See Delivery §2. When absent, SLA evaluation uses wall-clock time.
 */
export interface CalendarBlock {
  /**
   * IANA timezone identifier. All time calculations for this calendar use this timezone. Operating hours (when present) are interpreted in this timezone.
   */
  timezone: string;
  /**
   * Ordered list of working days. A date is a business day only if its day-of-week appears in this array and the date is not a holiday. Standard US federal work week: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'].
   *
   * @minItems 1
   */
  workWeek: [
    'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday',
    ...('monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday')[],
  ];
  /**
   * Holiday schedule. Days listed here are non-working regardless of workWeek. Includes both fixed-date holidays (e.g., July 4) and floating holidays (e.g., third Monday of January).
   */
  holidays?: Holiday[];
  operatingHours?: OperatingHours;
  /**
   * Date this calendar becomes effective (ISO 8601 date). When absent, the calendar is effective immediately.
   */
  effectiveDate?: string;
  /**
   * Date this calendar expires (ISO 8601 date). A processor MUST ignore an expired calendar and fall back to wall-clock time.
   */
  expirationDate?: string;
  /**
   * FEL expression evaluated against the case file to determine whether this calendar applies to a given case. Multi-jurisdiction workflows declare one calendar per jurisdiction and use this expression to route a case to the right one (Business Calendar §7.1). Evaluated whenever an SLA or temporal-parameter resolution requires a calendar; calendars whose expression evaluates false are excluded from composition. When absent, the calendar applies unconditionally to every case targeting the same workflow — equivalent to `appliesWhen: 'true'`. The expression sees the same evaluation context as governance FEL expressions: case-file fields, lifecycle state, actor metadata. See Kernel §7 for FEL grammar.
   */
  appliesWhen?: string;
}
export interface Holiday {
  /**
   * Human-readable holiday name displayed in provenance audit trails and SLA calculation logs. Used to identify which holiday caused a business-day adjustment.
   */
  name: string;
  /**
   * Fixed date for this holiday (ISO 8601 date). Required when 'rule' is not specified. One of 'date' or 'rule' MUST be present.
   */
  date?: string;
  /**
   * Recurrence rule for floating holidays. Required when 'date' is not specified. Standard rules: 'nthWeekday(n, weekday, month)' for the nth weekday in a month, 'lastWeekday(weekday, month)' for the last weekday in a month. Extension rules use the `x-` prefix. One of 'date' or 'rule' MUST be present.
   */
  rule?: {
    [k: string]: unknown;
  } & string;
  /**
   * Whether this entry is an observed date rather than the actual holiday. When a fixed-date holiday falls on a non-working day, a separate entry with 'observed: true' marks the actual day off.
   */
  observed?: boolean;
}
/**
 * Working hours within a business day. When present and an SLA is specified in hours, the processor counts only elapsed time during these hours. When absent, a business day is the full 24-hour period.
 */
export interface OperatingHours {
  /**
   * Start of the operating period (HH:MM in 24-hour format, interpreted in the calendar's timezone). The operating period is [start, end) — inclusive of start, exclusive of end. Hour-based SLA counters only accumulate time within this window.
   */
  start: string;
  /**
   * End of the operating period (HH:MM in 24-hour format, interpreted in the calendar's timezone). MUST be strictly after 'start'. Hour-based SLA counters stop accumulating at this time each business day and resume at 'start' the next business day.
   */
  end: string;
}
/**
 * Notification templates block. Defines reusable templates for notices generated during governance events: adverse decision notices, hold notifications, appeal acknowledgments, SLA warnings, and case status updates. Templates separate notice content from governance logic, enabling independent versioning, localization, and audit. Referenced by `notificationTemplateKey` (Governance S12.2) and `noticeTemplateKey` (Governance S3.1). See Delivery §3.
 */
export interface NotificationsBlock {
  /**
   * Named notification templates. Template keys are the identifiers referenced by notificationTemplateKey (Governance S12.2) and noticeTemplateKey (Governance S3.1) in governance documents.
   */
  templates: {
    [k: string]: NotificationTemplate;
  };
}
export interface NotificationTemplate {
  /**
   * Template category. Determines which governance mechanism uses this template. 'adverse-decision': adverse decision notice (Governance S3.1-S3.2). 'hold-notification': hold notice (Governance S12.2). 'appeal-acknowledgment': appeal receipt confirmation (Governance S3.5). 'sla-warning': SLA deadline warning (Governance S10.3). 'case-status-update': general case status notification. 'resume-notification': notice that a case resumed from hold (Governance S12.3).
   */
  category:
    | 'adverse-decision'
    | 'hold-notification'
    | 'appeal-acknowledgment'
    | 'sla-warning'
    | 'case-status-update'
    | 'resume-notification';
  /**
   * Human-readable description of when this template is used and what regulatory obligation it satisfies. Referenced in audit logs.
   */
  description?: string;
  /**
   * Subject line or title for the notification. MAY contain placeholder variables using {{variableName}} syntax.
   */
  subject?: string;
  /**
   * Ordered content sections composing the notification body. For 'adverse-decision' templates, sections MUST address: specific determination, individualized reason codes, appeal rights and filing deadline, and appeal instructions (Notification Template S4.4).
   *
   * @minItems 1
   */
  sections: [TemplateSection, ...TemplateSection[]];
  /**
   * Variables that MUST be present in the rendering context. If any required variable is missing, the processor MUST NOT send the notification and MUST record the failure in provenance.
   */
  requiredVariables?: string[];
  /**
   * Channels through which this notification can be delivered. 'postal': physical mail. 'email': electronic mail. 'portal': web portal notification. 'sms': text message. 'in-app': in-application notification. When absent, delivery channel is implementation-defined.
   */
  deliveryChannels?: ('postal' | 'email' | 'portal' | 'sms' | 'in-app')[];
  /**
   * BCP 47 language tag reference to a locale-specific variant of this template. When the recipient's locale matches, the localized template is used instead of the default.
   */
  localeRef?: string;
  /**
   * Regulatory or statutory authority requiring this notification.
   */
  authority?: string;
  extensions?: ExtensionsMap;
}
export interface TemplateSection {
  /**
   * Section identifier unique within the template. Used in audit logs and accessibility anchors. Referenced by condition expressions to target specific sections.
   */
  id: string;
  /**
   * Section heading displayed in the rendered notification. Rendered as a visible heading above the section content in postal, email, and portal output.
   */
  title?: string;
  /**
   * Type of content in this section. 'text': free-text with optional placeholders. 'structured': structured content with labeled fields. 'appeal-rights': standardized appeal rights block (must include filing deadline, review body, continuation status). 'action-required': describes actions the recipient must take. 'contact-information': contact details for questions.
   */
  contentType: 'text' | 'structured' | 'appeal-rights' | 'action-required' | 'contact-information';
  /**
   * Content body. MAY contain placeholder variables using {{variableName}} syntax. Required when contentType is 'text' or 'structured'. For 'appeal-rights', 'action-required', and 'contact-information', content provides additional context beyond the structured elements.
   */
  content?: string;
  /**
   * Whether this section MUST appear in the rendered notification. Default: true. For adverse-decision templates, due-process sections (determination, reasons, appealRights) MUST be required.
   */
  required?: boolean;
  /**
   * FEL expression that controls section visibility. When the expression evaluates to false, the section is omitted from the rendered notification. Evaluated against the standard FEL evaluation context (Kernel S7.3).
   */
  condition?: string;
}
/**
 * Vendor extension data attached to this node. All keys MUST start with 'x-' (see Kernel §10.6). The reserved namespace 'x-wos-*' is for WOS Working Group use only; third-party extensions MUST use a unique vendor prefix (e.g., 'x-acme-', 'x-vendor-'). Processors MUST ignore unknown extension keys to preserve forward compatibility. Extension values are unconstrained — any JSON value is valid, but authors are encouraged to document the shape in their vendor spec.
 */
export interface ExtensionsMap {
  [k: string]: unknown;
}
/**
 * Correspondence metadata block. Declares the metadata schema for correspondence entries (letters, phone calls, emails, portal submissions, in-person interactions) stored in case state. The kernel's existing event mechanism handles correspondence events; this block defines structured metadata for consistent cataloging and retrieval without adding new event types or modifying lifecycle semantics. See Delivery §4.
 */
export interface CorrespondenceBlock {
  /**
   * Dot-separated case state field path where correspondence entries are stored as an array. The workflow processor appends correspondence entry objects to this path when correspondence events are recorded in provenance. MUST refer to an array-typed field in the case state.
   */
  correspondenceField: string;
  /**
   * Templates defining the metadata structure for correspondence entries. Each template declares the channel, direction, correspondenceRole, and required fields for a category of correspondence. See Delivery §4.2-§4.3.
   *
   * @minItems 1
   */
  entryTemplates: [EntryTemplate, ...EntryTemplate[]];
}
/**
 * Template for correspondence entry metadata. See Delivery §4.2-§4.3 for the closed correspondence vocabulary and requiredFields convention.
 */
export interface EntryTemplate {
  /**
   * Unique template identifier. Referenced by correspondence entries via templateRef.
   */
  id: string;
  /**
   * Human-readable description of the correspondence category this template covers, used in tooling and audit summaries.
   */
  description?: string;
  /**
   * Communication channel. 'in-person': face-to-face contact. 'phone': telephone call. 'mail': physical mail. 'email': electronic mail. 'portal': web portal submission or message. 'fax': facsimile transmission. Extensible via x- prefixed values in the extensions property.
   */
  channel: 'in-person' | 'phone' | 'mail' | 'email' | 'portal' | 'fax';
  /**
   * Direction of the correspondence. 'inbound': received by the agency. 'outbound': sent by the agency.
   */
  direction: 'inbound' | 'outbound';
  /**
   * Who sent or received the correspondence. 'applicant': the primary case subject. 'representative': authorized representative acting on behalf of the applicant. 'third-party': external party (e.g., employer, medical provider). 'system': automated system-generated correspondence. 'agency': agency staff. Delivery uses correspondenceRole, not kernel actorType, because the kernel term names actor classification rather than correspondence party role.
   */
  correspondenceRole: 'applicant' | 'representative' | 'third-party' | 'system' | 'agency';
  /**
   * Fields that MUST be present in a correspondence entry using this template, beyond the base metadata (templateRef, channel, direction, correspondenceRole, contentRef, summary, timestamp). See Delivery §4.3.
   */
  requiredFields?: string[];
  extensions?: ExtensionsMap;
}
