/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A WOS Integration Profile Document per the WOS Integration Profile specification v1.0. A parallel seam document that declares named integration bindings for a WOS workflow: Arazzo sequences for multi-step API orchestration, CWL-informed tool descriptors for non-HTTP invocations, CloudEvents extension attributes for event interoperability, external policy engine bridges (XACML, OPA, Cedar), and standard request-response/event/callback patterns. Each binding declares interface references, input/output mappings, retry policies, and optional Formspec Definition contracts for request and response validation. The Integration Profile adds structure to the kernel's invokeService action (Kernel S9.2) without introducing new kernel seams. WOS MUST NOT alter core Formspec processing semantics.
 */
export interface WOSIntegrationProfileDocument {
  /**
   * WOS Integration Profile specification version. MUST be '1.0'. Identifies this document as a WOS Integration Profile Document and pins the specification version.
   */
  $wosIntegrationProfile: '1.0';
  /**
   * Optional JSON Schema URI for editor validation and autocompletion.
   */
  $schema?: string;
  /**
   * The WOS Kernel Document this profile targets. Specifies URL and compatible version range.
   */
  targetWorkflow: IntegrationProfileTargetWorkflow;
  /**
   * Version of this Integration Profile Document. SemVer is RECOMMENDED.
   */
  version?: string;
  /**
   * Human-readable name for this integration profile.
   */
  title?: string;
  /**
   * Human-readable description of the integration profile's purpose and scope.
   */
  description?: string;
  /**
   * Named integration bindings. Keys are binding identifiers referenced by invokeService serviceRef (Kernel S9.2). Values are typed binding declarations.
   */
  bindings: {
    [k: string]: IntegrationBinding;
  };
  /**
   * Extension data for this Integration Profile Document. Property names MUST begin with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface IntegrationProfileTargetWorkflow {
  /**
   * Canonical URI of the target WOS Kernel Document.
   */
  url: string;
  /**
   * SemVer range expression for compatible kernel document versions.
   */
  compatibleVersions?: string;
}
/**
 * A named integration binding declaration. The type property determines which additional properties are valid.
 */
export interface IntegrationBinding {
  /**
   * Integration binding type (Integration Profile S3.2). Standard types: request-response, event-emit, event-consume, callback, arazzo-sequence, tool, policy-engine. Custom types use x- prefix.
   */
  type: string;
  /**
   * Human-readable description of this integration binding.
   */
  description?: string;
  /**
   * OpenAPI interface reference. Required for request-response and callback bindings.
   */
  interface?: InterfaceRef;
  /**
   * Operation ID within the referenced OpenAPI document. Required for request-response and callback bindings.
   */
  operation?: string;
  /**
   * URI reference to the Arazzo document. Required for arazzo-sequence bindings.
   */
  arazzoRef?: string;
  /**
   * Invocation descriptor for non-HTTP tool bindings. Required for tool bindings.
   */
  invocation?: InvocationDescriptor;
  /**
   * Policy engine type (Integration Profile S8.2). Standard types: xacml, opa, cedar. Custom types use x- prefix.
   */
  engineType?: string;
  /**
   * The policy engine's decision endpoint. Required for policy-engine bindings.
   */
  endpoint?: string;
  /**
   * Maps WOS evaluation context fields to policy engine request parameters. Keys are engine-specific parameter names; values are FEL expressions or case state paths. Required for policy-engine bindings.
   */
  contextMapping?: {
    [k: string]: string;
  };
  /**
   * Maps the policy engine's response to a WOS governance decision. Required for policy-engine bindings.
   */
  decisionMapping?: DecisionMapping;
  /**
   * CloudEvents type attribute value. Required for event-emit, event-consume, and callback (as callbackEventType) bindings.
   */
  eventType?: string;
  /**
   * CloudEvents type attribute value of the expected callback event. Required for callback bindings.
   */
  callbackEventType?: string;
  /**
   * Correlation rules for matching inbound events to workflow instances (Integration Profile S6). Required for event-consume and callback bindings.
   */
  correlation?: CorrelationRule[];
  /**
   * Maps case state paths to event data fields. Keys are event data field names; values are FEL expressions or case state paths. Used with event-emit bindings.
   */
  dataMapping?: {
    [k: string]: string;
  };
  /**
   * Delivery channel hint (e.g., 'email', 'webhook', 'queue'). Implementation-defined. Used with event-emit bindings.
   */
  channel?: string;
  /**
   * Maps case state paths to service/tool input parameters. Keys are parameter names; values are FEL expressions or case state paths.
   */
  inputMapping?: {
    [k: string]: string;
  };
  /**
   * Maps service/tool output to case state paths. Keys are case state paths; values are JSON Path expressions into the response.
   */
  outputBinding?: {
    [k: string]: string;
  };
  /**
   * Formspec Definition contract for request validation (Integration Profile S4).
   */
  requestContract?: ContractRef;
  /**
   * Formspec Definition contract for response validation (Integration Profile S4).
   */
  responseContract?: ContractRef;
  /**
   * Resource constraints for tool bindings (Integration Profile S3.6.2).
   */
  resourceRequirements?: ResourceRequirements;
  /**
   * Retry policy for failed invocations (Integration Profile S3.8).
   */
  retry?: RetryPolicy;
  /**
   * Maximum time to wait for a response. ISO 8601 duration.
   */
  timeout?: string;
  /**
   * FEL expression evaluated against case state to produce an idempotency key (Integration Profile S7). Maps to Kernel S9.3.
   */
  idempotencyKeyExpression?: string;
  /**
   * Extension data for this binding. Property names MUST begin with 'x-'.
   */
  extensions?: {
    [k: string]: unknown;
  };
}
export interface InterfaceRef {
  /**
   * URI reference to an OpenAPI document.
   */
  $ref: string;
}
/**
 * Non-HTTP invocation descriptor informed by CWL's CommandLineTool pattern (Integration Profile S3.6.1).
 */
export interface InvocationDescriptor {
  /**
   * Invocation method. Standard methods: command-line, batch-file, database-procedure, graph-query. Custom methods use x- prefix.
   */
  method: string;
  /**
   * The command, procedure name, or query to execute.
   */
  command: string;
  /**
   * Ordered command arguments. FEL expressions in {{ }} delimiters are evaluated against case state before invocation.
   */
  arguments?: string[];
  /**
   * Execution environment metadata (e.g., container image, runtime version). Implementation-defined.
   */
  environment?: {
    [k: string]: unknown;
  };
}
/**
 * Reference to a Formspec Definition used as a validation contract (Integration Profile S4).
 */
export interface ContractRef {
  /**
   * URI reference to the Formspec Definition used for validation. The processor MUST delegate validation to a Formspec-conformant processor (Core S1.4).
   */
  definitionRef: string;
}
/**
 * A correlation rule for matching inbound events to workflow instances (Integration Profile S6).
 */
export interface CorrelationRule {
  /**
   * The CloudEvents attribute or extension attribute containing the correlation value.
   */
  attribute: string;
  /**
   * The case state path whose value MUST match the correlation attribute.
   */
  caseStateMapping: string;
}
/**
 * Maps a policy engine's response to a WOS governance decision (Integration Profile S8.3).
 */
export interface DecisionMapping {
  /**
   * JSON Path expression into the engine's response that evaluates to a boolean indicating 'permit'.
   */
  permitPath: string;
  /**
   * JSON Path expression for explicit 'deny'. If omitted, deny is inferred as the negation of permit.
   */
  denyPath?: string;
  /**
   * JSON Path expression for the engine's human-readable reason. Recorded in provenance.
   */
  reasonPath?: string;
  /**
   * JSON Path expression for obligations attached to the decision (XACML obligation pattern).
   */
  obligationsPath?: string;
  /**
   * JSON Path expression for 'indeterminate' (engine could not decide). When present and truthy, the decision is indeterminate. If omitted, indeterminate is not possible -- results are always permit or deny.
   */
  indeterminatePath?: string;
}
/**
 * Retry policy for failed integration invocations (Integration Profile S3.8).
 */
export interface RetryPolicy {
  /**
   * Maximum number of invocation attempts (including the initial attempt).
   */
  maxAttempts: number;
  /**
   * Backoff strategy between retries. 'fixed': constant interval. 'linear': interval grows linearly. 'exponential': interval doubles each retry.
   */
  backoff?: 'fixed' | 'linear' | 'exponential';
  /**
   * Initial interval between retries. ISO 8601 duration.
   */
  initialInterval?: string;
  /**
   * Maximum interval between retries (for exponential/linear backoff). ISO 8601 duration.
   */
  maxInterval?: string;
}
/**
 * Resource constraints for tool invocations (Integration Profile S3.6.2).
 */
export interface ResourceRequirements {
  /**
   * Maximum execution time. ISO 8601 duration. The processor MUST terminate the invocation if exceeded.
   */
  maxExecutionTime?: string;
  /**
   * Maximum memory allocation (e.g., '512MB', '2GB'). Implementation-defined enforcement.
   */
  maxMemory?: string;
  /**
   * Maximum CPU cores. Implementation-defined enforcement.
   */
  maxCores?: number;
}
/**
 * WOS CloudEvents extension attributes (Integration Profile S5). All events produced by a WOS workflow MUST include these attributes.
 */
export interface CloudEventsExtension {
  /**
   * The workflow instance identifier.
   */
  wosinstanceid: string;
  /**
   * The workflow definition identifier (kernel document URL).
   */
  wosdefid: string;
  /**
   * The workflow definition version (kernel document version).
   */
  wosdefversion: string;
  /**
   * The current lifecycle state at the time of event emission.
   */
  wosstate?: string;
  /**
   * The task identifier, if the event relates to a task.
   */
  wostaskid?: string;
  /**
   * The primary business correlation key for the workflow instance.
   */
  woscorrelationkey?: string;
  /**
   * The CloudEvents id of the event that triggered this event. Enables causal chains.
   */
  woscausationeventid?: string;
}
